version: '3.3'

volumes:
    symfony:

services:

    mysql:
        image: mysql:5.7
        restart: unless-stopped
        volumes:
            - ~/sirano-vol/mysql:/var/lib/mysql
        networks:
            sirano:
                ipv4_address: 172.10.0.7

    php:
        build:
            context: ./
            dockerfile: ./docker/php/Dockerfile
        restart: unless-stopped
        depends_on:
            - mysql
        volumes:
            - ./.env-dev:/var/www/symfony/.env
            - symfony:/var/www/symfony/public
            - ~/sirano-vol/media:/var/www/symfony/public/uploads
        networks:
            sirano:
                ipv4_address: 172.10.0.5

    nginx:
        build:
            context: ./
            dockerfile: ./docker/nginx/Dockerfile
        restart: unless-stopped
        ports: 
            - '80:80'
            - '443:443'
        depends_on:
            - php
        volumes:
            - symfony:/var/www/symfony/public:ro
            - ~/sirano-vol/media:/var/www/symfony/public/uploads:ro
            - ~/sirano-vol/nginx/sirano-dev.conf:/etc/nginx/conf.d/default.conf:ro
            - ~/sirano-vol/logs/nginx:/var/log/nginx
        networks:
            sirano:
                ipv4_address: 172.10.0.6

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        ports:
            - '8001:80'
        depends_on:
            - mysql
        environment:
            - PMA_HOST=mysql
            - PMA_USER=root
            - PMA_PASSWORD=root
        networks:
            - sirano

networks:
    sirano:
        driver: bridge
        ipam:
            config:
                 - subnet: 172.10.0.0/28