<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20190731105354 extends AbstractMigration
{
    public function getDescription() : string
    {
        return '';
    }

    public function up(Schema $schema) : void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() !== 'mysql', 'Migration can only be executed safely on \'mysql\'.');
    
        $this->addSql("UPDATE `customers` SET `city_id` = (SELECT `id` FROM `customer_city` WHERE `kladr_id` = '6600000400200') WHERE `city_name` = 'baltim';");
        $this->addSql("UPDATE `customers` SET `city_id` = (SELECT `id` FROM `customer_city` WHERE `kladr_id` = '8600001000000') WHERE `city_name` = 'cургут';");
        $this->addSql("UPDATE `customers` SET `city_id` = (SELECT `id` FROM `customer_city` WHERE `kladr_id` = '8600001000000') WHERE `city_name` = 'сургут';");
        $this->addSql("UPDATE `customers` SET `city_id` = (SELECT `id` FROM `customer_city` WHERE `kladr_id` = '1500400100000') WHERE `city_name` = 'digora';");
        $this->addSql("UPDATE `customers` SET `city_id` = (SELECT `id` FROM `customer_city` WHERE `kladr_id` = '6600000100000') WHERE `city_name` = 'ekaterinburg';");
        $this->addSql("UPDATE `customers` SET `city_id` = (SELECT `id` FROM `customer_city` WHERE `kladr_id` = '6600000100000') WHERE `city_name` = 'екаиеринбург';");
        $this->addSql("UPDATE `customers` SET `city_id` = (SELECT `id` FROM `customer_city` WHERE `kladr_id` = '6600000100000') WHERE `city_name` = 'екатеринабург';");
        $this->addSql("UPDATE `customers` SET `city_id` = (SELECT `id` FROM `customer_city` WHERE `kladr_id` = '6600000100000') WHERE `city_name` = 'екатеринбург';");
        $this->addSql("UPDATE `customers` SET `city_id` = (SELECT `id` FROM `customer_city` WHERE `kladr_id` = '5000003200000') WHERE `city_name` = 'kotelniki';");
        $this->addSql("UPDATE `customers` SET `city_id` = (SELECT `id` FROM `customer_city` WHERE `kladr_id` = '2400000100000') WHERE `city_name` = 'krasnoyarsk';");
        $this->addSql("UPDATE `customers` SET `city_id` = (SELECT `id` FROM `customer_city` WHERE `kladr_id` = '2400000100000') WHERE `city_name` = 'г. красноярск';");
        $this->addSql("UPDATE `customers` SET `city_id` = (SELECT `id` FROM `customer_city` WHERE `kladr_id` = '2400000100000') WHERE `city_name` = 'красноярск';");
        $this->addSql("UPDATE `customers` SET `city_id` = (SELECT `id` FROM `customer_city` WHERE `kladr_id` = '7700000000000') WHERE `city_name` = 'moscow';");
        $this->addSql("UPDATE `customers` SET `city_id` = (SELECT `id` FROM `customer_city` WHERE `kladr_id` = '7700000000000') WHERE `city_name` = 'г москва';");
        $this->addSql("UPDATE `customers` SET `city_id` = (SELECT `id` FROM `customer_city` WHERE `kladr_id` = '7700000000000') WHERE `city_name` = 'г. москва';");
        $this->addSql("UPDATE `customers` SET `city_id` = (SELECT `id` FROM `customer_city` WHERE `kladr_id` = '7700000000000') WHERE `city_name` = 'москва';");
        $this->addSql("UPDATE `customers` SET `city_id` = (SELECT `id` FROM `customer_city` WHERE `kladr_id` = '7700000000000') WHERE `city_name` = 'москваa';");
        $this->addSql("UPDATE `customers` SET `city_id` = (SELECT `id` FROM `customer_city` WHERE `kladr_id` = '8600001100000') WHERE `city_name` = 'nizhnevartovsk';");
        $this->addSql("UPDATE `customers` SET `city_id` = (SELECT `id` FROM `customer_city` WHERE `kladr_id` = '8600001100000') WHERE `city_name` = 'нижневартовск';");
        $this->addSql("UPDATE `customers` SET `city_id` = (SELECT `id` FROM `customer_city` WHERE `kladr_id` = '5400000100000') WHERE `city_name` = 'novosibirsk';");
        $this->addSql("UPDATE `customers` SET `city_id` = (SELECT `id` FROM `customer_city` WHERE `kladr_id` = '5400000100000') WHERE `city_name` = 'новосибирск';");
        $this->addSql("UPDATE `customers` SET `city_id` = (SELECT `id` FROM `customer_city` WHERE `kladr_id` = '6200000100000') WHERE `city_name` = 'ryazan';");
        $this->addSql("UPDATE `customers` SET `city_id` = (SELECT `id` FROM `customer_city` WHERE `kladr_id` = '6200000100000') WHERE `city_name` = 'рязань';");
        $this->addSql("UPDATE `customers` SET `city_id` = (SELECT `id` FROM `customer_city` WHERE `kladr_id` = '7601500100000') WHERE `city_name` = 'rybinsk';");
        $this->addSql("UPDATE `customers` SET `city_id` = (SELECT `id` FROM `customer_city` WHERE `kladr_id` = '7601500100000') WHERE `city_name` = 'рыбинск';");
        $this->addSql("UPDATE `customers` SET `city_id` = (SELECT `id` FROM `customer_city` WHERE `kladr_id` = '7800000000000') WHERE `city_name` = 'saint petersburg';");
        $this->addSql("UPDATE `customers` SET `city_id` = (SELECT `id` FROM `customer_city` WHERE `kladr_id` = '7800000000000') WHERE `city_name` = 'saint-petersburg';");
        $this->addSql("UPDATE `customers` SET `city_id` = (SELECT `id` FROM `customer_city` WHERE `kladr_id` = '7800000000000') WHERE `city_name` = 'петербург';");
        $this->addSql("UPDATE `customers` SET `city_id` = (SELECT `id` FROM `customer_city` WHERE `kladr_id` = '7800000000000') WHERE `city_name` = 'санкт -петербург';");
        $this->addSql("UPDATE `customers` SET `city_id` = (SELECT `id` FROM `customer_city` WHERE `kladr_id` = '7800000000000') WHERE `city_name` = 'санкт петербург';");
        $this->addSql("UPDATE `customers` SET `city_id` = (SELECT `id` FROM `customer_city` WHERE `kladr_id` = '7800000000000') WHERE `city_name` = 'санкт_петербург';");
        $this->addSql("UPDATE `customers` SET `city_id` = (SELECT `id` FROM `customer_city` WHERE `kladr_id` = '7800000000000') WHERE `city_name` = 'санкт- петербург';");
        $this->addSql("UPDATE `customers` SET `city_id` = (SELECT `id` FROM `customer_city` WHERE `kladr_id` = '7800000000000') WHERE `city_name` = 'санкт-петербург';");
        $this->addSql("UPDATE `customers` SET `city_id` = (SELECT `id` FROM `customer_city` WHERE `kladr_id` = '7800000000000') WHERE `city_name` = 'спб';");
        $this->addSql("UPDATE `customers` SET `city_id` = (SELECT `id` FROM `customer_city` WHERE `kladr_id` = '6900000100000') WHERE `city_name` = 'tver';");
        $this->addSql("UPDATE `customers` SET `city_id` = (SELECT `id` FROM `customer_city` WHERE `kladr_id` = '6900000100000') WHERE `city_name` = 'тверь';");
        $this->addSql("UPDATE `customers` SET `city_id` = (SELECT `id` FROM `customer_city` WHERE `kladr_id` = '1900000100000') WHERE `city_name` = 'абакан';");
        $this->addSql("UPDATE `customers` SET `city_id` = (SELECT `id` FROM `customer_city` WHERE `kladr_id` = '0100000200000') WHERE `city_name` = 'адыгейск';");
        $this->addSql("UPDATE `customers` SET `city_id` = (SELECT `id` FROM `customer_city` WHERE `kladr_id` = '6100001300000') WHERE `city_name` = 'азов,ростовская область';");
        $this->addSql("UPDATE `customers` SET `city_id` = (SELECT `id` FROM `customer_city` WHERE `kladr_id` = '6100001300000') WHERE `city_name` = 'рост.обл азов';");
        $this->addSql("UPDATE `customers` SET `city_id` = (SELECT `id` FROM `customer_city` WHERE `kladr_id` = '2200000000000') WHERE `city_name` = 'алтайский край';");
        $this->addSql("UPDATE `customers` SET `city_id` = (SELECT `id` FROM `customer_city` WHERE `kladr_id` = '9100001100000') WHERE `city_name` = 'алушта';");
        $this->addSql("UPDATE `customers` SET `city_id` = (SELECT `id` FROM `customer_city` WHERE `kladr_id` = '1600800100000') WHERE `city_name` = 'альметьевск';");
        $this->addSql("UPDATE `customers` SET `city_id` = (SELECT `id` FROM `customer_city` WHERE `kladr_id` = '2700000300000') WHERE `city_name` = 'амурск';");
        $this->addSql("UPDATE `customers` SET `city_id` = (SELECT `id` FROM `customer_city` WHERE `kladr_id` = '2300300100000') WHERE `city_name` = 'анапа';");
        $this->addSql("UPDATE `customers` SET `city_id` = (SELECT `id` FROM `customer_city` WHERE `kladr_id` = '3600200000100') WHERE `city_name` = 'анна';");
        $this->addSql("UPDATE `customers` SET `city_id` = (SELECT `id` FROM `customer_city` WHERE `kladr_id` = '2500200000100') WHERE `city_name` = 'анучино';");
        $this->addSql("UPDATE `customers` SET `city_id` = (SELECT `id` FROM `customer_city` WHERE `kladr_id` = '5002000200000') WHERE `city_name` = 'апрелевка';");
        $this->addSql("UPDATE `customers` SET `city_id` = (SELECT `id` FROM `customer_city` WHERE `kladr_id` = '7402600000100') WHERE `city_name` = 'аргаяш';");
        $this->addSql("UPDATE `customers` SET `city_id` = (SELECT `id` FROM `customer_city` WHERE `kladr_id` = '2900000100000') WHERE `city_name` = 'архангельск';");
        $this->addSql("UPDATE `customers` SET `city_id` = (SELECT `id` FROM `customer_city` WHERE `kladr_id` = '6600000200000') WHERE `city_name` = 'асбест';");
        $this->addSql("UPDATE `customers` SET `city_id` = (SELECT `id` FROM `customer_city` WHERE `kladr_id` = '7400200300000') WHERE `city_name` = 'аша';");
        $this->addSql("UPDATE `customers` SET `city_id` = (SELECT `id` FROM `customer_city` WHERE `kladr_id` = '6400000400000') WHERE `city_name` = 'балаково';");
        $this->addSql("UPDATE `customers` SET `city_id` = (SELECT `id` FROM `customer_city` WHERE `kladr_id` = '5200400100000') WHERE `city_name` = 'балахна';");
        $this->addSql("UPDATE `customers` SET `city_id` = (SELECT `id` FROM `customer_city` WHERE `kladr_id` = '5200400100000') WHERE `city_name` = 'нижний новгород нижегородская область г. балахна';");
        $this->addSql("UPDATE `customers` SET `city_id` = (SELECT `id` FROM `customer_city` WHERE `kladr_id` = '5000003600000') WHERE `city_name` = 'балашиха';");
        $this->addSql("UPDATE `customers` SET `city_id` = (SELECT `id` FROM `customer_city` WHERE `kladr_id` = '5000003600000') WHERE `city_name` = 'балашиха московской обл';");
        $this->addSql("UPDATE `customers` SET `city_id` = (SELECT `id` FROM `customer_city` WHERE `kladr_id` = '5000003600000') WHERE `city_name` = 'балашиха, микр. заря';");
        $this->addSql("UPDATE `customers` SET `city_id` = (SELECT `id` FROM `customer_city` WHERE `kladr_id` = '2200000100000') WHERE `city_name` = 'барнал';");
        $this->addSql("UPDATE `customers` SET `city_id` = (SELECT `id` FROM `customer_city` WHERE `kladr_id` = '2200000100000') WHERE `city_name` = 'барнаул';");
        $this->addSql("UPDATE `customers` SET `city_id` = (SELECT `id` FROM `customer_city` WHERE `kladr_id` = '2200000100000') WHERE `city_name` = 'г.барнаул';");
        $this->addSql("UPDATE `customers` SET `city_id` = (SELECT `id` FROM `customer_city` WHERE `kladr_id` = '6100000300000') WHERE `city_name` = 'батайск';");
        $this->addSql("UPDATE `customers` SET `city_id` = (SELECT `id` FROM `customer_city` WHERE `kladr_id` = '6900300100000') WHERE `city_name` = 'бежецк';");
        $this->addSql("UPDATE `customers` SET `city_id` = (SELECT `id` FROM `customer_city` WHERE `kladr_id` = '3100000100000') WHERE `city_name` = 'белгород';");
        $this->addSql("UPDATE `customers` SET `city_id` = (SELECT `id` FROM `customer_city` WHERE `kladr_id` = '3100000100000') WHERE `city_name` = 'г.белгород';");
        $this->addSql("UPDATE `customers` SET `city_id` = (SELECT `id` FROM `customer_city` WHERE `kladr_id` = '2200000300000') WHERE `city_name` = 'белокуриха';");
        $this->addSql("UPDATE `customers` SET `city_id` = (SELECT `id` FROM `customer_city` WHERE `kladr_id` = '0201100100000') WHERE `city_name` = 'белорецк';");
        $this->addSql("UPDATE `customers` SET `city_id` = (SELECT `id` FROM `customer_city` WHERE `kladr_id` = '2300600100000') WHERE `city_name` = 'белореченск';");
        $this->addSql("UPDATE `customers` SET `city_id` = (SELECT `id` FROM `customer_city` WHERE `kladr_id` = '5900000200000') WHERE `city_name` = 'березники';");
        $this->addSql("UPDATE `customers` SET `city_id` = (SELECT `id` FROM `customer_city` WHERE `kladr_id` = '6600000300000') WHERE `city_name` = 'березовский';");
        $this->addSql("UPDATE `customers` SET `city_id` = (SELECT `id` FROM `customer_city` WHERE `kladr_id` = '2200000400000') WHERE `city_name` = 'бийск';");
        $this->addSql("UPDATE `customers` SET `city_id` = (SELECT `id` FROM `customer_city` WHERE `kladr_id` = '7900000100000') WHERE `city_name` = 'биробиджан';");
        $this->addSql("UPDATE `customers` SET `city_id` = (SELECT `id` FROM `customer_city` WHERE `kladr_id` = '0201300100000') WHERE `city_name` = 'бирск';");
        $this->addSql("UPDATE `customers` SET `city_id` = (SELECT `id` FROM `customer_city` WHERE `kladr_id` = '3101200100000') WHERE `city_name` = 'бирюч';");
        $this->addSql("UPDATE `customers` SET `city_id` = (SELECT `id` FROM `customer_city` WHERE `kladr_id` = '0201500100000') WHERE `city_name` = 'благовещенск рб';");
        $this->addSql("UPDATE `customers` SET `city_id` = (SELECT `id` FROM `customer_city` WHERE `kladr_id` = '2800000100000') WHERE `city_name` = 'благовещенск, амурская область, россия';");
        $this->addSql("UPDATE `customers` SET `city_id` = (SELECT `id` FROM `customer_city` WHERE `kladr_id` = '7100500100000') WHERE `city_name` = 'богородицк';");
        $this->addSql("UPDATE `customers` SET `city_id` = (SELECT `id` FROM `customer_city` WHERE `kladr_id` = '2500000700000') WHERE `city_name` = 'большой камень';");
        $this->addSql("UPDATE `customers` SET `city_id` = (SELECT `id` FROM `customer_city` WHERE `kladr_id` = '5200000500000') WHERE `city_name` = 'бор';");
        $this->addSql("UPDATE `customers` SET `city_id` = (SELECT `id` FROM `customer_city` WHERE `kladr_id` = '3800000500000') WHERE `city_name` = 'братск';");
        $this->addSql("UPDATE `customers` SET `city_id` = (SELECT `id` FROM `customer_city` WHERE `kladr_id` = '3200000100000') WHERE `city_name` = 'брянск';");
        $this->addSql("UPDATE `customers` SET `city_id` = (SELECT `id` FROM `customer_city` WHERE `kladr_id` = '2600700100000') WHERE `city_name` = 'буденновск';");
        $this->addSql("UPDATE `customers` SET `city_id` = (SELECT `id` FROM `customer_city` WHERE `kladr_id` = '4400300100000') WHERE `city_name` = 'буй';");
        $this->addSql("UPDATE `customers` SET `city_id` = (SELECT `id` FROM `customer_city` WHERE `kladr_id` = '3600600100000') WHERE `city_name` = 'бутурлиновка';");
        $this->addSql("UPDATE `customers` SET `city_id` = (SELECT `id` FROM `customer_city` WHERE `kladr_id` = '7400000200000') WHERE `city_name` = 'верхний уфалей';");
        $this->addSql("UPDATE `customers` SET `city_id` = (SELECT `id` FROM `customer_city` WHERE `kladr_id` = '6600000400000') WHERE `city_name` = 'верхняя пышма';");
        $this->addSql("UPDATE `customers` SET `city_id` = (SELECT `id` FROM `customer_city` WHERE `kladr_id` = '2500000100000') WHERE `city_name` = 'владивосто';");
        $this->addSql("UPDATE `customers` SET `city_id` = (SELECT `id` FROM `customer_city` WHERE `kladr_id` = '2500000100000') WHERE `city_name` = 'владивосток';");
        $this->addSql("UPDATE `customers` SET `city_id` = (SELECT `id` FROM `customer_city` WHERE `kladr_id` = '2500000100000') WHERE `city_name` = 'воадивосток';");
        $this->addSql("UPDATE `customers` SET `city_id` = (SELECT `id` FROM `customer_city` WHERE `kladr_id` = '2500000100000') WHERE `city_name` = 'г. владивосток';");
        $this->addSql("UPDATE `customers` SET `city_id` = (SELECT `id` FROM `customer_city` WHERE `kladr_id` = '1500000100000') WHERE `city_name` = 'владикавказ';");
        $this->addSql("UPDATE `customers` SET `city_id` = (SELECT `id` FROM `customer_city` WHERE `kladr_id` = '3300000100000') WHERE `city_name` = 'владимир';");
        $this->addSql("UPDATE `customers` SET `city_id` = (SELECT `id` FROM `customer_city` WHERE `kladr_id` = '6100000400000') WHERE `city_name` = 'вогодонск';");
        $this->addSql("UPDATE `customers` SET `city_id` = (SELECT `id` FROM `customer_city` WHERE `kladr_id` = '6100000400000') WHERE `city_name` = 'волгодонск';");
        $this->addSql("UPDATE `customers` SET `city_id` = (SELECT `id` FROM `customer_city` WHERE `kladr_id` = '3400000100000') WHERE `city_name` = 'волгоград';");
        $this->addSql("UPDATE `customers` SET `city_id` = (SELECT `id` FROM `customer_city` WHERE `kladr_id` = '3400000100000') WHERE `city_name` = 'волгорад';");
        $this->addSql("UPDATE `customers` SET `city_id` = (SELECT `id` FROM `customer_city` WHERE `kladr_id` = '3400000200000') WHERE `city_name` = 'волжский';");
        $this->addSql("UPDATE `customers` SET `city_id` = (SELECT `id` FROM `customer_city` WHERE `kladr_id` = '3400000200000') WHERE `city_name` = 'г. волжский';");
        $this->addSql("UPDATE `customers` SET `city_id` = (SELECT `id` FROM `customer_city` WHERE `kladr_id` = '3600000100000') WHERE `city_name` = 'воронеж';");
        $this->addSql("UPDATE `customers` SET `city_id` = (SELECT `id` FROM `customer_city` WHERE `kladr_id` = '4700600100000') WHERE `city_name` = 'выборг';");
        $this->addSql("UPDATE `customers` SET `city_id` = (SELECT `id` FROM `customer_city` WHERE `kladr_id` = '6700300100000') WHERE `city_name` = 'вязьма';");
        $this->addSql("UPDATE `customers` SET `city_id` = (SELECT `id` FROM `customer_city` WHERE `kladr_id` = '5000002400000') WHERE `city_name` = 'г подольск';");
        $this->addSql("UPDATE `customers` SET `city_id` = (SELECT `id` FROM `customer_city` WHERE `kladr_id` = '5000002400000') WHERE `city_name` = 'подольск';");
        $this->addSql("UPDATE `customers` SET `city_id` = (SELECT `id` FROM `customer_city` WHERE `kladr_id` = '4300000100000') WHERE `city_name` = 'г. киров';");
        $this->addSql("UPDATE `customers` SET `city_id` = (SELECT `id` FROM `customer_city` WHERE `kladr_id` = '4300000100000') WHERE `city_name` = 'киров';");
        $this->addSql("UPDATE `customers` SET `city_id` = (SELECT `id` FROM `customer_city` WHERE `kladr_id` = '4800000100000') WHERE `city_name` = 'г. липецк';");
        $this->addSql("UPDATE `customers` SET `city_id` = (SELECT `id` FROM `customer_city` WHERE `kladr_id` = '4800000100000') WHERE `city_name` = 'липецк';");
        $this->addSql("UPDATE `customers` SET `city_id` = (SELECT `id` FROM `customer_city` WHERE `kladr_id` = '5700000100000') WHERE `city_name` = 'г. орёл';");
        $this->addSql("UPDATE `customers` SET `city_id` = (SELECT `id` FROM `customer_city` WHERE `kladr_id` = '5700000100000') WHERE `city_name` = 'орел';");
        $this->addSql("UPDATE `customers` SET `city_id` = (SELECT `id` FROM `customer_city` WHERE `kladr_id` = '5700000100000') WHERE `city_name` = 'орео';");
        $this->addSql("UPDATE `customers` SET `city_id` = (SELECT `id` FROM `customer_city` WHERE `kladr_id` = '6700000300000') WHERE `city_name` = 'г. смоленск';");
        $this->addSql("UPDATE `customers` SET `city_id` = (SELECT `id` FROM `customer_city` WHERE `kladr_id` = '6700000300000') WHERE `city_name` = 'смоленск';");
        $this->addSql("UPDATE `customers` SET `city_id` = (SELECT `id` FROM `customer_city` WHERE `kladr_id` = '7100000100000') WHERE `city_name` = 'г. тула';");
        $this->addSql("UPDATE `customers` SET `city_id` = (SELECT `id` FROM `customer_city` WHERE `kladr_id` = '7100000100000') WHERE `city_name` = 'тула';");
        $this->addSql("UPDATE `customers` SET `city_id` = (SELECT `id` FROM `customer_city` WHERE `kladr_id` = '6400001300000') WHERE `city_name` = 'г. энгельс, саратовская обл.';");
        $this->addSql("UPDATE `customers` SET `city_id` = (SELECT `id` FROM `customer_city` WHERE `kladr_id` = '6400001300000') WHERE `city_name` = 'энгельс';");
        $this->addSql("UPDATE `customers` SET `city_id` = (SELECT `id` FROM `customer_city` WHERE `kladr_id` = '1601500100000') WHERE `city_name` = 'г.буинск республики татарстан';");
        $this->addSql("UPDATE `customers` SET `city_id` = (SELECT `id` FROM `customer_city` WHERE `kladr_id` = '0200000100000') WHERE `city_name` = 'г.уфа';");
        $this->addSql("UPDATE `customers` SET `city_id` = (SELECT `id` FROM `customer_city` WHERE `kladr_id` = '0200000100000') WHERE `city_name` = 'республика башкортостан, г.уфа';");
        $this->addSql("UPDATE `customers` SET `city_id` = (SELECT `id` FROM `customer_city` WHERE `kladr_id` = '0200000100000') WHERE `city_name` = 'уфа';");
        $this->addSql("UPDATE `customers` SET `city_id` = (SELECT `id` FROM `customer_city` WHERE `kladr_id` = '2300000300000') WHERE `city_name` = 'геленджик';");
        $this->addSql("UPDATE `customers` SET `city_id` = (SELECT `id` FROM `customer_city` WHERE `kladr_id` = '0500900000100') WHERE `city_name` = 'гергебиль';");
        $this->addSql("UPDATE `customers` SET `city_id` = (SELECT `id` FROM `customer_city` WHERE `kladr_id` = '5002200300000') WHERE `city_name` = 'голицино';");
        $this->addSql("UPDATE `customers` SET `city_id` = (SELECT `id` FROM `customer_city` WHERE `kladr_id` = '0400000100000') WHERE `city_name` = 'горно-алтайск';");
        $this->addSql("UPDATE `customers` SET `city_id` = (SELECT `id` FROM `customer_city` WHERE `kladr_id` = '5900000500000') WHERE `city_name` = 'губаха пермский край';");
        $this->addSql("UPDATE `customers` SET `city_id` = (SELECT `id` FROM `customer_city` WHERE `kladr_id` = '2300900100000') WHERE `city_name` = 'гулькевичи';");
        $this->addSql("UPDATE `customers` SET `city_id` = (SELECT `id` FROM `customer_city` WHERE `kladr_id` = '6200500005400') WHERE `city_name` = 'гусь-железный';");
        $this->addSql("UPDATE `customers` SET `city_id` = (SELECT `id` FROM `customer_city` WHERE `kladr_id` = '7600100060800') WHERE `city_name` = 'д. кузнечиха';");
        $this->addSql("UPDATE `customers` SET `city_id` = (SELECT `id` FROM `customer_city` WHERE `kladr_id` = '7600600100000') WHERE `city_name` = 'данилов';");
        $this->addSql("UPDATE `customers` SET `city_id` = (SELECT `id` FROM `customer_city` WHERE `kladr_id` = '7500700000800') WHERE `city_name` = 'даурия';");
        $this->addSql("UPDATE `customers` SET `city_id` = (SELECT `id` FROM `customer_city` WHERE `kladr_id` = '5000900200000') WHERE `city_name` = 'дедовск';");
        $this->addSql("UPDATE `customers` SET `city_id` = (SELECT `id` FROM `customer_city` WHERE `kladr_id` = '5000006100000') WHERE `city_name` = 'дмитров';");
        $this->addSql("UPDATE `customers` SET `city_id` = (SELECT `id` FROM `customer_city` WHERE `kladr_id` = '5000002900000') WHERE `city_name` = 'долгопрудный, московская обл., россия';");
        $this->addSql("UPDATE `customers` SET `city_id` = (SELECT `id` FROM `customer_city` WHERE `kladr_id` = '5000000100000') WHERE `city_name` = 'домодедово';");
        $this->addSql("UPDATE `customers` SET `city_id` = (SELECT `id` FROM `customer_city` WHERE `kladr_id` = '7100000200000') WHERE `city_name` = 'донской';");
        $this->addSql("UPDATE `customers` SET `city_id` = (SELECT `id` FROM `customer_city` WHERE `kladr_id` = '1601900100000') WHERE `city_name` = 'елабуга';");
        $this->addSql("UPDATE `customers` SET `city_id` = (SELECT `id` FROM `customer_city` WHERE `kladr_id` = '4800000200000') WHERE `city_name` = 'елец';");
        $this->addSql("UPDATE `customers` SET `city_id` = (SELECT `id` FROM `customer_city` WHERE `kladr_id` = '2400001400000') WHERE `city_name` = 'енисейск';");
        $this->addSql("UPDATE `customers` SET `city_id` = (SELECT `id` FROM `customer_city` WHERE `kladr_id` = '2600000300000') WHERE `city_name` = 'железноводск';");
        $this->addSql("UPDATE `customers` SET `city_id` = (SELECT `id` FROM `customer_city` WHERE `kladr_id` = '7200000400000') WHERE `city_name` = 'заводоуковск';");
        $this->addSql("UPDATE `customers` SET `city_id` = (SELECT `id` FROM `customer_city` WHERE `kladr_id` = '5100000300000') WHERE `city_name` = 'заозерск';");
        $this->addSql("UPDATE `customers` SET `city_id` = (SELECT `id` FROM `customer_city` WHERE `kladr_id` = '2200001100000') WHERE `city_name` = 'заринск';");
        $this->addSql("UPDATE `customers` SET `city_id` = (SELECT `id` FROM `customer_city` WHERE `kladr_id` = '2201600000100') WHERE `city_name` = 'зональное';");
        $this->addSql("UPDATE `customers` SET `city_id` = (SELECT `id` FROM `customer_city` WHERE `kladr_id` = '3700000100000') WHERE `city_name` = 'иваново';");
        $this->addSql("UPDATE `customers` SET `city_id` = (SELECT `id` FROM `customer_city` WHERE `kladr_id` = '5000000700000') WHERE `city_name` = 'ивантеевка, мо';");
        $this->addSql("UPDATE `customers` SET `city_id` = (SELECT `id` FROM `customer_city` WHERE `kladr_id` = '3800000300000') WHERE `city_name` = 'иркутск';");
        $this->addSql("UPDATE `customers` SET `city_id` = (SELECT `id` FROM `customer_city` WHERE `kladr_id` = '5000005700000') WHERE `city_name` = 'истра';");
        $this->addSql("UPDATE `customers` SET `city_id` = (SELECT `id` FROM `customer_city` WHERE `kladr_id` = '1200000100000') WHERE `city_name` = 'йошкар-ола';");
        $this->addSql("UPDATE `customers` SET `city_id` = (SELECT `id` FROM `customer_city` WHERE `kladr_id` = '1600000100000') WHERE `city_name` = 'казань';");
        $this->addSql("UPDATE `customers` SET `city_id` = (SELECT `id` FROM `customer_city` WHERE `kladr_id` = '3900000100000') WHERE `city_name` = 'калиниград';");
        $this->addSql("UPDATE `customers` SET `city_id` = (SELECT `id` FROM `customer_city` WHERE `kladr_id` = '3900000100000') WHERE `city_name` = 'калининград';");
        $this->addSql("UPDATE `customers` SET `city_id` = (SELECT `id` FROM `customer_city` WHERE `kladr_id` = '4000000100000') WHERE `city_name` = 'калуга';");
        $this->addSql("UPDATE `customers` SET `city_id` = (SELECT `id` FROM `customer_city` WHERE `kladr_id` = '4000000000000') WHERE `city_name` = 'калужская область';");
        $this->addSql("UPDATE `customers` SET `city_id` = (SELECT `id` FROM `customer_city` WHERE `kladr_id` = '6901100100000') WHERE `city_name` = 'калязин';");
        $this->addSql("UPDATE `customers` SET `city_id` = (SELECT `id` FROM `customer_city` WHERE `kladr_id` = '6600002200000') WHERE `city_name` = 'каменск- уральский';");
        $this->addSql("UPDATE `customers` SET `city_id` = (SELECT `id` FROM `customer_city` WHERE `kladr_id` = '6600002200000') WHERE `city_name` = 'каменск-уральский';");
        $this->addSql("UPDATE `customers` SET `city_id` = (SELECT `id` FROM `customer_city` WHERE `kladr_id` = '1602300000100') WHERE `city_name` = 'камское-устье';");
        $this->addSql("UPDATE `customers` SET `city_id` = (SELECT `id` FROM `customer_city` WHERE `kladr_id` = '6200000400000') WHERE `city_name` = 'касимов';");
        $this->addSql("UPDATE `customers` SET `city_id` = (SELECT `id` FROM `customer_city` WHERE `kladr_id` = '6900000900000') WHERE `city_name` = 'кашин';");
        $this->addSql("UPDATE `customers` SET `city_id` = (SELECT `id` FROM `customer_city` WHERE `kladr_id` = '4200000900000') WHERE `city_name` = 'кемерово';");
        $this->addSql("UPDATE `customers` SET `city_id` = (SELECT `id` FROM `customer_city` WHERE `kladr_id` = '1000400100000') WHERE `city_name` = 'кемь';");
        $this->addSql("UPDATE `customers` SET `city_id` = (SELECT `id` FROM `customer_city` WHERE `kladr_id` = '0500000700000') WHERE `city_name` = 'кизилюрт';");
        $this->addSql("UPDATE `customers` SET `city_id` = (SELECT `id` FROM `customer_city` WHERE `kladr_id` = '4700900100000') WHERE `city_name` = 'кириши';");
        $this->addSql("UPDATE `customers` SET `city_id` = (SELECT `id` FROM `customer_city` WHERE `kladr_id` = '6600000900000') WHERE `city_name` = 'кировград';");
        $this->addSql("UPDATE `customers` SET `city_id` = (SELECT `id` FROM `customer_city` WHERE `kladr_id` = '4300000400000') WHERE `city_name` = 'кирово-чепецк';");
        $this->addSql("UPDATE `customers` SET `city_id` = (SELECT `id` FROM `customer_city` WHERE `kladr_id` = '3300000400000') WHERE `city_name` = 'ковров';");
        $this->addSql("UPDATE `customers` SET `city_id` = (SELECT `id` FROM `customer_city` WHERE `kladr_id` = '8600000200000') WHERE `city_name` = 'когалым';");
        $this->addSql("UPDATE `customers` SET `city_id` = (SELECT `id` FROM `customer_city` WHERE `kladr_id` = '5000002700000') WHERE `city_name` = 'коломна';");
        $this->addSql("UPDATE `customers` SET `city_id` = (SELECT `id` FROM `customer_city` WHERE `kladr_id` = '5001200017300') WHERE `city_name` = 'коломна-1. городок';");
        $this->addSql("UPDATE `customers` SET `city_id` = (SELECT `id` FROM `customer_city` WHERE `kladr_id` = '3300900100000') WHERE `city_name` = 'кольчугино';");
        $this->addSql("UPDATE `customers` SET `city_id` = (SELECT `id` FROM `customer_city` WHERE `kladr_id` = '2700000500000') WHERE `city_name` = 'комсомольск-на-амуре';");
        $this->addSql("UPDATE `customers` SET `city_id` = (SELECT `id` FROM `customer_city` WHERE `kladr_id` = '6901500100000') WHERE `city_name` = 'конаково';");
        $this->addSql("UPDATE `customers` SET `city_id` = (SELECT `id` FROM `customer_city` WHERE `kladr_id` = '4000600100000') WHERE `city_name` = 'кондрово';");
        $this->addSql("UPDATE `customers` SET `city_id` = (SELECT `id` FROM `customer_city` WHERE `kladr_id` = '7404500100000') WHERE `city_name` = 'коркино';");
        $this->addSql("UPDATE `customers` SET `city_id` = (SELECT `id` FROM `customer_city` WHERE `kladr_id` = '5000000900000') WHERE `city_name` = 'королев';");
        $this->addSql("UPDATE `customers` SET `city_id` = (SELECT `id` FROM `customer_city` WHERE `kladr_id` = '4400000300000') WHERE `city_name` = 'кострома';");
        $this->addSql("UPDATE `customers` SET `city_id` = (SELECT `id` FROM `customer_city` WHERE `kladr_id` = '5000004900000') WHERE `city_name` = 'красногорск';");
        $this->addSql("UPDATE `customers` SET `city_id` = (SELECT `id` FROM `customer_city` WHERE `kladr_id` = '2300000100000') WHERE `city_name` = 'краснодар';");
        $this->addSql("UPDATE `customers` SET `city_id` = (SELECT `id` FROM `customer_city` WHERE `kladr_id` = '5000001100000') WHERE `city_name` = 'краснознаменск';");
        $this->addSql("UPDATE `customers` SET `city_id` = (SELECT `id` FROM `customer_city` WHERE `kladr_id` = '6600001000000') WHERE `city_name` = 'краснотурьинск';");
        $this->addSql("UPDATE `customers` SET `city_id` = (SELECT `id` FROM `customer_city` WHERE `kladr_id` = '9100000000000') WHERE `city_name` = 'крым';");
        $this->addSql("UPDATE `customers` SET `city_id` = (SELECT `id` FROM `customer_city` WHERE `kladr_id` = '2301800100000') WHERE `city_name` = 'крымск';");
        $this->addSql("UPDATE `customers` SET `city_id` = (SELECT `id` FROM `customer_city` WHERE `kladr_id` = '5202700100000') WHERE `city_name` = 'кстово';");
        $this->addSql("UPDATE `customers` SET `city_id` = (SELECT `id` FROM `customer_city` WHERE `kladr_id` = '5002200400000') WHERE `city_name` = 'кубинка';");
        $this->addSql("UPDATE `customers` SET `city_id` = (SELECT `id` FROM `customer_city` WHERE `kladr_id` = '4700511600000') WHERE `city_name` = 'кудрово';");
        $this->addSql("UPDATE `customers` SET `city_id` = (SELECT `id` FROM `customer_city` WHERE `kladr_id` = '5900001400000') WHERE `city_name` = 'кудымкар';");
        $this->addSql("UPDATE `customers` SET `city_id` = (SELECT `id` FROM `customer_city` WHERE `kladr_id` = '0200000700000') WHERE `city_name` = 'кумертау';");
        $this->addSql("UPDATE `customers` SET `city_id` = (SELECT `id` FROM `customer_city` WHERE `kladr_id` = '5900000900000') WHERE `city_name` = 'кунгур';");
        $this->addSql("UPDATE `customers` SET `city_id` = (SELECT `id` FROM `customer_city` WHERE `kladr_id` = '4500000100000') WHERE `city_name` = 'курган';");
        $this->addSql("UPDATE `customers` SET `city_id` = (SELECT `id` FROM `customer_city` WHERE `kladr_id` = '3300500200000') WHERE `city_name` = 'курлово';");
        $this->addSql("UPDATE `customers` SET `city_id` = (SELECT `id` FROM `customer_city` WHERE `kladr_id` = '4600000100000') WHERE `city_name` = 'курск';");
        $this->addSql("UPDATE `customers` SET `city_id` = (SELECT `id` FROM `customer_city` WHERE `kladr_id` = '0900900000900') WHERE `city_name` = 'кчр, хабезский р-н, а,кош-хабль';");
        $this->addSql("UPDATE `customers` SET `city_id` = (SELECT `id` FROM `customer_city` WHERE `kladr_id` = '1700000100000') WHERE `city_name` = 'кызыл';");
        $this->addSql("UPDATE `customers` SET `city_id` = (SELECT `id` FROM `customer_city` WHERE `kladr_id` = '2302100100000') WHERE `city_name` = 'лабинск';");
        $this->addSql("UPDATE `customers` SET `city_id` = (SELECT `id` FROM `customer_city` WHERE `kladr_id` = '8600000300000') WHERE `city_name` = 'лангепас';");
        $this->addSql("UPDATE `customers` SET `city_id` = (SELECT `id` FROM `customer_city` WHERE `kladr_id` = '2500001200000') WHERE `city_name` = 'лесозаводск';");
        $this->addSql("UPDATE `customers` SET `city_id` = (SELECT `id` FROM `customer_city` WHERE `kladr_id` = '3601500100000') WHERE `city_name` = 'лиски';");
        $this->addSql("UPDATE `customers` SET `city_id` = (SELECT `id` FROM `customer_city` WHERE `kladr_id` = '5000001200000') WHERE `city_name` = 'лобня';");
        $this->addSql("UPDATE `customers` SET `city_id` = (SELECT `id` FROM `customer_city` WHERE `kladr_id` = '7800000600000') WHERE `city_name` = 'ломоносов';");
        $this->addSql("UPDATE `customers` SET `city_id` = (SELECT `id` FROM `customer_city` WHERE `kladr_id` = '4301700100000') WHERE `city_name` = 'луза';");
        $this->addSql("UPDATE `customers` SET `city_id` = (SELECT `id` FROM `customer_city` WHERE `kladr_id` = '5000001300000') WHERE `city_name` = 'лыткарино';");
        $this->addSql("UPDATE `customers` SET `city_id` = (SELECT `id` FROM `customer_city` WHERE `kladr_id` = '5000005000000') WHERE `city_name` = 'люберцы';");
        $this->addSql("UPDATE `customers` SET `city_id` = (SELECT `id` FROM `customer_city` WHERE `kladr_id` = '0202800004700') WHERE `city_name` = 'магинск';");
        $this->addSql("UPDATE `customers` SET `city_id` = (SELECT `id` FROM `customer_city` WHERE `kladr_id` = '7400000900000') WHERE `city_name` = 'магнитогорск';");
        $this->addSql("UPDATE `customers` SET `city_id` = (SELECT `id` FROM `customer_city` WHERE `kladr_id` = '4401000100000') WHERE `city_name` = 'мантурово';");
        $this->addSql("UPDATE `customers` SET `city_id` = (SELECT `id` FROM `customer_city` WHERE `kladr_id` = '0500000100000') WHERE `city_name` = 'махачкала';");
        $this->addSql("UPDATE `customers` SET `city_id` = (SELECT `id` FROM `customer_city` WHERE `kladr_id` = '8600400000100') WHERE `city_name` = 'междуреченский';");
        $this->addSql("UPDATE `customers` SET `city_id` = (SELECT `id` FROM `customer_city` WHERE `kladr_id` = '0203500100000') WHERE `city_name` = 'мелеуз';");
        $this->addSql("UPDATE `customers` SET `city_id` = (SELECT `id` FROM `customer_city` WHERE `kladr_id` = '4001700100000') WHERE `city_name` = 'мещовск';");
        $this->addSql("UPDATE `customers` SET `city_id` = (SELECT `id` FROM `customer_city` WHERE `kladr_id` = '7400001000000') WHERE `city_name` = 'миасс';");
        $this->addSql("UPDATE `customers` SET `city_id` = (SELECT `id` FROM `customer_city` WHERE `kladr_id` = '2400001700000') WHERE `city_name` = 'минусинск';");
        $this->addSql("UPDATE `customers` SET `city_id` = (SELECT `id` FROM `customer_city` WHERE `kladr_id` = '2900000200000') WHERE `city_name` = 'мирный';");
        $this->addSql("UPDATE `customers` SET `city_id` = (SELECT `id` FROM `customer_city` WHERE `kladr_id` = '6800000300000') WHERE `city_name` = 'моршанск';");
        $this->addSql("UPDATE `customers` SET `city_id` = (SELECT `id` FROM `customer_city` WHERE `kladr_id` = '5100000100000') WHERE `city_name` = 'мурманск';");
        $this->addSql("UPDATE `customers` SET `city_id` = (SELECT `id` FROM `customer_city` WHERE `kladr_id` = '5200000100000') WHERE `city_name` = 'н.новгород';");
        $this->addSql("UPDATE `customers` SET `city_id` = (SELECT `id` FROM `customer_city` WHERE `kladr_id` = '5200000100000') WHERE `city_name` = 'нижний новгород';");
        $this->addSql("UPDATE `customers` SET `city_id` = (SELECT `id` FROM `customer_city` WHERE `kladr_id` = '5200000100000') WHERE `city_name` = 'нижний-новгород';");
        $this->addSql("UPDATE `customers` SET `city_id` = (SELECT `id` FROM `customer_city` WHERE `kladr_id` = '1600000200000') WHERE `city_name` = 'наб.челны';");
        $this->addSql("UPDATE `customers` SET `city_id` = (SELECT `id` FROM `customer_city` WHERE `kladr_id` = '1600000200000') WHERE `city_name` = 'набережные челны';");
        $this->addSql("UPDATE `customers` SET `city_id` = (SELECT `id` FROM `customer_city` WHERE `kladr_id` = '1600000200000') WHERE `city_name` = 'набережные челны, рт';");
        $this->addSql("UPDATE `customers` SET `city_id` = (SELECT `id` FROM `customer_city` WHERE `kladr_id` = '2400001800000') WHERE `city_name` = 'назарово';");
        $this->addSql("UPDATE `customers` SET `city_id` = (SELECT `id` FROM `customer_city` WHERE `kladr_id` = '0700000100000') WHERE `city_name` = 'нальчик';");
        $this->addSql("UPDATE `customers` SET `city_id` = (SELECT `id` FROM `customer_city` WHERE `kladr_id` = '2500000400000') WHERE `city_name` = 'находка';");
        $this->addSql("UPDATE `customers` SET `city_id` = (SELECT `id` FROM `customer_city` WHERE `kladr_id` = '4401300100000') WHERE `city_name` = 'нерехта';");
        $this->addSql("UPDATE `customers` SET `city_id` = (SELECT `id` FROM `customer_city` WHERE `kladr_id` = '0200000300000') WHERE `city_name` = 'нефтекамск';");
        $this->addSql("UPDATE `customers` SET `city_id` = (SELECT `id` FROM `customer_city` WHERE `kladr_id` = '0200000300000') WHERE `city_name` = 'нефтекамск рб';");
        $this->addSql("UPDATE `customers` SET `city_id` = (SELECT `id` FROM `customer_city` WHERE `kladr_id` = '8600001400000') WHERE `city_name` = 'нефтеюганск';");
        $this->addSql("UPDATE `customers` SET `city_id` = (SELECT `id` FROM `customer_city` WHERE `kladr_id` = '1603100100000') WHERE `city_name` = 'нижнекамск';");
        $this->addSql("UPDATE `customers` SET `city_id` = (SELECT `id` FROM `customer_city` WHERE `kladr_id` = '6600002300000') WHERE `city_name` = 'нижний тагил';");
        $this->addSql("UPDATE `customers` SET `city_id` = (SELECT `id` FROM `customer_city` WHERE `kladr_id` = '6600002300000') WHERE `city_name` = 'нижний тагил свердловской области';");
        $this->addSql("UPDATE `customers` SET `city_id` = (SELECT `id` FROM `customer_city` WHERE `kladr_id` = '2200000800000') WHERE `city_name` = 'новоалтайск';");
        $this->addSql("UPDATE `customers` SET `city_id` = (SELECT `id` FROM `customer_city` WHERE `kladr_id` = '3600000300000') WHERE `city_name` = 'нововоронеж';");
        $this->addSql("UPDATE `customers` SET `city_id` = (SELECT `id` FROM `customer_city` WHERE `kladr_id` = '6300000300000') WHERE `city_name` = 'новокуйбышевск';");
        $this->addSql("UPDATE `customers` SET `city_id` = (SELECT `id` FROM `customer_city` WHERE `kladr_id` = '7101700100000') WHERE `city_name` = 'новомосковск';");
        $this->addSql("UPDATE `customers` SET `city_id` = (SELECT `id` FROM `customer_city` WHERE `kladr_id` = '2300000600000') WHERE `city_name` = 'новороссийск';");
        $this->addSql("UPDATE `customers` SET `city_id` = (SELECT `id` FROM `customer_city` WHERE `kladr_id` = '6600001500000') WHERE `city_name` = 'новоуральск';");
        $this->addSql("UPDATE `customers` SET `city_id` = (SELECT `id` FROM `customer_city` WHERE `kladr_id` = '6100000900000') WHERE `city_name` = 'новочеркасск';");
        $this->addSql("UPDATE `customers` SET `city_id` = (SELECT `id` FROM `customer_city` WHERE `kladr_id` = '6100000900000') WHERE `city_name` = 'рост.обл новочеркасск';");
        $this->addSql("UPDATE `customers` SET `city_id` = (SELECT `id` FROM `customer_city` WHERE `kladr_id` = '8900000600000') WHERE `city_name` = 'новый уренгой';");
        $this->addSql("UPDATE `customers` SET `city_id` = (SELECT `id` FROM `customer_city` WHERE `kladr_id` = '2400000900000') WHERE `city_name` = 'норильск';");
        $this->addSql("UPDATE `customers` SET `city_id` = (SELECT `id` FROM `customer_city` WHERE `kladr_id` = '8900000700000') WHERE `city_name` = 'ноябрьск';");
        $this->addSql("UPDATE `customers` SET `city_id` = (SELECT `id` FROM `customer_city` WHERE `kladr_id` = '8600000500000') WHERE `city_name` = 'нягань';");
        $this->addSql("UPDATE `customers` SET `city_id` = (SELECT `id` FROM `customer_city` WHERE `kladr_id` = '8600000500000') WHERE `city_name` = 'нянань';");
        $this->addSql("UPDATE `customers` SET `city_id` = (SELECT `id` FROM `customer_city` WHERE `kladr_id` = '4000000200000') WHERE `city_name` = 'обнинск';");
        $this->addSql("UPDATE `customers` SET `city_id` = (SELECT `id` FROM `customer_city` WHERE `kladr_id` = '5002200100000') WHERE `city_name` = 'одинцово';");
        $this->addSql("UPDATE `customers` SET `city_id` = (SELECT `id` FROM `customer_city` WHERE `kladr_id` = '7400001100000') WHERE `city_name` = 'озерск';");
        $this->addSql("UPDATE `customers` SET `city_id` = (SELECT `id` FROM `customer_city` WHERE `kladr_id` = '0200000400000') WHERE `city_name` = 'октябрьский';");
        $this->addSql("UPDATE `customers` SET `city_id` = (SELECT `id` FROM `customer_city` WHERE `kladr_id` = '5500000100000') WHERE `city_name` = 'омск';");
        $this->addSql("UPDATE `customers` SET `city_id` = (SELECT `id` FROM `customer_city` WHERE `kladr_id` = '5500000000000') WHERE `city_name` = 'омская область';");
        $this->addSql("UPDATE `customers` SET `city_id` = (SELECT `id` FROM `customer_city` WHERE `kladr_id` = '5600000100000') WHERE `city_name` = 'оренбург';");
        $this->addSql("UPDATE `customers` SET `city_id` = (SELECT `id` FROM `customer_city` WHERE `kladr_id` = '5000002600000') WHERE `city_name` = 'орехово-зуево';");
        $this->addSql("UPDATE `customers` SET `city_id` = (SELECT `id` FROM `customer_city` WHERE `kladr_id` = '5601200000600') WHERE `city_name` = 'п. боровский';");
        $this->addSql("UPDATE `customers` SET `city_id` = (SELECT `id` FROM `customer_city` WHERE `kladr_id` = '8600600001300') WHERE `city_name` = 'п. излучинск нижневартовский район';");
        $this->addSql("UPDATE `customers` SET `city_id` = (SELECT `id` FROM `customer_city` WHERE `kladr_id` = '6101400000100') WHERE `city_name` = 'п.зимовники';");
        $this->addSql("UPDATE `customers` SET `city_id` = (SELECT `id` FROM `customer_city` WHERE `kladr_id` = '5203200100000') WHERE `city_name` = 'павлово, нижегородская область';");
        $this->addSql("UPDATE `customers` SET `city_id` = (SELECT `id` FROM `customer_city` WHERE `kladr_id` = '3602100100000') WHERE `city_name` = 'павловск';");
        $this->addSql("UPDATE `customers` SET `city_id` = (SELECT `id` FROM `customer_city` WHERE `kladr_id` = '7800000700000') WHERE `city_name` = 'павловск спб';");
        $this->addSql("UPDATE `customers` SET `city_id` = (SELECT `id` FROM `customer_city` WHERE `kladr_id` = '5000400000800') WHERE `city_name` = 'пгт белоозерский';");
        $this->addSql("UPDATE `customers` SET `city_id` = (SELECT `id` FROM `customer_city` WHERE `kladr_id` = '6902000000100') WHERE `city_name` = 'пгт максатиха. тверская обл';");
        $this->addSql("UPDATE `customers` SET `city_id` = (SELECT `id` FROM `customer_city` WHERE `kladr_id` = '4201100100000') WHERE `city_name` = 'пгт промышленная';");
        $this->addSql("UPDATE `customers` SET `city_id` = (SELECT `id` FROM `customer_city` WHERE `kladr_id` = '8600900000400') WHERE `city_name` = 'пгт. белый яр';");
        $this->addSql("UPDATE `customers` SET `city_id` = (SELECT `id` FROM `customer_city` WHERE `kladr_id` = '5800000100000') WHERE `city_name` = 'пенза';");
        $this->addSql("UPDATE `customers` SET `city_id` = (SELECT `id` FROM `customer_city` WHERE `kladr_id` = '5800000000000') WHERE `city_name` = 'пензенская обл.';");
        $this->addSql("UPDATE `customers` SET `city_id` = (SELECT `id` FROM `customer_city` WHERE `kladr_id` = '7600000200000') WHERE `city_name` = 'переславль-залесский';");
        $this->addSql("UPDATE `customers` SET `city_id` = (SELECT `id` FROM `customer_city` WHERE `kladr_id` = '5900000100000') WHERE `city_name` = 'пермь';");
        $this->addSql("UPDATE `customers` SET `city_id` = (SELECT `id` FROM `customer_city` WHERE `kladr_id` = '1000000100000') WHERE `city_name` = 'петрозаводск';");
        $this->addSql("UPDATE `customers` SET `city_id` = (SELECT `id` FROM `customer_city` WHERE `kladr_id` = '5100001000000') WHERE `city_name` = 'полярный';");
        $this->addSql("UPDATE `customers` SET `city_id` = (SELECT `id` FROM `customer_city` WHERE `kladr_id` = '7200100001200') WHERE `city_name` = 'пос боровский тюменский район тюменская область';");
        $this->addSql("UPDATE `customers` SET `city_id` = (SELECT `id` FROM `customer_city` WHERE `kladr_id` = '5100000000400') WHERE `city_name` = 'пос. видяево, мурманская область';");
        $this->addSql("UPDATE `customers` SET `city_id` = (SELECT `id` FROM `customer_city` WHERE `kladr_id` = '5000000000800') WHERE `city_name` = 'пос. власиха';");
        $this->addSql("UPDATE `customers` SET `city_id` = (SELECT `id` FROM `customer_city` WHERE `kladr_id` = '6600000001000') WHERE `city_name` = 'пос. рефтинский';");
        $this->addSql("UPDATE `customers` SET `city_id` = (SELECT `id` FROM `customer_city` WHERE `kladr_id` = '2502200000100') WHERE `city_name` = 'приморский край с.хороль';");
        $this->addSql("UPDATE `customers` SET `city_id` = (SELECT `id` FROM `customer_city` WHERE `kladr_id` = '6000000100000') WHERE `city_name` = 'псков';");
        $this->addSql("UPDATE `customers` SET `city_id` = (SELECT `id` FROM `customer_city` WHERE `kladr_id` = '5002700100000') WHERE `city_name` = 'пушкино';");
        $this->addSql("UPDATE `customers` SET `city_id` = (SELECT `id` FROM `customer_city` WHERE `kladr_id` = '3400500000100') WHERE `city_name` = 'р.п.даниловка';");
        $this->addSql("UPDATE `customers` SET `city_id` = (SELECT `id` FROM `customer_city` WHERE `kladr_id` = '6201600000100') WHERE `city_name` = 'р.п.сапожок';");
        $this->addSql("UPDATE `customers` SET `city_id` = (SELECT `id` FROM `customer_city` WHERE `kladr_id` = '5002800100000') WHERE `city_name` = 'раменское';");
        $this->addSql("UPDATE `customers` SET `city_id` = (SELECT `id` FROM `customer_city` WHERE `kladr_id` = '6602100100000') WHERE `city_name` = 'реж';");
        $this->addSql("UPDATE `customers` SET `city_id` = (SELECT `id` FROM `customer_city` WHERE `kladr_id` = '5000001600000') WHERE `city_name` = 'реутов';");
        $this->addSql("UPDATE `customers` SET `city_id` = (SELECT `id` FROM `customer_city` WHERE `kladr_id` = '3602800100000') WHERE `city_name` = 'россошь';");
        $this->addSql("UPDATE `customers` SET `city_id` = (SELECT `id` FROM `customer_city` WHERE `kladr_id` = '6100500100000') WHERE `city_name` = 'рост. белая калитва';");
        $this->addSql("UPDATE `customers` SET `city_id` = (SELECT `id` FROM `customer_city` WHERE `kladr_id` = '6102200000100') WHERE `city_name` = 'рост.обл м.-курган';");
        $this->addSql("UPDATE `customers` SET `city_id` = (SELECT `id` FROM `customer_city` WHERE `kladr_id` = '6100001200000') WHERE `city_name` = 'рост.обл шахты';");
        $this->addSql("UPDATE `customers` SET `city_id` = (SELECT `id` FROM `customer_city` WHERE `kladr_id` = '6100001200000') WHERE `city_name` = 'рост.обл. шахты';");
        $this->addSql("UPDATE `customers` SET `city_id` = (SELECT `id` FROM `customer_city` WHERE `kladr_id` = '6100000100000') WHERE `city_name` = 'росто-на-дону';");
        $this->addSql("UPDATE `customers` SET `city_id` = (SELECT `id` FROM `customer_city` WHERE `kladr_id` = '6100000100000') WHERE `city_name` = 'ростов на дону';");
        $this->addSql("UPDATE `customers` SET `city_id` = (SELECT `id` FROM `customer_city` WHERE `kladr_id` = '6100000100000') WHERE `city_name` = 'ростов-на-дону';");
        $this->addSql("UPDATE `customers` SET `city_id` = (SELECT `id` FROM `customer_city` WHERE `kladr_id` = '7601400100000') WHERE `city_name` = 'ростов великий';");
        $this->addSql("UPDATE `customers` SET `city_id` = (SELECT `id` FROM `customer_city` WHERE `kladr_id` = '2200000900000') WHERE `city_name` = 'рубцовск';");
        $this->addSql("UPDATE `customers` SET `city_id` = (SELECT `id` FROM `customer_city` WHERE `kladr_id` = '1300000300000') WHERE `city_name` = 'рузаевка';");
        $this->addSql("UPDATE `customers` SET `city_id` = (SELECT `id` FROM `customer_city` WHERE `kladr_id` = '6201500100000') WHERE `city_name` = 'ряжск';");
        $this->addSql("UPDATE `customers` SET `city_id` = (SELECT `id` FROM `customer_city` WHERE `kladr_id` = '6200600024000') WHERE `city_name` = 'рязанская область, рп.тума';");
        $this->addSql("UPDATE `customers` SET `city_id` = (SELECT `id` FROM `customer_city` WHERE `kladr_id` = '6200600024000') WHERE `city_name` = 'тума';");
        $this->addSql("UPDATE `customers` SET `city_id` = (SELECT `id` FROM `customer_city` WHERE `kladr_id` = '0204400011300') WHERE `city_name` = 'с. серафимовский';");
        $this->addSql("UPDATE `customers` SET `city_id` = (SELECT `id` FROM `customer_city` WHERE `kladr_id` = '0204400011300') WHERE `city_name` = 'с.серафимовский';");
        $this->addSql("UPDATE `customers` SET `city_id` = (SELECT `id` FROM `customer_city` WHERE `kladr_id` = '6102600000100') WHERE `city_name` = 'с. чалтырь';");
        $this->addSql("UPDATE `customers` SET `city_id` = (SELECT `id` FROM `customer_city` WHERE `kladr_id` = '0204200002700') WHERE `city_name` = 'с.верхние услы';");
        $this->addSql("UPDATE `customers` SET `city_id` = (SELECT `id` FROM `customer_city` WHERE `kladr_id` = '2200900000100') WHERE `city_name` = 'с.волчиха';");
        $this->addSql("UPDATE `customers` SET `city_id` = (SELECT `id` FROM `customer_city` WHERE `kladr_id` = '7201800000100') WHERE `city_name` = 'с.уват';");
        $this->addSql("UPDATE `customers` SET `city_id` = (SELECT `id` FROM `customer_city` WHERE `kladr_id` = '8900000100000') WHERE `city_name` = 'салехард';");
        $this->addSql("UPDATE `customers` SET `city_id` = (SELECT `id` FROM `customer_city` WHERE `kladr_id` = '6300000100000') WHERE `city_name` = 'самаоа';");
        $this->addSql("UPDATE `customers` SET `city_id` = (SELECT `id` FROM `customer_city` WHERE `kladr_id` = '6300000100000') WHERE `city_name` = 'самара';");
        $this->addSql("UPDATE `customers` SET `city_id` = (SELECT `id` FROM `customer_city` WHERE `kladr_id` = '6400000100000') WHERE `city_name` = 'саратов';");
        $this->addSql("UPDATE `customers` SET `city_id` = (SELECT `id` FROM `customer_city` WHERE `kladr_id` = '6400000000000') WHERE `city_name` = 'саратовская область';");
        $this->addSql("UPDATE `customers` SET `city_id` = (SELECT `id` FROM `customer_city` WHERE `kladr_id` = '1900000200000') WHERE `city_name` = 'саяногорск';");
        $this->addSql("UPDATE `customers` SET `city_id` = (SELECT `id` FROM `customer_city` WHERE `kladr_id` = '6600004100000') WHERE `city_name` = 'свердловская область город дегтярск';");
        $this->addSql("UPDATE `customers` SET `city_id` = (SELECT `id` FROM `customer_city` WHERE `kladr_id` = '2900000400000') WHERE `city_name` = 'северодвинск';");
        $this->addSql("UPDATE `customers` SET `city_id` = (SELECT `id` FROM `customer_city` WHERE `kladr_id` = '5100001100000') WHERE `city_name` = 'североморск';");
        $this->addSql("UPDATE `customers` SET `city_id` = (SELECT `id` FROM `customer_city` WHERE `kladr_id` = '5400600000100') WHERE `city_name` = 'село довольное';");
        $this->addSql("UPDATE `customers` SET `city_id` = (SELECT `id` FROM `customer_city` WHERE `kladr_id` = '8600900002800') WHERE `city_name` = 'село угут, сургутского района, хмао-югра';");
        $this->addSql("UPDATE `customers` SET `city_id` = (SELECT `id` FROM `customer_city` WHERE `kladr_id` = '6600003400000') WHERE `city_name` = 'серов';");
        $this->addSql("UPDATE `customers` SET `city_id` = (SELECT `id` FROM `customer_city` WHERE `kladr_id` = '5000002800000') WHERE `city_name` = 'серпухов';");
        $this->addSql("UPDATE `customers` SET `city_id` = (SELECT `id` FROM `customer_city` WHERE `kladr_id` = '6200000300000') WHERE `city_name` = 'скопин';");
        $this->addSql("UPDATE `customers` SET `city_id` = (SELECT `id` FROM `customer_city` WHERE `kladr_id` = '2200001000000') WHERE `city_name` = 'славгород';");
        $this->addSql("UPDATE `customers` SET `city_id` = (SELECT `id` FROM `customer_city` WHERE `kladr_id` = '4303100100000') WHERE `city_name` = 'слободской';");
        $this->addSql("UPDATE `customers` SET `city_id` = (SELECT `id` FROM `customer_city` WHERE `kladr_id` = '3801800100000') WHERE `city_name` = 'слюдянка';");
        $this->addSql("UPDATE `customers` SET `city_id` = (SELECT `id` FROM `customer_city` WHERE `kladr_id` = '7400001300000') WHERE `city_name` = 'снежинск';");
        $this->addSql("UPDATE `customers` SET `city_id` = (SELECT `id` FROM `customer_city` WHERE `kladr_id` = '5900001100000') WHERE `city_name` = 'соликамск';");
        $this->addSql("UPDATE `customers` SET `city_id` = (SELECT `id` FROM `customer_city` WHERE `kladr_id` = '2300000700000') WHERE `city_name` = 'сочи';");
        $this->addSql("UPDATE `customers` SET `city_id` = (SELECT `id` FROM `customer_city` WHERE `kladr_id` = '2500001000000') WHERE `city_name` = 'спасск-дальний';");
        $this->addSql("UPDATE `customers` SET `city_id` = (SELECT `id` FROM `customer_city` WHERE `kladr_id` = '6202000100000') WHERE `city_name` = 'спасск-рязанский';");
        $this->addSql("UPDATE `customers` SET `city_id` = (SELECT `id` FROM `customer_city` WHERE `kladr_id` = '6600003800000') WHERE `city_name` = 'среднеуральск';");
        $this->addSql("UPDATE `customers` SET `city_id` = (SELECT `id` FROM `customer_city` WHERE `kladr_id` = '6101100000100') WHERE `city_name` = 'ст. егорлыкская';");
        $this->addSql("UPDATE `customers` SET `city_id` = (SELECT `id` FROM `customer_city` WHERE `kladr_id` = '6101100000100') WHERE `city_name` = 'ст.егорлыкская ростовской области';");
        $this->addSql("UPDATE `customers` SET `city_id` = (SELECT `id` FROM `customer_city` WHERE `kladr_id` = '2600000100000') WHERE `city_name` = 'ставрополь';");
        $this->addSql("UPDATE `customers` SET `city_id` = (SELECT `id` FROM `customer_city` WHERE `kladr_id` = '3100000200000') WHERE `city_name` = 'старый оскол';");
        $this->addSql("UPDATE `customers` SET `city_id` = (SELECT `id` FROM `customer_city` WHERE `kladr_id` = '0200001400000') WHERE `city_name` = 'стерлитамак';");
        $this->addSql("UPDATE `customers` SET `city_id` = (SELECT `id` FROM `customer_city` WHERE `kladr_id` = '0200001400000') WHERE `city_name` = 'стерлитамак, башкортостан (башкирия), россия';");
        $this->addSql("UPDATE `customers` SET `city_id` = (SELECT `id` FROM `customer_city` WHERE `kladr_id` = '8600900000000') WHERE `city_name` = 'сургутский район';");
        $this->addSql("UPDATE `customers` SET `city_id` = (SELECT `id` FROM `customer_city` WHERE `kladr_id` = '6602400100000') WHERE `city_name` = 'сухой лог';");
        $this->addSql("UPDATE `customers` SET `city_id` = (SELECT `id` FROM `customer_city` WHERE `kladr_id` = '1100000100000') WHERE `city_name` = 'сыктывкар';");
        $this->addSql("UPDATE `customers` SET `city_id` = (SELECT `id` FROM `customer_city` WHERE `kladr_id` = '6100001100000') WHERE `city_name` = 'таганрог';");
        $this->addSql("UPDATE `customers` SET `city_id` = (SELECT `id` FROM `customer_city` WHERE `kladr_id` = '6800000400000') WHERE `city_name` = 'тамбов';");
        $this->addSql("UPDATE `customers` SET `city_id` = (SELECT `id` FROM `customer_city` WHERE `kladr_id` = '3701700100000') WHERE `city_name` = 'тейково';");
        $this->addSql("UPDATE `customers` SET `city_id` = (SELECT `id` FROM `customer_city` WHERE `kladr_id` = '4701700100000') WHERE `city_name` = 'тихаин';");
        $this->addSql("UPDATE `customers` SET `city_id` = (SELECT `id` FROM `customer_city` WHERE `kladr_id` = '7200000200000') WHERE `city_name` = 'тобольск';");
        $this->addSql("UPDATE `customers` SET `city_id` = (SELECT `id` FROM `customer_city` WHERE `kladr_id` = '6300000700000') WHERE `city_name` = 'тольятти';");
        $this->addSql("UPDATE `customers` SET `city_id` = (SELECT `id` FROM `customer_city` WHERE `kladr_id` = '7000000100000') WHERE `city_name` = 'томск';");
        $this->addSql("UPDATE `customers` SET `city_id` = (SELECT `id` FROM `customer_city` WHERE `kladr_id` = '6900000200000') WHERE `city_name` = 'торжок';");
        $this->addSql("UPDATE `customers` SET `city_id` = (SELECT `id` FROM `customer_city` WHERE `kladr_id` = '4701800000000') WHERE `city_name` = 'тосненск';");
        $this->addSql("UPDATE `customers` SET `city_id` = (SELECT `id` FROM `customer_city` WHERE `kladr_id` = '2303600100000') WHERE `city_name` = 'туапсе';");
        $this->addSql("UPDATE `customers` SET `city_id` = (SELECT `id` FROM `customer_city` WHERE `kladr_id` = '2303600100000') WHERE `city_name` = 'туапсе улица фрунзе дом 29 кв 44';");
        $this->addSql("UPDATE `customers` SET `city_id` = (SELECT `id` FROM `customer_city` WHERE `kladr_id` = '0400500000100') WHERE `city_name` = 'турочак';");
        $this->addSql("UPDATE `customers` SET `city_id` = (SELECT `id` FROM `customer_city` WHERE `kladr_id` = '7601600100000') WHERE `city_name` = 'тутаев ярославская область';");
        $this->addSql("UPDATE `customers` SET `city_id` = (SELECT `id` FROM `customer_city` WHERE `kladr_id` = '7200000100000') WHERE `city_name` = 'тюмен';");
        $this->addSql("UPDATE `customers` SET `city_id` = (SELECT `id` FROM `customer_city` WHERE `kladr_id` = '7200000100000') WHERE `city_name` = 'тюмень';");
        $this->addSql("UPDATE `customers` SET `city_id` = (SELECT `id` FROM `customer_city` WHERE `kladr_id` = '7102200100000') WHERE `city_name` = 'узловая';");
        $this->addSql("UPDATE `customers` SET `city_id` = (SELECT `id` FROM `customer_city` WHERE `kladr_id` = '2202000002700') WHERE `city_name` = 'украинский';");
        $this->addSql("UPDATE `customers` SET `city_id` = (SELECT `id` FROM `customer_city` WHERE `kladr_id` = '0300000100000') WHERE `city_name` = 'улан-удэ';");
        $this->addSql("UPDATE `customers` SET `city_id` = (SELECT `id` FROM `customer_city` WHERE `kladr_id` = '7300000100000') WHERE `city_name` = 'ульяновск';");
        $this->addSql("UPDATE `customers` SET `city_id` = (SELECT `id` FROM `customer_city` WHERE `kladr_id` = '8600000900000') WHERE `city_name` = 'урай';");
        $this->addSql("UPDATE `customers` SET `city_id` = (SELECT `id` FROM `customer_city` WHERE `kladr_id` = '2500001100000') WHERE `city_name` = 'уссугийск';");
        $this->addSql("UPDATE `customers` SET `city_id` = (SELECT `id` FROM `customer_city` WHERE `kladr_id` = '2500001100000') WHERE `city_name` = 'уссурийск';");
        $this->addSql("UPDATE `customers` SET `city_id` = (SELECT `id` FROM `customer_city` WHERE `kladr_id` = '1100000800000') WHERE `city_name` = 'ухта';");
        $this->addSql("UPDATE `customers` SET `city_id` = (SELECT `id` FROM `customer_city` WHERE `kladr_id` = '2500000600000') WHERE `city_name` = 'фокино';");
        $this->addSql("UPDATE `customers` SET `city_id` = (SELECT `id` FROM `customer_city` WHERE `kladr_id` = '2700000100000') WHERE `city_name` = 'хабаровск';");
        $this->addSql("UPDATE `customers` SET `city_id` = (SELECT `id` FROM `customer_city` WHERE `kladr_id` = '2700000100000') WHERE `city_name` = 'хабаровск, хабаровский край';");
        $this->addSql("UPDATE `customers` SET `city_id` = (SELECT `id` FROM `customer_city` WHERE `kladr_id` = '8600000100000') WHERE `city_name` = 'ханты-мансийск';");
        $this->addSql("UPDATE `customers` SET `city_id` = (SELECT `id` FROM `customer_city` WHERE `kladr_id` = '5000003000000') WHERE `city_name` = 'химки';");
        $this->addSql("UPDATE `customers` SET `city_id` = (SELECT `id` FROM `customer_city` WHERE `kladr_id` = '6501600100000') WHERE `city_name` = 'холмск';");
        $this->addSql("UPDATE `customers` SET `city_id` = (SELECT `id` FROM `customer_city` WHERE `kladr_id` = '6300000600000') WHERE `city_name` = 'чапаевск';");
        $this->addSql("UPDATE `customers` SET `city_id` = (SELECT `id` FROM `customer_city` WHERE `kladr_id` = '2100000100000') WHERE `city_name` = 'чебоксары';");
        $this->addSql("UPDATE `customers` SET `city_id` = (SELECT `id` FROM `customer_city` WHERE `kladr_id` = '7400000100000') WHERE `city_name` = 'челябинск';");
        $this->addSql("UPDATE `customers` SET `city_id` = (SELECT `id` FROM `customer_city` WHERE `kladr_id` = '3500000200000') WHERE `city_name` = 'череповец';");
        $this->addSql("UPDATE `customers` SET `city_id` = (SELECT `id` FROM `customer_city` WHERE `kladr_id` = '0900000100000') WHERE `city_name` = 'черкесск';");
        $this->addSql("UPDATE `customers` SET `city_id` = (SELECT `id` FROM `customer_city` WHERE `kladr_id` = '3101900000100') WHERE `city_name` = 'чернянка';");
        $this->addSql("UPDATE `customers` SET `city_id` = (SELECT `id` FROM `customer_city` WHERE `kladr_id` = '7500000100000') WHERE `city_name` = 'чита';");
        $this->addSql("UPDATE `customers` SET `city_id` = (SELECT `id` FROM `customer_city` WHERE `kladr_id` = '7500000100000') WHERE `city_name` = 'чита, 672007';");
        $this->addSql("UPDATE `customers` SET `city_id` = (SELECT `id` FROM `customer_city` WHERE `kladr_id` = '2100400000100') WHERE `city_name` = 'чувашия батыревский район с. батырево';");
        $this->addSql("UPDATE `customers` SET `city_id` = (SELECT `id` FROM `customer_city` WHERE `kladr_id` = '5900001300000') WHERE `city_name` = 'чусовой';");
        $this->addSql("UPDATE `customers` SET `city_id` = (SELECT `id` FROM `customer_city` WHERE `kladr_id` = '4500000200000') WHERE `city_name` = 'шадринск';");
        $this->addSql("UPDATE `customers` SET `city_id` = (SELECT `id` FROM `customer_city` WHERE `kladr_id` = '5000004200000') WHERE `city_name` = 'шаховская';");
        $this->addSql("UPDATE `customers` SET `city_id` = (SELECT `id` FROM `customer_city` WHERE `kladr_id` = '6202400100000') WHERE `city_name` = 'шацк';");
        $this->addSql("UPDATE `customers` SET `city_id` = (SELECT `id` FROM `customer_city` WHERE `kladr_id` = '2206000000100') WHERE `city_name` = 'шелаболиха';");
        $this->addSql("UPDATE `customers` SET `city_id` = (SELECT `id` FROM `customer_city` WHERE `kladr_id` = '7102400100000') WHERE `city_name` = 'щекино,тульской области';");
        $this->addSql("UPDATE `customers` SET `city_id` = (SELECT `id` FROM `customer_city` WHERE `kladr_id` = '5004000100000') WHERE `city_name` = 'щелково';");
        $this->addSql("UPDATE `customers` SET `city_id` = (SELECT `id` FROM `customer_city` WHERE `kladr_id` = '5000002100000') WHERE `city_name` = 'электросталь';");
        $this->addSql("UPDATE `customers` SET `city_id` = (SELECT `id` FROM `customer_city` WHERE `kladr_id` = '6500000100000') WHERE `city_name` = 'южно-сахалинск';");
        $this->addSql("UPDATE `customers` SET `city_id` = (SELECT `id` FROM `customer_city` WHERE `kladr_id` = '7400001600000') WHERE `city_name` = 'южноуральск';");
        $this->addSql("UPDATE `customers` SET `city_id` = (SELECT `id` FROM `customer_city` WHERE `kladr_id` = '7200000500000') WHERE `city_name` = 'ялуторовск';");
        $this->addSql("UPDATE `customers` SET `city_id` = (SELECT `id` FROM `customer_city` WHERE `kladr_id` = '7200000500000') WHERE `city_name` = 'ялуторовск г,';");
        $this->addSql("UPDATE `customers` SET `city_id` = (SELECT `id` FROM `customer_city` WHERE `kladr_id` = '7600000100000') WHERE `city_name` = 'ярославль';");
        $this->addSql("UPDATE `customers` SET `city_id` = (SELECT `id` FROM `customer_city` WHERE `kladr_id` = '7600000100000') WHERE `city_name` = 'ярославль ярославская';");
        $this->addSql("UPDATE `customers` SET `city_id` = (SELECT `id` FROM `customer_city` WHERE `name` = 'Запорожье') WHERE `city_name` = 'zaporizhzhya';");
        $this->addSql("UPDATE `customers` SET `city_id` = (SELECT `id` FROM `customer_city` WHERE `name` = 'Алма-Ата') WHERE `city_name` = 'алматы';");
        $this->addSql("UPDATE `customers` SET `city_id` = (SELECT `id` FROM `customer_city` WHERE `name` = 'Алма-Ата') WHERE `city_name` = 'г.алматы';");
        $this->addSql("UPDATE `customers` SET `city_id` = (SELECT `id` FROM `customer_city` WHERE `name` = 'Астана') WHERE `city_name` = 'астана';");
        $this->addSql("UPDATE `customers` SET `city_id` = (SELECT `id` FROM `customer_city` WHERE `name` = 'Геттинген') WHERE `city_name` = 'гёттинген';");
        $this->addSql("UPDATE `customers` SET `city_id` = (SELECT `id` FROM `customer_city` WHERE `name` = 'Елгава') WHERE `city_name` = 'елгава (латвия)';");
        $this->addSql("UPDATE `customers` SET `city_id` = (SELECT `id` FROM `customer_city` WHERE `name` = 'Житомир') WHERE `city_name` = 'житомир';");
        $this->addSql("UPDATE `customers` SET `city_id` = (SELECT `id` FROM `customer_city` WHERE `name` = 'Киев') WHERE `city_name` = 'киев';");
        $this->addSql("UPDATE `customers` SET `city_id` = (SELECT `id` FROM `customer_city` WHERE `name` = 'Костанай') WHERE `city_name` = 'костанай';");
        $this->addSql("UPDATE `customers` SET `city_id` = (SELECT `id` FROM `customer_city` WHERE `name` = 'Минск') WHERE `city_name` = 'минск';");
        $this->addSql("UPDATE `customers` SET `city_id` = (SELECT `id` FROM `customer_city` WHERE `name` = 'Спитак') WHERE `city_name` = 'спитак';");
        $this->addSql("UPDATE `customers` SET `city_id` = (SELECT `id` FROM `customer_city` WHERE `name` = 'Стокгольм') WHERE `city_name` = 'стокгольм';");
        $this->addSql("UPDATE `customers` SET `city_id` = (SELECT `id` FROM `customer_city` WHERE `name` = 'Харьков') WHERE `city_name` = 'харьков';");
    }

    public function down(Schema $schema) : void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() !== 'mysql', 'Migration can only be executed safely on \'mysql\'.');
    }
}
