<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20190731103136 extends AbstractMigration
{
    public function getDescription() : string
    {
        return '';
    }

    public function up(Schema $schema) : void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() !== 'mysql', 'Migration can only be executed safely on \'mysql\'.');
    
        $this->addSql("INSERT INTO `customer_city` (`country`, `name`, `full_name`) VALUES ('Армения', 'Спитак', 'Спитак');");
        $this->addSql("INSERT INTO `customer_city` (`country`, `name`, `full_name`) VALUES ('Беларусь', 'Минск', 'Красноярский край, р-н Большемуртинский, Минск');");
        $this->addSql("INSERT INTO `customer_city` (`country`, `name`, `full_name`) VALUES ('Германия', 'Геттинген', 'Геттинген');");
        $this->addSql("INSERT INTO `customer_city` (`country`, `name`, `full_name`) VALUES ('Казахстан', 'Алма-Ата', 'Алма-Ата');");
        $this->addSql("INSERT INTO `customer_city` (`country`, `name`, `full_name`) VALUES ('Казахстан', 'Астана', 'Астана');");
        $this->addSql("INSERT INTO `customer_city` (`country`, `name`, `full_name`) VALUES ('Казахстан', 'Костанай', 'Костанайская обл, Костанай');");
        $this->addSql("INSERT INTO `customer_city` (`country`, `name`, `full_name`) VALUES ('Латвия', 'Елгава', 'Елгава');");
        $this->addSql("INSERT INTO `customer_city` (`country`, `name`, `full_name`) VALUES ('Украина', 'Житомир', 'Житомирская обл, Житомир');");
        $this->addSql("INSERT INTO `customer_city` (`country`, `name`, `full_name`) VALUES ('Украина', 'Запорожье', 'Запорожье');");
        $this->addSql("INSERT INTO `customer_city` (`country`, `name`, `full_name`) VALUES ('Украина', 'Киев', 'Киев');");
        $this->addSql("INSERT INTO `customer_city` (`country`, `name`, `full_name`) VALUES ('Украина', 'Харьков', 'Харьковская обл, Харьков');");
        $this->addSql("INSERT INTO `customer_city` (`country`, `name`, `full_name`) VALUES ('Швеция', 'Стокгольм', 'Стокгольм');");
        $this->addSql("INSERT INTO `customer_city` (`kladr_id`, `country`, `name`, `full_name`) VALUES ('0100000200000', 'Россия', 'Адыгейск', 'Адыгея Респ, Адыгейск');");
        $this->addSql("INSERT INTO `customer_city` (`kladr_id`, `country`, `name`, `full_name`) VALUES ('0200000100000', 'Россия', 'Уфа', 'Башкортостан Респ, Уфа');");
        $this->addSql("INSERT INTO `customer_city` (`kladr_id`, `country`, `name`, `full_name`) VALUES ('0200000300000', 'Россия', 'Нефтекамск', 'Башкортостан Респ, Нефтекамск');");
        $this->addSql("INSERT INTO `customer_city` (`kladr_id`, `country`, `name`, `full_name`) VALUES ('0200000400000', 'Россия', 'Октябрьский', 'Башкортостан Респ, Октябрьский');");
        $this->addSql("INSERT INTO `customer_city` (`kladr_id`, `country`, `name`, `full_name`) VALUES ('0200000700000', 'Россия', 'Кумертау', 'Башкортостан Респ, Кумертау');");
        $this->addSql("INSERT INTO `customer_city` (`kladr_id`, `country`, `name`, `full_name`) VALUES ('0200001400000', 'Россия', 'Стерлитамак', 'Башкортостан Респ, Стерлитамак');");
        $this->addSql("INSERT INTO `customer_city` (`kladr_id`, `country`, `name`, `full_name`) VALUES ('0201100100000', 'Россия', 'Белорецк', 'Башкортостан Респ, р-н Белорецкий, Белорецк');");
        $this->addSql("INSERT INTO `customer_city` (`kladr_id`, `country`, `name`, `full_name`) VALUES ('0201300100000', 'Россия', 'Бирск', 'Башкортостан Респ, р-н Бирский, Бирск');");
        $this->addSql("INSERT INTO `customer_city` (`kladr_id`, `country`, `name`, `full_name`) VALUES ('0201500100000', 'Россия', 'Благовещенск', 'Башкортостан Респ, р-н Благовещенский, Благовещенск');");
        $this->addSql("INSERT INTO `customer_city` (`kladr_id`, `country`, `name`, `full_name`) VALUES ('0202800004700', 'Россия', 'с Магинск', 'Башкортостан Респ, р-н Караидельский, с Магинск');");
        $this->addSql("INSERT INTO `customer_city` (`kladr_id`, `country`, `name`, `full_name`) VALUES ('0203500100000', 'Россия', 'Мелеуз', 'Башкортостан Респ, р-н Мелеузовский, Мелеуз');");
        $this->addSql("INSERT INTO `customer_city` (`kladr_id`, `country`, `name`, `full_name`) VALUES ('0204200002700', 'Россия', 'с Верхние Услы', 'Башкортостан Респ, р-н Стерлитамакский, с Верхние Услы');");
        $this->addSql("INSERT INTO `customer_city` (`kladr_id`, `country`, `name`, `full_name`) VALUES ('0204400011300', 'Россия', 'с Серафимовский', 'Башкортостан Респ, р-н Туймазинский, с Серафимовский');");
        $this->addSql("INSERT INTO `customer_city` (`kladr_id`, `country`, `name`, `full_name`) VALUES ('0300000100000', 'Россия', 'Улан-Удэ', 'Бурятия Респ, Улан-Удэ');");
        $this->addSql("INSERT INTO `customer_city` (`kladr_id`, `country`, `name`, `full_name`) VALUES ('0400000100000', 'Россия', 'Горно-Алтайск', 'Алтай Респ, Горно-Алтайск');");
        $this->addSql("INSERT INTO `customer_city` (`kladr_id`, `country`, `name`, `full_name`) VALUES ('0400500000100', 'Россия', 'с Турочак', 'Алтай Респ, р-н Турочакский, с Турочак');");
        $this->addSql("INSERT INTO `customer_city` (`kladr_id`, `country`, `name`, `full_name`) VALUES ('0500000100000', 'Россия', 'Махачкала', 'Дагестан Респ, Махачкала');");
        $this->addSql("INSERT INTO `customer_city` (`kladr_id`, `country`, `name`, `full_name`) VALUES ('0500000700000', 'Россия', 'Кизилюрт', 'Дагестан Респ, Кизилюрт');");
        $this->addSql("INSERT INTO `customer_city` (`kladr_id`, `country`, `name`, `full_name`) VALUES ('0500900000100', 'Россия', 'с Гергебиль', 'Дагестан Респ, р-н Гергебильский, с Гергебиль');");
        $this->addSql("INSERT INTO `customer_city` (`kladr_id`, `country`, `name`, `full_name`) VALUES ('0700000100000', 'Россия', 'Нальчик', 'Кабардино-Балкарская Респ, Нальчик');");
        $this->addSql("INSERT INTO `customer_city` (`kladr_id`, `country`, `name`, `full_name`) VALUES ('0900000100000', 'Россия', 'Черкесск', 'Карачаево-Черкесская Респ, Черкесск');");
        $this->addSql("INSERT INTO `customer_city` (`kladr_id`, `country`, `name`, `full_name`) VALUES ('0900900000900', 'Россия', 'аул Кош-Хабль', 'Карачаево-Черкесская Респ, р-н Хабезский, аул Кош-Хабль');");
        $this->addSql("INSERT INTO `customer_city` (`kladr_id`, `country`, `name`, `full_name`) VALUES ('1000000100000', 'Россия', 'Петрозаводск', 'Карелия Респ, Петрозаводск');");
        $this->addSql("INSERT INTO `customer_city` (`kladr_id`, `country`, `name`, `full_name`) VALUES ('1000400100000', 'Россия', 'Кемь', 'Карелия Респ, р-н Кемский, Кемь');");
        $this->addSql("INSERT INTO `customer_city` (`kladr_id`, `country`, `name`, `full_name`) VALUES ('1100000100000', 'Россия', 'Сыктывкар', 'Коми Респ, Сыктывкар');");
        $this->addSql("INSERT INTO `customer_city` (`kladr_id`, `country`, `name`, `full_name`) VALUES ('1100000800000', 'Россия', 'Ухта', 'Коми Респ, Ухта');");
        $this->addSql("INSERT INTO `customer_city` (`kladr_id`, `country`, `name`, `full_name`) VALUES ('1200000100000', 'Россия', 'Йошкар-Ола', 'Марий Эл Респ, Йошкар-Ола');");
        $this->addSql("INSERT INTO `customer_city` (`kladr_id`, `country`, `name`, `full_name`) VALUES ('1300000300000', 'Россия', 'Рузаевка', 'Мордовия Респ, Рузаевка');");
        $this->addSql("INSERT INTO `customer_city` (`kladr_id`, `country`, `name`, `full_name`) VALUES ('1500000100000', 'Россия', 'Владикавказ', 'Северная Осетия - Алания Респ, Владикавказ');");
        $this->addSql("INSERT INTO `customer_city` (`kladr_id`, `country`, `name`, `full_name`) VALUES ('1500400100000', 'Россия', 'Дигора', 'Северная Осетия - Алания Респ, р-н Дигорский, Дигора');");
        $this->addSql("INSERT INTO `customer_city` (`kladr_id`, `country`, `name`, `full_name`) VALUES ('1600000100000', 'Россия', 'Казань', 'Татарстан Респ, Казань');");
        $this->addSql("INSERT INTO `customer_city` (`kladr_id`, `country`, `name`, `full_name`) VALUES ('1600000200000', 'Россия', 'Набережные Челны', 'Татарстан Респ, Набережные Челны');");
        $this->addSql("INSERT INTO `customer_city` (`kladr_id`, `country`, `name`, `full_name`) VALUES ('1600800100000', 'Россия', 'Альметьевск', 'Татарстан Респ, р-н Альметьевский, Альметьевск');");
        $this->addSql("INSERT INTO `customer_city` (`kladr_id`, `country`, `name`, `full_name`) VALUES ('1601500100000', 'Россия', 'Буинск', 'Татарстан Респ, р-н Буинский, Буинск');");
        $this->addSql("INSERT INTO `customer_city` (`kladr_id`, `country`, `name`, `full_name`) VALUES ('1601900100000', 'Россия', 'Елабуга', 'Татарстан Респ, р-н Елабужский, Елабуга');");
        $this->addSql("INSERT INTO `customer_city` (`kladr_id`, `country`, `name`, `full_name`) VALUES ('1602300000100', 'Россия', 'пгт Камское Устье', 'Татарстан Респ, р-н Камско-Устьинский, пгт Камское Устье');");
        $this->addSql("INSERT INTO `customer_city` (`kladr_id`, `country`, `name`, `full_name`) VALUES ('1603100100000', 'Россия', 'Нижнекамск', 'Татарстан Респ, р-н Нижнекамский, Нижнекамск');");
        $this->addSql("INSERT INTO `customer_city` (`kladr_id`, `country`, `name`, `full_name`) VALUES ('1700000100000', 'Россия', 'Кызыл', 'Тыва Респ, Кызыл');");
        $this->addSql("INSERT INTO `customer_city` (`kladr_id`, `country`, `name`, `full_name`) VALUES ('1900000100000', 'Россия', 'Абакан', 'Хакасия Респ, Абакан');");
        $this->addSql("INSERT INTO `customer_city` (`kladr_id`, `country`, `name`, `full_name`) VALUES ('1900000200000', 'Россия', 'Саяногорск', 'Хакасия Респ, Саяногорск');");
        $this->addSql("INSERT INTO `customer_city` (`kladr_id`, `country`, `name`, `full_name`) VALUES ('2100000100000', 'Россия', 'Чебоксары', 'Чувашская Республика Чувашия, Чебоксары');");
        $this->addSql("INSERT INTO `customer_city` (`kladr_id`, `country`, `name`, `full_name`) VALUES ('2100400000100', 'Россия', 'с Батырево', 'Чувашская Республика Чувашия, р-н Батыревский, с Батырево');");
        $this->addSql("INSERT INTO `customer_city` (`kladr_id`, `country`, `name`, `full_name`) VALUES ('2200000100000', 'Россия', 'Барнаул', 'Алтайский край, Барнаул');");
        $this->addSql("INSERT INTO `customer_city` (`kladr_id`, `country`, `name`, `full_name`) VALUES ('2200000300000', 'Россия', 'Белокуриха', 'Алтайский край, Белокуриха');");
        $this->addSql("INSERT INTO `customer_city` (`kladr_id`, `country`, `name`, `full_name`) VALUES ('2200000400000', 'Россия', 'Бийск', 'Алтайский край, Бийск');");
        $this->addSql("INSERT INTO `customer_city` (`kladr_id`, `country`, `name`, `full_name`) VALUES ('2200000800000', 'Россия', 'Новоалтайск', 'Алтайский край, Новоалтайск');");
        $this->addSql("INSERT INTO `customer_city` (`kladr_id`, `country`, `name`, `full_name`) VALUES ('2200000900000', 'Россия', 'Рубцовск', 'Алтайский край, Рубцовск');");
        $this->addSql("INSERT INTO `customer_city` (`kladr_id`, `country`, `name`, `full_name`) VALUES ('2200001000000', 'Россия', 'Славгород', 'Алтайский край, Славгород');");
        $this->addSql("INSERT INTO `customer_city` (`kladr_id`, `country`, `name`, `full_name`) VALUES ('2200001100000', 'Россия', 'Заринск', 'Алтайский край, Заринск');");
        $this->addSql("INSERT INTO `customer_city` (`kladr_id`, `country`, `name`, `full_name`) VALUES ('2200900000100', 'Россия', 'с Волчиха', 'Алтайский край, р-н Волчихинский, с Волчиха');");
        $this->addSql("INSERT INTO `customer_city` (`kladr_id`, `country`, `name`, `full_name`) VALUES ('2201600000100', 'Россия', 'с Зональное', 'Алтайский край, р-н Зональный, с Зональное');");
        $this->addSql("INSERT INTO `customer_city` (`kladr_id`, `country`, `name`, `full_name`) VALUES ('2202000002700', 'Россия', 'п Украинский', 'Алтайский край, р-н Косихинский, п Украинский');");
        $this->addSql("INSERT INTO `customer_city` (`kladr_id`, `country`, `name`, `full_name`) VALUES ('2206000000100', 'Россия', 'с Шелаболиха', 'Алтайский край, р-н Шелаболихинский, с Шелаболиха');");
        $this->addSql("INSERT INTO `customer_city` (`kladr_id`, `country`, `name`, `full_name`) VALUES ('2300000100000', 'Россия', 'Краснодар', 'Краснодарский край, Краснодар');");
        $this->addSql("INSERT INTO `customer_city` (`kladr_id`, `country`, `name`, `full_name`) VALUES ('2300000300000', 'Россия', 'Геленджик', 'Краснодарский край, Геленджик');");
        $this->addSql("INSERT INTO `customer_city` (`kladr_id`, `country`, `name`, `full_name`) VALUES ('2300000600000', 'Россия', 'Новороссийск', 'Краснодарский край, Новороссийск');");
        $this->addSql("INSERT INTO `customer_city` (`kladr_id`, `country`, `name`, `full_name`) VALUES ('2300000700000', 'Россия', 'Сочи', 'Краснодарский край, Сочи');");
        $this->addSql("INSERT INTO `customer_city` (`kladr_id`, `country`, `name`, `full_name`) VALUES ('2300300100000', 'Россия', 'Анапа', 'Краснодарский край, р-н Анапский, Анапа');");
        $this->addSql("INSERT INTO `customer_city` (`kladr_id`, `country`, `name`, `full_name`) VALUES ('2300600100000', 'Россия', 'Белореченск', 'Краснодарский край, р-н Белореченский, Белореченск');");
        $this->addSql("INSERT INTO `customer_city` (`kladr_id`, `country`, `name`, `full_name`) VALUES ('2300900100000', 'Россия', 'Гулькевичи', 'Краснодарский край, р-н Гулькевичский, Гулькевичи');");
        $this->addSql("INSERT INTO `customer_city` (`kladr_id`, `country`, `name`, `full_name`) VALUES ('2301800100000', 'Россия', 'Крымск', 'Краснодарский край, р-н Крымский, Крымск');");
        $this->addSql("INSERT INTO `customer_city` (`kladr_id`, `country`, `name`, `full_name`) VALUES ('2302100100000', 'Россия', 'Лабинск', 'Краснодарский край, р-н Лабинский, Лабинск');");
        $this->addSql("INSERT INTO `customer_city` (`kladr_id`, `country`, `name`, `full_name`) VALUES ('2303600100000', 'Россия', 'Туапсе', 'Краснодарский край, р-н Туапсинский, Туапсе');");
        $this->addSql("INSERT INTO `customer_city` (`kladr_id`, `country`, `name`, `full_name`) VALUES ('2400000100000', 'Россия', 'Красноярск', 'Красноярский край, Красноярск');");
        $this->addSql("INSERT INTO `customer_city` (`kladr_id`, `country`, `name`, `full_name`) VALUES ('2400000900000', 'Россия', 'Норильск', 'Красноярский край, Норильск');");
        $this->addSql("INSERT INTO `customer_city` (`kladr_id`, `country`, `name`, `full_name`) VALUES ('2400001400000', 'Россия', 'Енисейск', 'Красноярский край, Енисейск');");
        $this->addSql("INSERT INTO `customer_city` (`kladr_id`, `country`, `name`, `full_name`) VALUES ('2400001700000', 'Россия', 'Минусинск', 'Красноярский край, Минусинск');");
        $this->addSql("INSERT INTO `customer_city` (`kladr_id`, `country`, `name`, `full_name`) VALUES ('2400001800000', 'Россия', 'Назарово', 'Красноярский край, Назарово');");
        $this->addSql("INSERT INTO `customer_city` (`kladr_id`, `country`, `name`, `full_name`) VALUES ('2500000100000', 'Россия', 'Владивосток', 'Приморский край, Владивосток');");
        $this->addSql("INSERT INTO `customer_city` (`kladr_id`, `country`, `name`, `full_name`) VALUES ('2500000400000', 'Россия', 'Находка', 'Приморский край, Находка');");
        $this->addSql("INSERT INTO `customer_city` (`kladr_id`, `country`, `name`, `full_name`) VALUES ('2500000600000', 'Россия', 'Фокино', 'Приморский край, Фокино');");
        $this->addSql("INSERT INTO `customer_city` (`kladr_id`, `country`, `name`, `full_name`) VALUES ('2500000700000', 'Россия', 'Большой Камень', 'Приморский край, Большой Камень');");
        $this->addSql("INSERT INTO `customer_city` (`kladr_id`, `country`, `name`, `full_name`) VALUES ('2500001000000', 'Россия', 'Спасск-Дальний', 'Приморский край, Спасск-Дальний');");
        $this->addSql("INSERT INTO `customer_city` (`kladr_id`, `country`, `name`, `full_name`) VALUES ('2500001100000', 'Россия', 'Уссурийск', 'Приморский край, Уссурийск');");
        $this->addSql("INSERT INTO `customer_city` (`kladr_id`, `country`, `name`, `full_name`) VALUES ('2500001200000', 'Россия', 'Лесозаводск', 'Приморский край, Лесозаводск');");
        $this->addSql("INSERT INTO `customer_city` (`kladr_id`, `country`, `name`, `full_name`) VALUES ('2500200000100', 'Россия', 'с Анучино', 'Приморский край, р-н Анучинский, с Анучино');");
        $this->addSql("INSERT INTO `customer_city` (`kladr_id`, `country`, `name`, `full_name`) VALUES ('2502200000100', 'Россия', 'с Хороль', 'Приморский край, р-н Хорольский, с Хороль');");
        $this->addSql("INSERT INTO `customer_city` (`kladr_id`, `country`, `name`, `full_name`) VALUES ('2600000100000', 'Россия', 'Ставрополь', 'Ставропольский край, Ставрополь');");
        $this->addSql("INSERT INTO `customer_city` (`kladr_id`, `country`, `name`, `full_name`) VALUES ('2600000300000', 'Россия', 'Железноводск', 'Ставропольский край, Железноводск');");
        $this->addSql("INSERT INTO `customer_city` (`kladr_id`, `country`, `name`, `full_name`) VALUES ('2600700100000', 'Россия', 'Буденновск', 'Ставропольский край, р-н Буденновский, Буденновск');");
        $this->addSql("INSERT INTO `customer_city` (`kladr_id`, `country`, `name`, `full_name`) VALUES ('2700000100000', 'Россия', 'Хабаровск', 'Хабаровский край, Хабаровск');");
        $this->addSql("INSERT INTO `customer_city` (`kladr_id`, `country`, `name`, `full_name`) VALUES ('2700000300000', 'Россия', 'Амурск', 'Хабаровский край, Амурск');");
        $this->addSql("INSERT INTO `customer_city` (`kladr_id`, `country`, `name`, `full_name`) VALUES ('2700000500000', 'Россия', 'Комсомольск-на-Амуре', 'Хабаровский край, Комсомольск-на-Амуре');");
        $this->addSql("INSERT INTO `customer_city` (`kladr_id`, `country`, `name`, `full_name`) VALUES ('2800000100000', 'Россия', 'Благовещенск', 'Амурская обл, Благовещенск');");
        $this->addSql("INSERT INTO `customer_city` (`kladr_id`, `country`, `name`, `full_name`) VALUES ('2900000100000', 'Россия', 'Архангельск', 'Архангельская обл, Архангельск');");
        $this->addSql("INSERT INTO `customer_city` (`kladr_id`, `country`, `name`, `full_name`) VALUES ('2900000200000', 'Россия', 'Мирный', 'Архангельская обл, Мирный');");
        $this->addSql("INSERT INTO `customer_city` (`kladr_id`, `country`, `name`, `full_name`) VALUES ('2900000400000', 'Россия', 'Северодвинск', 'Архангельская обл, Северодвинск');");
        $this->addSql("INSERT INTO `customer_city` (`kladr_id`, `country`, `name`, `full_name`) VALUES ('3100000100000', 'Россия', 'Белгород', 'Белгородская обл, Белгород');");
        $this->addSql("INSERT INTO `customer_city` (`kladr_id`, `country`, `name`, `full_name`) VALUES ('3100000200000', 'Россия', 'Старый Оскол', 'Белгородская обл, Старый Оскол');");
        $this->addSql("INSERT INTO `customer_city` (`kladr_id`, `country`, `name`, `full_name`) VALUES ('3101200100000', 'Россия', 'Бирюч', 'Белгородская обл, р-н Красногвардейский, Бирюч');");
        $this->addSql("INSERT INTO `customer_city` (`kladr_id`, `country`, `name`, `full_name`) VALUES ('3101900000100', 'Россия', 'п Чернянка', 'Белгородская обл, р-н Чернянский, п Чернянка');");
        $this->addSql("INSERT INTO `customer_city` (`kladr_id`, `country`, `name`, `full_name`) VALUES ('3200000100000', 'Россия', 'Брянск', 'Брянская обл, Брянск');");
        $this->addSql("INSERT INTO `customer_city` (`kladr_id`, `country`, `name`, `full_name`) VALUES ('3300000100000', 'Россия', 'Владимир', 'Владимирская обл, Владимир');");
        $this->addSql("INSERT INTO `customer_city` (`kladr_id`, `country`, `name`, `full_name`) VALUES ('3300000400000', 'Россия', 'Ковров', 'Владимирская обл, Ковров');");
        $this->addSql("INSERT INTO `customer_city` (`kladr_id`, `country`, `name`, `full_name`) VALUES ('3300500200000', 'Россия', 'Курлово', 'Владимирская обл, р-н Гусь-Хрустальный, Курлово');");
        $this->addSql("INSERT INTO `customer_city` (`kladr_id`, `country`, `name`, `full_name`) VALUES ('3300900100000', 'Россия', 'Кольчугино', 'Владимирская обл, р-н Кольчугинский, Кольчугино');");
        $this->addSql("INSERT INTO `customer_city` (`kladr_id`, `country`, `name`, `full_name`) VALUES ('3400000100000', 'Россия', 'Волгоград', 'Волгоградская обл, Волгоград');");
        $this->addSql("INSERT INTO `customer_city` (`kladr_id`, `country`, `name`, `full_name`) VALUES ('3400000200000', 'Россия', 'Волжский', 'Волгоградская обл, Волжский');");
        $this->addSql("INSERT INTO `customer_city` (`kladr_id`, `country`, `name`, `full_name`) VALUES ('3400500000100', 'Россия', 'рп Даниловка', 'Волгоградская обл, р-н Даниловский, рп Даниловка');");
        $this->addSql("INSERT INTO `customer_city` (`kladr_id`, `country`, `name`, `full_name`) VALUES ('3500000200000', 'Россия', 'Череповец', 'Вологодская обл, Череповец');");
        $this->addSql("INSERT INTO `customer_city` (`kladr_id`, `country`, `name`, `full_name`) VALUES ('3600000100000', 'Россия', 'Воронеж', 'Воронежская обл, Воронеж');");
        $this->addSql("INSERT INTO `customer_city` (`kladr_id`, `country`, `name`, `full_name`) VALUES ('3600000300000', 'Россия', 'Нововоронеж', 'Воронежская обл, Нововоронеж');");
        $this->addSql("INSERT INTO `customer_city` (`kladr_id`, `country`, `name`, `full_name`) VALUES ('3600200000100', 'Россия', 'пгт Анна', 'Воронежская обл, р-н Аннинский, пгт Анна');");
        $this->addSql("INSERT INTO `customer_city` (`kladr_id`, `country`, `name`, `full_name`) VALUES ('3600600100000', 'Россия', 'Бутурлиновка', 'Воронежская обл, р-н Бутурлиновский, Бутурлиновка');");
        $this->addSql("INSERT INTO `customer_city` (`kladr_id`, `country`, `name`, `full_name`) VALUES ('3601500100000', 'Россия', 'Лиски', 'Воронежская обл, р-н Лискинский, Лиски');");
        $this->addSql("INSERT INTO `customer_city` (`kladr_id`, `country`, `name`, `full_name`) VALUES ('3602100100000', 'Россия', 'Павловск', 'Воронежская обл, р-н Павловский, Павловск');");
        $this->addSql("INSERT INTO `customer_city` (`kladr_id`, `country`, `name`, `full_name`) VALUES ('3602800100000', 'Россия', 'Россошь', 'Воронежская обл, р-н Россошанский, Россошь');");
        $this->addSql("INSERT INTO `customer_city` (`kladr_id`, `country`, `name`, `full_name`) VALUES ('3700000100000', 'Россия', 'Иваново', 'Ивановская обл, Иваново');");
        $this->addSql("INSERT INTO `customer_city` (`kladr_id`, `country`, `name`, `full_name`) VALUES ('3701700100000', 'Россия', 'Тейково', 'Ивановская обл, р-н Тейковский, Тейково');");
        $this->addSql("INSERT INTO `customer_city` (`kladr_id`, `country`, `name`, `full_name`) VALUES ('3800000300000', 'Россия', 'Иркутск', 'Иркутская обл, Иркутск');");
        $this->addSql("INSERT INTO `customer_city` (`kladr_id`, `country`, `name`, `full_name`) VALUES ('3800000500000', 'Россия', 'Братск', 'Иркутская обл, Братск');");
        $this->addSql("INSERT INTO `customer_city` (`kladr_id`, `country`, `name`, `full_name`) VALUES ('3801800100000', 'Россия', 'Слюдянка', 'Иркутская обл, р-н Слюдянский, Слюдянка');");
        $this->addSql("INSERT INTO `customer_city` (`kladr_id`, `country`, `name`, `full_name`) VALUES ('3900000100000', 'Россия', 'Калининград', 'Калининградская обл, Калининград');");
        $this->addSql("INSERT INTO `customer_city` (`kladr_id`, `country`, `name`, `full_name`) VALUES ('4000000100000', 'Россия', 'Калуга', 'Калужская обл, Калуга');");
        $this->addSql("INSERT INTO `customer_city` (`kladr_id`, `country`, `name`, `full_name`) VALUES ('4000000200000', 'Россия', 'Обнинск', 'Калужская обл, Обнинск');");
        $this->addSql("INSERT INTO `customer_city` (`kladr_id`, `country`, `name`, `full_name`) VALUES ('4000600100000', 'Россия', 'Кондрово', 'Калужская обл, р-н Дзержинский, Кондрово');");
        $this->addSql("INSERT INTO `customer_city` (`kladr_id`, `country`, `name`, `full_name`) VALUES ('4001700100000', 'Россия', 'Мещовск', 'Калужская обл, р-н Мещовский, Мещовск');");
        $this->addSql("INSERT INTO `customer_city` (`kladr_id`, `country`, `name`, `full_name`) VALUES ('4200000900000', 'Россия', 'Кемерово', 'Кемеровская обл, Кемерово');");
        $this->addSql("INSERT INTO `customer_city` (`kladr_id`, `country`, `name`, `full_name`) VALUES ('4201100100000', 'Россия', 'пгт Промышленная', 'Кемеровская обл, р-н Промышленновский, пгт Промышленная');");
        $this->addSql("INSERT INTO `customer_city` (`kladr_id`, `country`, `name`, `full_name`) VALUES ('4300000100000', 'Россия', 'Киров', 'Кировская обл, Киров');");
        $this->addSql("INSERT INTO `customer_city` (`kladr_id`, `country`, `name`, `full_name`) VALUES ('4300000400000', 'Россия', 'Кирово-Чепецк', 'Кировская обл, Кирово-Чепецк');");
        $this->addSql("INSERT INTO `customer_city` (`kladr_id`, `country`, `name`, `full_name`) VALUES ('4301700100000', 'Россия', 'Луза', 'Кировская обл, р-н Лузский, Луза');");
        $this->addSql("INSERT INTO `customer_city` (`kladr_id`, `country`, `name`, `full_name`) VALUES ('4303100100000', 'Россия', 'Слободской', 'Кировская обл, р-н Слободской, Слободской');");
        $this->addSql("INSERT INTO `customer_city` (`kladr_id`, `country`, `name`, `full_name`) VALUES ('4400000300000', 'Россия', 'Кострома', 'Костромская обл, Кострома');");
        $this->addSql("INSERT INTO `customer_city` (`kladr_id`, `country`, `name`, `full_name`) VALUES ('4400300100000', 'Россия', 'Буй', 'Костромская обл, р-н Буйский, Буй');");
        $this->addSql("INSERT INTO `customer_city` (`kladr_id`, `country`, `name`, `full_name`) VALUES ('4401000100000', 'Россия', 'Мантурово', 'Костромская обл, р-н Мантуровский, Мантурово');");
        $this->addSql("INSERT INTO `customer_city` (`kladr_id`, `country`, `name`, `full_name`) VALUES ('4401300100000', 'Россия', 'Нерехта', 'Костромская обл, р-н Нерехтский, Нерехта');");
        $this->addSql("INSERT INTO `customer_city` (`kladr_id`, `country`, `name`, `full_name`) VALUES ('4500000100000', 'Россия', 'Курган', 'Курганская обл, Курган');");
        $this->addSql("INSERT INTO `customer_city` (`kladr_id`, `country`, `name`, `full_name`) VALUES ('4500000200000', 'Россия', 'Шадринск', 'Курганская обл, Шадринск');");
        $this->addSql("INSERT INTO `customer_city` (`kladr_id`, `country`, `name`, `full_name`) VALUES ('4600000100000', 'Россия', 'Курск', 'Курская обл, Курск');");
        $this->addSql("INSERT INTO `customer_city` (`kladr_id`, `country`, `name`, `full_name`) VALUES ('4700511600000', 'Россия', 'Кудрово', 'Ленинградская обл, р-н Всеволожский, Кудрово');");
        $this->addSql("INSERT INTO `customer_city` (`kladr_id`, `country`, `name`, `full_name`) VALUES ('4700600100000', 'Россия', 'Выборг', 'Ленинградская обл, р-н Выборгский, Выборг');");
        $this->addSql("INSERT INTO `customer_city` (`kladr_id`, `country`, `name`, `full_name`) VALUES ('4700900100000', 'Россия', 'Кириши', 'Ленинградская обл, р-н Киришский, Кириши');");
        $this->addSql("INSERT INTO `customer_city` (`kladr_id`, `country`, `name`, `full_name`) VALUES ('4701700100000', 'Россия', 'Тихвин', 'Ленинградская обл, р-н Тихвинский, Тихвин');");
        $this->addSql("INSERT INTO `customer_city` (`kladr_id`, `country`, `name`, `full_name`) VALUES ('4800000100000', 'Россия', 'Липецк', 'Липецкая обл, Липецк');");
        $this->addSql("INSERT INTO `customer_city` (`kladr_id`, `country`, `name`, `full_name`) VALUES ('4800000200000', 'Россия', 'Елец', 'Липецкая обл, Елец');");
        $this->addSql("INSERT INTO `customer_city` (`kladr_id`, `country`, `name`, `full_name`) VALUES ('5000000000800', 'Россия', 'п Власиха', 'Московская обл, п Власиха');");
        $this->addSql("INSERT INTO `customer_city` (`kladr_id`, `country`, `name`, `full_name`) VALUES ('5000000100000', 'Россия', 'Домодедово', 'Московская обл, Домодедово');");
        $this->addSql("INSERT INTO `customer_city` (`kladr_id`, `country`, `name`, `full_name`) VALUES ('5000000700000', 'Россия', 'Ивантеевка', 'Московская обл, Ивантеевка');");
        $this->addSql("INSERT INTO `customer_city` (`kladr_id`, `country`, `name`, `full_name`) VALUES ('5000000900000', 'Россия', 'Королев', 'Московская обл, Королев');");
        $this->addSql("INSERT INTO `customer_city` (`kladr_id`, `country`, `name`, `full_name`) VALUES ('5000001100000', 'Россия', 'Краснознаменск', 'Московская обл, Краснознаменск');");
        $this->addSql("INSERT INTO `customer_city` (`kladr_id`, `country`, `name`, `full_name`) VALUES ('5000001200000', 'Россия', 'Лобня', 'Московская обл, Лобня');");
        $this->addSql("INSERT INTO `customer_city` (`kladr_id`, `country`, `name`, `full_name`) VALUES ('5000001300000', 'Россия', 'Лыткарино', 'Московская обл, Лыткарино');");
        $this->addSql("INSERT INTO `customer_city` (`kladr_id`, `country`, `name`, `full_name`) VALUES ('5000001600000', 'Россия', 'Реутов', 'Московская обл, Реутов');");
        $this->addSql("INSERT INTO `customer_city` (`kladr_id`, `country`, `name`, `full_name`) VALUES ('5000002100000', 'Россия', 'Электросталь', 'Московская обл, Электросталь');");
        $this->addSql("INSERT INTO `customer_city` (`kladr_id`, `country`, `name`, `full_name`) VALUES ('5000002400000', 'Россия', 'Подольск', 'Московская обл, Подольск');");
        $this->addSql("INSERT INTO `customer_city` (`kladr_id`, `country`, `name`, `full_name`) VALUES ('5000002600000', 'Россия', 'Орехово-Зуево', 'Московская обл, Орехово-Зуево');");
        $this->addSql("INSERT INTO `customer_city` (`kladr_id`, `country`, `name`, `full_name`) VALUES ('5000002700000', 'Россия', 'Коломна', 'Московская обл, Коломна');");
        $this->addSql("INSERT INTO `customer_city` (`kladr_id`, `country`, `name`, `full_name`) VALUES ('5000002800000', 'Россия', 'Серпухов', 'Московская обл, Серпухов');");
        $this->addSql("INSERT INTO `customer_city` (`kladr_id`, `country`, `name`, `full_name`) VALUES ('5000002900000', 'Россия', 'Долгопрудный', 'Московская обл, Долгопрудный');");
        $this->addSql("INSERT INTO `customer_city` (`kladr_id`, `country`, `name`, `full_name`) VALUES ('5000003000000', 'Россия', 'Химки', 'Московская обл, Химки');");
        $this->addSql("INSERT INTO `customer_city` (`kladr_id`, `country`, `name`, `full_name`) VALUES ('5000003200000', 'Россия', 'Котельники', 'Московская обл, Котельники');");
        $this->addSql("INSERT INTO `customer_city` (`kladr_id`, `country`, `name`, `full_name`) VALUES ('5000003600000', 'Россия', 'Балашиха', 'Московская обл, Балашиха');");
        $this->addSql("INSERT INTO `customer_city` (`kladr_id`, `country`, `name`, `full_name`) VALUES ('5000004200000', 'Россия', 'рп Шаховская', 'Московская обл, рп Шаховская');");
        $this->addSql("INSERT INTO `customer_city` (`kladr_id`, `country`, `name`, `full_name`) VALUES ('5000004900000', 'Россия', 'Красногорск', 'Московская обл, Красногорск');");
        $this->addSql("INSERT INTO `customer_city` (`kladr_id`, `country`, `name`, `full_name`) VALUES ('5000005000000', 'Россия', 'Люберцы', 'Московская обл, Люберцы');");
        $this->addSql("INSERT INTO `customer_city` (`kladr_id`, `country`, `name`, `full_name`) VALUES ('5000005700000', 'Россия', 'Истра', 'Московская обл, Истра');");
        $this->addSql("INSERT INTO `customer_city` (`kladr_id`, `country`, `name`, `full_name`) VALUES ('5000006100000', 'Россия', 'Дмитров', 'Московская обл, Дмитров');");
        $this->addSql("INSERT INTO `customer_city` (`kladr_id`, `country`, `name`, `full_name`) VALUES ('5000400000800', 'Россия', 'пгт Белоозерский', 'Московская обл, р-н Воскресенский, пгт Белоозерский');");
        $this->addSql("INSERT INTO `customer_city` (`kladr_id`, `country`, `name`, `full_name`) VALUES ('5000900200000', 'Россия', 'Дедовск', 'Московская обл, р-н Истринский, Дедовск');");
        $this->addSql("INSERT INTO `customer_city` (`kladr_id`, `country`, `name`, `full_name`) VALUES ('5001200017300', 'Россия', 'городок Коломна-1', 'Московская обл, р-н Коломенский, городок Коломна-1');");
        $this->addSql("INSERT INTO `customer_city` (`kladr_id`, `country`, `name`, `full_name`) VALUES ('5002000200000', 'Россия', 'Апрелевка', 'Московская обл, р-н Наро-Фоминский, Апрелевка');");
        $this->addSql("INSERT INTO `customer_city` (`kladr_id`, `country`, `name`, `full_name`) VALUES ('5002200100000', 'Россия', 'Одинцово', 'Московская обл, р-н Одинцовский, Одинцово');");
        $this->addSql("INSERT INTO `customer_city` (`kladr_id`, `country`, `name`, `full_name`) VALUES ('5002200300000', 'Россия', 'Голицыно', 'Московская обл, р-н Одинцовский, Голицыно');");
        $this->addSql("INSERT INTO `customer_city` (`kladr_id`, `country`, `name`, `full_name`) VALUES ('5002200400000', 'Россия', 'Кубинка', 'Московская обл, р-н Одинцовский, Кубинка');");
        $this->addSql("INSERT INTO `customer_city` (`kladr_id`, `country`, `name`, `full_name`) VALUES ('5002700100000', 'Россия', 'Пушкино', 'Московская обл, р-н Пушкинский, Пушкино');");
        $this->addSql("INSERT INTO `customer_city` (`kladr_id`, `country`, `name`, `full_name`) VALUES ('5002800100000', 'Россия', 'Раменское', 'Московская обл, р-н Раменский, Раменское');");
        $this->addSql("INSERT INTO `customer_city` (`kladr_id`, `country`, `name`, `full_name`) VALUES ('5004000100000', 'Россия', 'Щелково', 'Московская обл, р-н Щелковский, Щелково');");
        $this->addSql("INSERT INTO `customer_city` (`kladr_id`, `country`, `name`, `full_name`) VALUES ('5100000000400', 'Россия', 'п Видяево', 'Мурманская обл, п Видяево');");
        $this->addSql("INSERT INTO `customer_city` (`kladr_id`, `country`, `name`, `full_name`) VALUES ('5100000100000', 'Россия', 'Мурманск', 'Мурманская обл, Мурманск');");
        $this->addSql("INSERT INTO `customer_city` (`kladr_id`, `country`, `name`, `full_name`) VALUES ('5100000300000', 'Россия', 'Заозерск', 'Мурманская обл, Заозерск');");
        $this->addSql("INSERT INTO `customer_city` (`kladr_id`, `country`, `name`, `full_name`) VALUES ('5100001000000', 'Россия', 'Полярный', 'Мурманская обл, Полярный');");
        $this->addSql("INSERT INTO `customer_city` (`kladr_id`, `country`, `name`, `full_name`) VALUES ('5100001100000', 'Россия', 'Североморск', 'Мурманская обл, Североморск');");
        $this->addSql("INSERT INTO `customer_city` (`kladr_id`, `country`, `name`, `full_name`) VALUES ('5200000100000', 'Россия', 'Нижний Новгород', 'Нижегородская обл, Нижний Новгород');");
        $this->addSql("INSERT INTO `customer_city` (`kladr_id`, `country`, `name`, `full_name`) VALUES ('5200000500000', 'Россия', 'Бор', 'Нижегородская обл, Бор');");
        $this->addSql("INSERT INTO `customer_city` (`kladr_id`, `country`, `name`, `full_name`) VALUES ('5200400100000', 'Россия', 'Балахна', 'Нижегородская обл, р-н Балахнинский, Балахна');");
        $this->addSql("INSERT INTO `customer_city` (`kladr_id`, `country`, `name`, `full_name`) VALUES ('5202700100000', 'Россия', 'Кстово', 'Нижегородская обл, р-н Кстовский, Кстово');");
        $this->addSql("INSERT INTO `customer_city` (`kladr_id`, `country`, `name`, `full_name`) VALUES ('5203200100000', 'Россия', 'Павлово', 'Нижегородская обл, р-н Павловский, Павлово');");
        $this->addSql("INSERT INTO `customer_city` (`kladr_id`, `country`, `name`, `full_name`) VALUES ('5400000100000', 'Россия', 'Новосибирск', 'Новосибирская обл, Новосибирск');");
        $this->addSql("INSERT INTO `customer_city` (`kladr_id`, `country`, `name`, `full_name`) VALUES ('5400600000100', 'Россия', 'с Довольное', 'Новосибирская обл, р-н Доволенский, с Довольное');");
        $this->addSql("INSERT INTO `customer_city` (`kladr_id`, `country`, `name`, `full_name`) VALUES ('5500000100000', 'Россия', 'Омск', 'Омская обл, Омск');");
        $this->addSql("INSERT INTO `customer_city` (`kladr_id`, `country`, `name`, `full_name`) VALUES ('5600000100000', 'Россия', 'Оренбург', 'Оренбургская обл, Оренбург');");
        $this->addSql("INSERT INTO `customer_city` (`kladr_id`, `country`, `name`, `full_name`) VALUES ('5601200000600', 'Россия', 'п Боровский', 'Оренбургская обл, р-н Бузулукский, п Боровский');");
        $this->addSql("INSERT INTO `customer_city` (`kladr_id`, `country`, `name`, `full_name`) VALUES ('5700000100000', 'Россия', 'Орёл', 'Орловская обл, Орёл');");
        $this->addSql("INSERT INTO `customer_city` (`kladr_id`, `country`, `name`, `full_name`) VALUES ('5800000100000', 'Россия', 'Пенза', 'Пензенская обл, Пенза');");
        $this->addSql("INSERT INTO `customer_city` (`kladr_id`, `country`, `name`, `full_name`) VALUES ('5900000100000', 'Россия', 'Пермь', 'Пермский край, Пермь');");
        $this->addSql("INSERT INTO `customer_city` (`kladr_id`, `country`, `name`, `full_name`) VALUES ('5900000200000', 'Россия', 'Березники', 'Пермский край, Березники');");
        $this->addSql("INSERT INTO `customer_city` (`kladr_id`, `country`, `name`, `full_name`) VALUES ('5900000500000', 'Россия', 'Губаха', 'Пермский край, Губаха');");
        $this->addSql("INSERT INTO `customer_city` (`kladr_id`, `country`, `name`, `full_name`) VALUES ('5900000900000', 'Россия', 'Кунгур', 'Пермский край, Кунгур');");
        $this->addSql("INSERT INTO `customer_city` (`kladr_id`, `country`, `name`, `full_name`) VALUES ('5900001100000', 'Россия', 'Соликамск', 'Пермский край, Соликамск');");
        $this->addSql("INSERT INTO `customer_city` (`kladr_id`, `country`, `name`, `full_name`) VALUES ('5900001300000', 'Россия', 'Чусовой', 'Пермский край, Чусовой');");
        $this->addSql("INSERT INTO `customer_city` (`kladr_id`, `country`, `name`, `full_name`) VALUES ('5900001400000', 'Россия', 'Кудымкар', 'Пермский край, Кудымкар');");
        $this->addSql("INSERT INTO `customer_city` (`kladr_id`, `country`, `name`, `full_name`) VALUES ('6000000100000', 'Россия', 'Псков', 'Псковская обл, Псков');");
        $this->addSql("INSERT INTO `customer_city` (`kladr_id`, `country`, `name`, `full_name`) VALUES ('6100000100000', 'Россия', 'Ростов-на-Дону', 'Ростовская обл, Ростов-на-Дону');");
        $this->addSql("INSERT INTO `customer_city` (`kladr_id`, `country`, `name`, `full_name`) VALUES ('6100000300000', 'Россия', 'Батайск', 'Ростовская обл, Батайск');");
        $this->addSql("INSERT INTO `customer_city` (`kladr_id`, `country`, `name`, `full_name`) VALUES ('6100000400000', 'Россия', 'Волгодонск', 'Ростовская обл, Волгодонск');");
        $this->addSql("INSERT INTO `customer_city` (`kladr_id`, `country`, `name`, `full_name`) VALUES ('6100000900000', 'Россия', 'Новочеркасск', 'Ростовская обл, Новочеркасск');");
        $this->addSql("INSERT INTO `customer_city` (`kladr_id`, `country`, `name`, `full_name`) VALUES ('6100001100000', 'Россия', 'Таганрог', 'Ростовская обл, Таганрог');");
        $this->addSql("INSERT INTO `customer_city` (`kladr_id`, `country`, `name`, `full_name`) VALUES ('6100001200000', 'Россия', 'Шахты', 'Ростовская обл, Шахты');");
        $this->addSql("INSERT INTO `customer_city` (`kladr_id`, `country`, `name`, `full_name`) VALUES ('6100001300000', 'Россия', 'Азов', 'Ростовская обл, Азов');");
        $this->addSql("INSERT INTO `customer_city` (`kladr_id`, `country`, `name`, `full_name`) VALUES ('6100500100000', 'Россия', 'Белая Калитва', 'Ростовская обл, р-н Белокалитвинский, Белая Калитва');");
        $this->addSql("INSERT INTO `customer_city` (`kladr_id`, `country`, `name`, `full_name`) VALUES ('6101100000100', 'Россия', 'ст-ца Егорлыкская', 'Ростовская обл, р-н Егорлыкский, ст-ца Егорлыкская');");
        $this->addSql("INSERT INTO `customer_city` (`kladr_id`, `country`, `name`, `full_name`) VALUES ('6101400000100', 'Россия', 'п Зимовники', 'Ростовская обл, р-н Зимовниковский, п Зимовники');");
        $this->addSql("INSERT INTO `customer_city` (`kladr_id`, `country`, `name`, `full_name`) VALUES ('6102200000100', 'Россия', 'п Матвеев Курган', 'Ростовская обл, р-н Матвеево-Курганский, п Матвеев Курган');");
        $this->addSql("INSERT INTO `customer_city` (`kladr_id`, `country`, `name`, `full_name`) VALUES ('6102600000100', 'Россия', 'с Чалтырь', 'Ростовская обл, р-н Мясниковский, с Чалтырь');");
        $this->addSql("INSERT INTO `customer_city` (`kladr_id`, `country`, `name`, `full_name`) VALUES ('6200000100000', 'Россия', 'Рязань', 'Рязанская обл, Рязань');");
        $this->addSql("INSERT INTO `customer_city` (`kladr_id`, `country`, `name`, `full_name`) VALUES ('6200000300000', 'Россия', 'Скопин', 'Рязанская обл, Скопин');");
        $this->addSql("INSERT INTO `customer_city` (`kladr_id`, `country`, `name`, `full_name`) VALUES ('6200000400000', 'Россия', 'Касимов', 'Рязанская обл, Касимов');");
        $this->addSql("INSERT INTO `customer_city` (`kladr_id`, `country`, `name`, `full_name`) VALUES ('6200500005400', 'Россия', 'рп Гусь-Железный', 'Рязанская обл, р-н Касимовский, рп Гусь-Железный');");
        $this->addSql("INSERT INTO `customer_city` (`kladr_id`, `country`, `name`, `full_name`) VALUES ('6200600024000', 'Россия', 'рп Тума', 'Рязанская обл, р-н Клепиковский, рп Тума');");
        $this->addSql("INSERT INTO `customer_city` (`kladr_id`, `country`, `name`, `full_name`) VALUES ('6201500100000', 'Россия', 'Ряжск', 'Рязанская обл, р-н Ряжский, Ряжск');");
        $this->addSql("INSERT INTO `customer_city` (`kladr_id`, `country`, `name`, `full_name`) VALUES ('6201600000100', 'Россия', 'рп Сапожок', 'Рязанская обл, р-н Сапожковский, рп Сапожок');");
        $this->addSql("INSERT INTO `customer_city` (`kladr_id`, `country`, `name`, `full_name`) VALUES ('6202000100000', 'Россия', 'Спасск-Рязанский', 'Рязанская обл, р-н Спасский, Спасск-Рязанский');");
        $this->addSql("INSERT INTO `customer_city` (`kladr_id`, `country`, `name`, `full_name`) VALUES ('6202400100000', 'Россия', 'Шацк', 'Рязанская обл, р-н Шацкий, Шацк');");
        $this->addSql("INSERT INTO `customer_city` (`kladr_id`, `country`, `name`, `full_name`) VALUES ('6300000100000', 'Россия', 'Самара', 'Самарская обл, Самара');");
        $this->addSql("INSERT INTO `customer_city` (`kladr_id`, `country`, `name`, `full_name`) VALUES ('6300000300000', 'Россия', 'Новокуйбышевск', 'Самарская обл, Новокуйбышевск');");
        $this->addSql("INSERT INTO `customer_city` (`kladr_id`, `country`, `name`, `full_name`) VALUES ('6300000600000', 'Россия', 'Чапаевск', 'Самарская обл, Чапаевск');");
        $this->addSql("INSERT INTO `customer_city` (`kladr_id`, `country`, `name`, `full_name`) VALUES ('6300000700000', 'Россия', 'Тольятти', 'Самарская обл, Тольятти');");
        $this->addSql("INSERT INTO `customer_city` (`kladr_id`, `country`, `name`, `full_name`) VALUES ('6400000100000', 'Россия', 'Саратов', 'Саратовская обл, Саратов');");
        $this->addSql("INSERT INTO `customer_city` (`kladr_id`, `country`, `name`, `full_name`) VALUES ('6400000400000', 'Россия', 'Балаково', 'Саратовская обл, Балаково');");
        $this->addSql("INSERT INTO `customer_city` (`kladr_id`, `country`, `name`, `full_name`) VALUES ('6400001300000', 'Россия', 'Энгельс', 'Саратовская обл, Энгельс');");
        $this->addSql("INSERT INTO `customer_city` (`kladr_id`, `country`, `name`, `full_name`) VALUES ('6500000100000', 'Россия', 'Южно-Сахалинск', 'Сахалинская обл, Южно-Сахалинск');");
        $this->addSql("INSERT INTO `customer_city` (`kladr_id`, `country`, `name`, `full_name`) VALUES ('6501600100000', 'Россия', 'Холмск', 'Сахалинская обл, р-н Холмский, Холмск');");
        $this->addSql("INSERT INTO `customer_city` (`kladr_id`, `country`, `name`, `full_name`) VALUES ('6600000001000', 'Россия', 'пгт Рефтинский', 'Свердловская обл, пгт Рефтинский');");
        $this->addSql("INSERT INTO `customer_city` (`kladr_id`, `country`, `name`, `full_name`) VALUES ('6600000100000', 'Россия', 'Екатеринбург', 'Свердловская обл, Екатеринбург');");
        $this->addSql("INSERT INTO `customer_city` (`kladr_id`, `country`, `name`, `full_name`) VALUES ('6600000200000', 'Россия', 'Асбест', 'Свердловская обл, Асбест');");
        $this->addSql("INSERT INTO `customer_city` (`kladr_id`, `country`, `name`, `full_name`) VALUES ('6600000300000', 'Россия', 'Березовский', 'Свердловская обл, Березовский');");
        $this->addSql("INSERT INTO `customer_city` (`kladr_id`, `country`, `name`, `full_name`) VALUES ('6600000400000', 'Россия', 'Верхняя Пышма', 'Свердловская обл, Верхняя Пышма');");
        $this->addSql("INSERT INTO `customer_city` (`kladr_id`, `country`, `name`, `full_name`) VALUES ('6600000400200', 'Россия', 'с Балтым', 'Свердловская обл, с Балтым');");
        $this->addSql("INSERT INTO `customer_city` (`kladr_id`, `country`, `name`, `full_name`) VALUES ('6600000900000', 'Россия', 'Кировград', 'Свердловская обл, Кировград');");
        $this->addSql("INSERT INTO `customer_city` (`kladr_id`, `country`, `name`, `full_name`) VALUES ('6600001000000', 'Россия', 'Краснотурьинск', 'Свердловская обл, Краснотурьинск');");
        $this->addSql("INSERT INTO `customer_city` (`kladr_id`, `country`, `name`, `full_name`) VALUES ('6600001500000', 'Россия', 'Новоуральск', 'Свердловская обл, Новоуральск');");
        $this->addSql("INSERT INTO `customer_city` (`kladr_id`, `country`, `name`, `full_name`) VALUES ('6600002200000', 'Россия', 'Каменск-Уральский', 'Свердловская обл, Каменск-Уральский');");
        $this->addSql("INSERT INTO `customer_city` (`kladr_id`, `country`, `name`, `full_name`) VALUES ('6600002300000', 'Россия', 'Нижний Тагил', 'Свердловская обл, Нижний Тагил');");
        $this->addSql("INSERT INTO `customer_city` (`kladr_id`, `country`, `name`, `full_name`) VALUES ('6600003400000', 'Россия', 'Серов', 'Свердловская обл, Серов');");
        $this->addSql("INSERT INTO `customer_city` (`kladr_id`, `country`, `name`, `full_name`) VALUES ('6600003800000', 'Россия', 'Среднеуральск', 'Свердловская обл, Среднеуральск');");
        $this->addSql("INSERT INTO `customer_city` (`kladr_id`, `country`, `name`, `full_name`) VALUES ('6600004100000', 'Россия', 'Дегтярск', 'Свердловская обл, Дегтярск');");
        $this->addSql("INSERT INTO `customer_city` (`kladr_id`, `country`, `name`, `full_name`) VALUES ('6602100100000', 'Россия', 'Реж', 'Свердловская обл, р-н Режевской, Реж');");
        $this->addSql("INSERT INTO `customer_city` (`kladr_id`, `country`, `name`, `full_name`) VALUES ('6602400100000', 'Россия', 'Сухой Лог', 'Свердловская обл, р-н Сухоложский, Сухой Лог');");
        $this->addSql("INSERT INTO `customer_city` (`kladr_id`, `country`, `name`, `full_name`) VALUES ('6700000300000', 'Россия', 'Смоленск', 'Смоленская обл, Смоленск');");
        $this->addSql("INSERT INTO `customer_city` (`kladr_id`, `country`, `name`, `full_name`) VALUES ('6700300100000', 'Россия', 'Вязьма', 'Смоленская обл, р-н Вяземский, Вязьма');");
        $this->addSql("INSERT INTO `customer_city` (`kladr_id`, `country`, `name`, `full_name`) VALUES ('6800000300000', 'Россия', 'Моршанск', 'Тамбовская обл, Моршанск');");
        $this->addSql("INSERT INTO `customer_city` (`kladr_id`, `country`, `name`, `full_name`) VALUES ('6800000400000', 'Россия', 'Тамбов', 'Тамбовская обл, Тамбов');");
        $this->addSql("INSERT INTO `customer_city` (`kladr_id`, `country`, `name`, `full_name`) VALUES ('6900000100000', 'Россия', 'Тверь', 'Тверская обл, Тверь');");
        $this->addSql("INSERT INTO `customer_city` (`kladr_id`, `country`, `name`, `full_name`) VALUES ('6900000200000', 'Россия', 'Торжок', 'Тверская обл, Торжок');");
        $this->addSql("INSERT INTO `customer_city` (`kladr_id`, `country`, `name`, `full_name`) VALUES ('6900000900000', 'Россия', 'Кашин', 'Тверская обл, Кашин');");
        $this->addSql("INSERT INTO `customer_city` (`kladr_id`, `country`, `name`, `full_name`) VALUES ('6900300100000', 'Россия', 'Бежецк', 'Тверская обл, р-н Бежецкий, Бежецк');");
        $this->addSql("INSERT INTO `customer_city` (`kladr_id`, `country`, `name`, `full_name`) VALUES ('6901100100000', 'Россия', 'Калязин', 'Тверская обл, р-н Калязинский, Калязин');");
        $this->addSql("INSERT INTO `customer_city` (`kladr_id`, `country`, `name`, `full_name`) VALUES ('6901500100000', 'Россия', 'Конаково', 'Тверская обл, р-н Конаковский, Конаково');");
        $this->addSql("INSERT INTO `customer_city` (`kladr_id`, `country`, `name`, `full_name`) VALUES ('6902000000100', 'Россия', 'пгт Максатиха', 'Тверская обл, р-н Максатихинский, пгт Максатиха');");
        $this->addSql("INSERT INTO `customer_city` (`kladr_id`, `country`, `name`, `full_name`) VALUES ('7000000100000', 'Россия', 'Томск', 'Томская обл, Томск');");
        $this->addSql("INSERT INTO `customer_city` (`kladr_id`, `country`, `name`, `full_name`) VALUES ('7100000100000', 'Россия', 'Тула', 'Тульская обл, Тула');");
        $this->addSql("INSERT INTO `customer_city` (`kladr_id`, `country`, `name`, `full_name`) VALUES ('7100000200000', 'Россия', 'Донской', 'Тульская обл, Донской');");
        $this->addSql("INSERT INTO `customer_city` (`kladr_id`, `country`, `name`, `full_name`) VALUES ('7100500100000', 'Россия', 'Богородицк', 'Тульская обл, р-н Богородицкий, Богородицк');");
        $this->addSql("INSERT INTO `customer_city` (`kladr_id`, `country`, `name`, `full_name`) VALUES ('7101700100000', 'Россия', 'Новомосковск', 'Тульская обл, р-н Новомосковский, Новомосковск');");
        $this->addSql("INSERT INTO `customer_city` (`kladr_id`, `country`, `name`, `full_name`) VALUES ('7102200100000', 'Россия', 'Узловая', 'Тульская обл, р-н Узловский, Узловая');");
        $this->addSql("INSERT INTO `customer_city` (`kladr_id`, `country`, `name`, `full_name`) VALUES ('7102400100000', 'Россия', 'Щекино', 'Тульская обл, р-н Щекинский, Щекино');");
        $this->addSql("INSERT INTO `customer_city` (`kladr_id`, `country`, `name`, `full_name`) VALUES ('7200000100000', 'Россия', 'Тюмень', 'Тюменская обл, Тюмень');");
        $this->addSql("INSERT INTO `customer_city` (`kladr_id`, `country`, `name`, `full_name`) VALUES ('7200000200000', 'Россия', 'Тобольск', 'Тюменская обл, Тобольск');");
        $this->addSql("INSERT INTO `customer_city` (`kladr_id`, `country`, `name`, `full_name`) VALUES ('7200000400000', 'Россия', 'Заводоуковск', 'Тюменская обл, Заводоуковск');");
        $this->addSql("INSERT INTO `customer_city` (`kladr_id`, `country`, `name`, `full_name`) VALUES ('7200000500000', 'Россия', 'Ялуторовск', 'Тюменская обл, Ялуторовск');");
        $this->addSql("INSERT INTO `customer_city` (`kladr_id`, `country`, `name`, `full_name`) VALUES ('7200100001200', 'Россия', 'рп Боровский', 'Тюменская обл, р-н Тюменский, рп Боровский');");
        $this->addSql("INSERT INTO `customer_city` (`kladr_id`, `country`, `name`, `full_name`) VALUES ('7201800000100', 'Россия', 'с Уват', 'Тюменская обл, р-н Уватский, с Уват');");
        $this->addSql("INSERT INTO `customer_city` (`kladr_id`, `country`, `name`, `full_name`) VALUES ('7300000100000', 'Россия', 'Ульяновск', 'Ульяновская обл, Ульяновск');");
        $this->addSql("INSERT INTO `customer_city` (`kladr_id`, `country`, `name`, `full_name`) VALUES ('7400000100000', 'Россия', 'Челябинск', 'Челябинская обл, Челябинск');");
        $this->addSql("INSERT INTO `customer_city` (`kladr_id`, `country`, `name`, `full_name`) VALUES ('7400000200000', 'Россия', 'Верхний Уфалей', 'Челябинская обл, Верхний Уфалей');");
        $this->addSql("INSERT INTO `customer_city` (`kladr_id`, `country`, `name`, `full_name`) VALUES ('7400000900000', 'Россия', 'Магнитогорск', 'Челябинская обл, Магнитогорск');");
        $this->addSql("INSERT INTO `customer_city` (`kladr_id`, `country`, `name`, `full_name`) VALUES ('7400001000000', 'Россия', 'Миасс', 'Челябинская обл, Миасс');");
        $this->addSql("INSERT INTO `customer_city` (`kladr_id`, `country`, `name`, `full_name`) VALUES ('7400001100000', 'Россия', 'Озерск', 'Челябинская обл, Озерск');");
        $this->addSql("INSERT INTO `customer_city` (`kladr_id`, `country`, `name`, `full_name`) VALUES ('7400001300000', 'Россия', 'Снежинск', 'Челябинская обл, Снежинск');");
        $this->addSql("INSERT INTO `customer_city` (`kladr_id`, `country`, `name`, `full_name`) VALUES ('7400001600000', 'Россия', 'Южноуральск', 'Челябинская обл, Южноуральск');");
        $this->addSql("INSERT INTO `customer_city` (`kladr_id`, `country`, `name`, `full_name`) VALUES ('7400200300000', 'Россия', 'Аша', 'Челябинская обл, р-н Ашинский, Аша');");
        $this->addSql("INSERT INTO `customer_city` (`kladr_id`, `country`, `name`, `full_name`) VALUES ('7402600000100', 'Россия', 'с Аргаяш', 'Челябинская обл, р-н Аргаяшский, с Аргаяш');");
        $this->addSql("INSERT INTO `customer_city` (`kladr_id`, `country`, `name`, `full_name`) VALUES ('7404500100000', 'Россия', 'Коркино', 'Челябинская обл, р-н Коркинский, Коркино');");
        $this->addSql("INSERT INTO `customer_city` (`kladr_id`, `country`, `name`, `full_name`) VALUES ('7500000100000', 'Россия', 'Чита', 'Забайкальский край, Чита');");
        $this->addSql("INSERT INTO `customer_city` (`kladr_id`, `country`, `name`, `full_name`) VALUES ('7500700000800', 'Россия', 'п/ст Даурия', 'Забайкальский край, р-н Забайкальский, п/ст Даурия');");
        $this->addSql("INSERT INTO `customer_city` (`kladr_id`, `country`, `name`, `full_name`) VALUES ('7600000100000', 'Россия', 'Ярославль', 'Ярославская обл, Ярославль');");
        $this->addSql("INSERT INTO `customer_city` (`kladr_id`, `country`, `name`, `full_name`) VALUES ('7600000200000', 'Россия', 'Переславль-Залесский', 'Ярославская обл, Переславль-Залесский');");
        $this->addSql("INSERT INTO `customer_city` (`kladr_id`, `country`, `name`, `full_name`) VALUES ('7600100060800', 'Россия', 'д Кузнечиха', 'Ярославская обл, р-н Ярославский, д Кузнечиха');");
        $this->addSql("INSERT INTO `customer_city` (`kladr_id`, `country`, `name`, `full_name`) VALUES ('7600600100000', 'Россия', 'Данилов', 'Ярославская обл, р-н Даниловский, Данилов');");
        $this->addSql("INSERT INTO `customer_city` (`kladr_id`, `country`, `name`, `full_name`) VALUES ('7601400100000', 'Россия', 'Ростов', 'Ярославская обл, р-н Ростовский, Ростов');");
        $this->addSql("INSERT INTO `customer_city` (`kladr_id`, `country`, `name`, `full_name`) VALUES ('7601500100000', 'Россия', 'Рыбинск', 'Ярославская обл, р-н Рыбинский, Рыбинск');");
        $this->addSql("INSERT INTO `customer_city` (`kladr_id`, `country`, `name`, `full_name`) VALUES ('7601600100000', 'Россия', 'Тутаев', 'Ярославская обл, р-н Тутаевский, Тутаев');");
        $this->addSql("INSERT INTO `customer_city` (`kladr_id`, `country`, `name`, `full_name`) VALUES ('7700000000000', 'Россия', 'Москва', 'Москва');");
        $this->addSql("INSERT INTO `customer_city` (`kladr_id`, `country`, `name`, `full_name`) VALUES ('7800000000000', 'Россия', 'Санкт-Петербург', 'Санкт-Петербург');");
        $this->addSql("INSERT INTO `customer_city` (`kladr_id`, `country`, `name`, `full_name`) VALUES ('7800000600000', 'Россия', 'Ломоносов', 'Ломоносов');");
        $this->addSql("INSERT INTO `customer_city` (`kladr_id`, `country`, `name`, `full_name`) VALUES ('7800000700000', 'Россия', 'Павловск', 'Павловск');");
        $this->addSql("INSERT INTO `customer_city` (`kladr_id`, `country`, `name`, `full_name`) VALUES ('7900000100000', 'Россия', 'Биробиджан', 'Еврейская Аобл, Биробиджан');");
        $this->addSql("INSERT INTO `customer_city` (`kladr_id`, `country`, `name`, `full_name`) VALUES ('8600000100000', 'Россия', 'Ханты-Мансийск', 'Ханты-Мансийский Автономный округ - Югра АО, Ханты-Мансийск');");
        $this->addSql("INSERT INTO `customer_city` (`kladr_id`, `country`, `name`, `full_name`) VALUES ('8600000200000', 'Россия', 'Когалым', 'Ханты-Мансийский Автономный округ - Югра АО, Когалым');");
        $this->addSql("INSERT INTO `customer_city` (`kladr_id`, `country`, `name`, `full_name`) VALUES ('8600000300000', 'Россия', 'Лангепас', 'Ханты-Мансийский Автономный округ - Югра АО, Лангепас');");
        $this->addSql("INSERT INTO `customer_city` (`kladr_id`, `country`, `name`, `full_name`) VALUES ('8600000500000', 'Россия', 'Нягань', 'Ханты-Мансийский Автономный округ - Югра АО, Нягань');");
        $this->addSql("INSERT INTO `customer_city` (`kladr_id`, `country`, `name`, `full_name`) VALUES ('8600000900000', 'Россия', 'Урай', 'Ханты-Мансийский Автономный округ - Югра АО, Урай');");
        $this->addSql("INSERT INTO `customer_city` (`kladr_id`, `country`, `name`, `full_name`) VALUES ('8600001000000', 'Россия', 'Сургут', 'Ханты-Мансийский Автономный округ - Югра АО, Сургут');");
        $this->addSql("INSERT INTO `customer_city` (`kladr_id`, `country`, `name`, `full_name`) VALUES ('8600001100000', 'Россия', 'Нижневартовск', 'Ханты-Мансийский Автономный округ - Югра АО, Нижневартовск');");
        $this->addSql("INSERT INTO `customer_city` (`kladr_id`, `country`, `name`, `full_name`) VALUES ('8600001400000', 'Россия', 'Нефтеюганск', 'Ханты-Мансийский Автономный округ - Югра АО, Нефтеюганск');");
        $this->addSql("INSERT INTO `customer_city` (`kladr_id`, `country`, `name`, `full_name`) VALUES ('8600400000100', 'Россия', 'пгт Междуреченский', 'Ханты-Мансийский Автономный округ - Югра АО, р-н Кондинский, пгт Междуреченский');");
        $this->addSql("INSERT INTO `customer_city` (`kladr_id`, `country`, `name`, `full_name`) VALUES ('8600600001300', 'Россия', 'пгт Излучинск', 'Ханты-Мансийский Автономный округ - Югра АО, р-н Нижневартовский, пгт Излучинск');");
        $this->addSql("INSERT INTO `customer_city` (`kladr_id`, `country`, `name`, `full_name`) VALUES ('8600900000400', 'Россия', 'пгт Белый Яр', 'Ханты-Мансийский Автономный округ - Югра АО, р-н Сургутский, пгт Белый Яр');");
        $this->addSql("INSERT INTO `customer_city` (`kladr_id`, `country`, `name`, `full_name`) VALUES ('8600900002800', 'Россия', 'с Угут', 'Ханты-Мансийский Автономный округ - Югра АО, р-н Сургутский, с Угут');");
        $this->addSql("INSERT INTO `customer_city` (`kladr_id`, `country`, `name`, `full_name`) VALUES ('8900000100000', 'Россия', 'Салехард', 'Ямало-Ненецкий АО, Салехард');");
        $this->addSql("INSERT INTO `customer_city` (`kladr_id`, `country`, `name`, `full_name`) VALUES ('8900000600000', 'Россия', 'Новый Уренгой', 'Ямало-Ненецкий АО, Новый Уренгой');");
        $this->addSql("INSERT INTO `customer_city` (`kladr_id`, `country`, `name`, `full_name`) VALUES ('8900000700000', 'Россия', 'Ноябрьск', 'Ямало-Ненецкий АО, Ноябрьск');");
        $this->addSql("INSERT INTO `customer_city` (`kladr_id`, `country`, `name`, `full_name`) VALUES ('9100001100000', 'Россия', 'Алушта', 'Крым Респ, Алушта');");
    }

    public function down(Schema $schema) : void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() !== 'mysql', 'Migration can only be executed safely on \'mysql\'.');
    }
}
