<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20190730191824 extends AbstractMigration
{
    public function getDescription() : string
    {
        return '';
    }

    public function up(Schema $schema) : void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() !== 'mysql', 'Migration can only be executed safely on \'mysql\'.');
    
        $this->addSql('ALTER TABLE `customers` ADD `old_specialization` VARCHAR(100) NULL DEFAULT NULL;');
        $this->addSql('UPDATE `customers` SET `old_specialization` = LOWER(TRIM(`specialty`));');
        $this->addSql("UPDATE `customers` SET `main_specialty_id` = 1 WHERE `old_specialization` = 'акушер' AND `main_specialty_id` IS NULL;");
        $this->addSql("UPDATE `customers` SET `main_specialty_id` = 2 WHERE `old_specialization` = 'акушер гинеколог' AND `main_specialty_id` IS NULL;");
        $this->addSql("UPDATE `customers` SET `main_specialty_id` = 2 WHERE `old_specialization` = 'акушер-гинеколог' AND `main_specialty_id` IS NULL;");
        $this->addSql("UPDATE `customers` SET `main_specialty_id` = 3 WHERE `old_specialization` = 'аллерголог' AND `main_specialty_id` IS NULL;");
        $this->addSql("UPDATE `customers` SET `main_specialty_id` = 12 WHERE `old_specialization` = 'аллерголог иммунолог' AND `main_specialty_id` IS NULL;");
        $this->addSql("UPDATE `customers` SET `main_specialty_id` = 12 WHERE `old_specialization` = 'аллерголог иммунолог, педиатр' AND `main_specialty_id` IS NULL;");
        $this->addSql("UPDATE `customers` SET `main_specialty_id` = 12 WHERE `old_specialization` = 'аллерголог имунолог' AND `main_specialty_id` IS NULL;");
        $this->addSql("UPDATE `customers` SET `main_specialty_id` = 12 WHERE `old_specialization` = 'аллерголог-иммунолог' AND `main_specialty_id` IS NULL;");
        $this->addSql("UPDATE `customers` SET `main_specialty_id` = 12 WHERE `old_specialization` = 'аллерголог-иммунолог, педиатр' AND `main_specialty_id` IS NULL;");
        $this->addSql("UPDATE `customers` SET `main_specialty_id` = 12 WHERE `old_specialization` = 'аллерголог-имунолог' AND `main_specialty_id` IS NULL;");
        $this->addSql("UPDATE `customers` SET `main_specialty_id` = 26 WHERE `old_specialization` = 'аллерголог, пульмонолог, педиатр' AND `main_specialty_id` IS NULL;");
        $this->addSql("UPDATE `customers` SET `main_specialty_id` = 3 WHERE `old_specialization` = 'аллергология и иммунология' AND `main_specialty_id` IS NULL;");
        $this->addSql("UPDATE `customers` SET `main_specialty_id` = 3 WHERE `old_specialization` = 'аллергология и иммунология, пульмонология' AND `main_specialty_id` IS NULL;");
        $this->addSql("UPDATE `customers` SET `main_specialty_id` = 3 WHERE `old_specialization` = 'аллергология иммунология' AND `main_specialty_id` IS NULL;");
        $this->addSql("UPDATE `customers` SET `main_specialty_id` = 3 WHERE `old_specialization` = 'аллергология-иммунология' AND `main_specialty_id` IS NULL;");
        $this->addSql("UPDATE `customers` SET `main_specialty_id` = 4 WHERE `old_specialization` = 'анестезиолог' AND `main_specialty_id` IS NULL;");
        $this->addSql("UPDATE `customers` SET `main_specialty_id` = 4 WHERE `old_specialization` = 'анестезиология и реаниматология' AND `main_specialty_id` IS NULL;");
        $this->addSql("UPDATE `customers` SET `main_specialty_id` = 36 WHERE `old_specialization` = 'ао вертекс' AND `main_specialty_id` IS NULL;");
        $this->addSql("UPDATE `customers` SET `main_specialty_id` = 18, `additional_specialty_id` = 12 WHERE `old_specialization` = 'ассист.каф.пед.' AND `main_specialty_id` IS NULL;");
        $this->addSql("UPDATE `customers` SET `main_specialty_id` = 36 WHERE `old_specialization` = 'ассистент' AND `main_specialty_id` IS NULL;");
        $this->addSql("UPDATE `customers` SET `main_specialty_id` = 36 WHERE `old_specialization` = 'вав омсп' AND `main_specialty_id` IS NULL;");
        $this->addSql("UPDATE `customers` SET `main_specialty_id` = 36 WHERE `old_specialization` = 'вип' AND `main_specialty_id` IS NULL;");
        $this->addSql("UPDATE `customers` SET `main_specialty_id` = 36 WHERE `old_specialization` = 'вкпк' AND `main_specialty_id` IS NULL;");
        $this->addSql("UPDATE `customers` SET `main_specialty_id` = 30 WHERE `old_specialization` = 'воп' AND `main_specialty_id` IS NULL;");
        $this->addSql("UPDATE `customers` SET `main_specialty_id` = 30 WHERE `old_specialization` = 'воп терапевт' AND `main_specialty_id` IS NULL;");
        $this->addSql("UPDATE `customers` SET `main_specialty_id` = 30 WHERE `old_specialization` = 'врач' AND `main_specialty_id` IS NULL;");
        $this->addSql("UPDATE `customers` SET `main_specialty_id` = 37 WHERE `old_specialization` = 'врач   педиатр' AND `main_specialty_id` IS NULL;");
        $this->addSql("UPDATE `customers` SET `main_specialty_id` = 22 WHERE `old_specialization` = 'врач  оториноларинголог' AND `main_specialty_id` IS NULL;");
        $this->addSql("UPDATE `customers` SET `main_specialty_id` = 37 WHERE `old_specialization` = 'врач  педиатр' AND `main_specialty_id` IS NULL;");
        $this->addSql("UPDATE `customers` SET `main_specialty_id` = 37 WHERE `old_specialization` = 'врач  педиатр участковый' AND `main_specialty_id` IS NULL;");
        $this->addSql("UPDATE `customers` SET `main_specialty_id` = 37 WHERE `old_specialization` = 'врач  педиатр, аллерголог' AND `main_specialty_id` IS NULL;");
        $this->addSql("UPDATE `customers` SET `main_specialty_id` = 37 WHERE `old_specialization` = 'врач - педиатр' AND `main_specialty_id` IS NULL;");
        $this->addSql("UPDATE `customers` SET `main_specialty_id` = 2 WHERE `old_specialization` = 'врач ак гин' AND `main_specialty_id` IS NULL;");
        $this->addSql("UPDATE `customers` SET `main_specialty_id` = 2 WHERE `old_specialization` = 'врач ак-гин' AND `main_specialty_id` IS NULL;");
        $this->addSql("UPDATE `customers` SET `main_specialty_id` = 2 WHERE `old_specialization` = 'врач акушер гинеколог' AND `main_specialty_id` IS NULL;");
        $this->addSql("UPDATE `customers` SET `main_specialty_id` = 2 WHERE `old_specialization` = 'врач акушер-гинеколог' AND `main_specialty_id` IS NULL;");
        $this->addSql("UPDATE `customers` SET `main_specialty_id` = 3 WHERE `old_specialization` = 'врач аллерголог' AND `main_specialty_id` IS NULL;");
        $this->addSql("UPDATE `customers` SET `main_specialty_id` = 13 WHERE `old_specialization` = 'врач инфекционист' AND `main_specialty_id` IS NULL;");
        $this->addSql("UPDATE `customers` SET `main_specialty_id` = 16 WHERE `old_specialization` = 'врач клинический фармаколог' AND `main_specialty_id` IS NULL;");
        $this->addSql("UPDATE `customers` SET `main_specialty_id` = 36 WHERE `old_specialization` = 'врач лечебник' AND `main_specialty_id` IS NULL;");
        $this->addSql("UPDATE `customers` SET `main_specialty_id` = 37 WHERE `old_specialization` = 'врач лфк, педиатрия' AND `main_specialty_id` IS NULL;");
        $this->addSql("UPDATE `customers` SET `main_specialty_id` = 36 WHERE `old_specialization` = 'врач неонатолог' AND `main_specialty_id` IS NULL;");
        $this->addSql("UPDATE `customers` SET `main_specialty_id` = 30 WHERE `old_specialization` = 'врач общей практики' AND `main_specialty_id` IS NULL;");
        $this->addSql("UPDATE `customers` SET `main_specialty_id` = 30 WHERE `old_specialization` = 'врач общей практики (семейная медицина), аллерголог иммунолог' AND `main_specialty_id` IS NULL;");
        $this->addSql("UPDATE `customers` SET `main_specialty_id` = 30 WHERE `old_specialization` = 'врач общей практики (семейная медицина), аллерголог-иммунолог' AND `main_specialty_id` IS NULL;");
        $this->addSql("UPDATE `customers` SET `main_specialty_id` = 30 WHERE `old_specialization` = 'врач общей практики, оториноларинголог' AND `main_specialty_id` IS NULL;");
        $this->addSql("UPDATE `customers` SET `main_specialty_id` = 30 WHERE `old_specialization` = 'врач овп' AND `main_specialty_id` IS NULL;");
        $this->addSql("UPDATE `customers` SET `main_specialty_id` = 30 WHERE `old_specialization` = 'врач оп' AND `main_specialty_id` IS NULL;");
        $this->addSql("UPDATE `customers` SET `main_specialty_id` = 36 WHERE `old_specialization` = 'врач осмп' AND `main_specialty_id` IS NULL;");
        $this->addSql("UPDATE `customers` SET `main_specialty_id` = 22 WHERE `old_specialization` = 'врач отоларинголог' AND `main_specialty_id` IS NULL;");
        $this->addSql("UPDATE `customers` SET `main_specialty_id` = 22 WHERE `old_specialization` = 'врач оториноларинголог' AND `main_specialty_id` IS NULL;");
        $this->addSql("UPDATE `customers` SET `main_specialty_id` = 37 WHERE `old_specialization` = 'врач педиатр' AND `main_specialty_id` IS NULL;");
        $this->addSql("UPDATE `customers` SET `main_specialty_id` = 37 WHERE `old_specialization` = 'врач педиатр выезлная бригада смп' AND `main_specialty_id` IS NULL;");
        $this->addSql("UPDATE `customers` SET `main_specialty_id` = 37 WHERE `old_specialization` = 'врач педиатр дерматолог' AND `main_specialty_id` IS NULL;");
        $this->addSql("UPDATE `customers` SET `main_specialty_id` = 37 WHERE `old_specialization` = 'врач педиатр скорой помощи' AND `main_specialty_id` IS NULL;");
        $this->addSql("UPDATE `customers` SET `main_specialty_id` = 37 WHERE `old_specialization` = 'врач педиатр участков.' AND `main_specialty_id` IS NULL;");
        $this->addSql("UPDATE `customers` SET `main_specialty_id` = 37 WHERE `old_specialization` = 'врач педиатр участковый' AND `main_specialty_id` IS NULL;");
        $this->addSql("UPDATE `customers` SET `main_specialty_id` = 37 WHERE `old_specialization` = 'врач педиатр школы' AND `main_specialty_id` IS NULL;");
        $this->addSql("UPDATE `customers` SET `main_specialty_id` = 37 WHERE `old_specialization` = 'врач педиатр-участковый' AND `main_specialty_id` IS NULL;");
        $this->addSql("UPDATE `customers` SET `main_specialty_id` = 36 WHERE `old_specialization` = 'врач по реабилитации' AND `main_specialty_id` IS NULL;");
        $this->addSql("UPDATE `customers` SET `main_specialty_id` = 26 WHERE `old_specialization` = 'врач пульмонолог' AND `main_specialty_id` IS NULL;");
        $this->addSql("UPDATE `customers` SET `main_specialty_id` = 30 WHERE `old_specialization` = 'врач терапевт' AND `main_specialty_id` IS NULL;");
        $this->addSql("UPDATE `customers` SET `main_specialty_id` = 30 WHERE `old_specialization` = 'врач терапевт участковый' AND `main_specialty_id` IS NULL;");
        $this->addSql("UPDATE `customers` SET `main_specialty_id` = 30 WHERE `old_specialization` = 'врач терапевт, врач гериатр' AND `main_specialty_id` IS NULL;");
        $this->addSql("UPDATE `customers` SET `main_specialty_id` = 36 WHERE `old_specialization` = 'врач эндоскопист' AND `main_specialty_id` IS NULL;");
        $this->addSql("UPDATE `customers` SET `main_specialty_id` = 30 WHERE `old_specialization` = 'врач nls' AND `main_specialty_id` IS NULL;");
        $this->addSql("UPDATE `customers` SET `main_specialty_id` = 22 WHERE `old_specialization` = 'врач- оториноларинголог' AND `main_specialty_id` IS NULL;");
        $this->addSql("UPDATE `customers` SET `main_specialty_id` = 37 WHERE `old_specialization` = 'врач- педиатр' AND `main_specialty_id` IS NULL;");
        $this->addSql("UPDATE `customers` SET `main_specialty_id` = 37 WHERE `old_specialization` = 'врач- педиатр участковый' AND `main_specialty_id` IS NULL;");
        $this->addSql("UPDATE `customers` SET `main_specialty_id` = 37 WHERE `old_specialization` = 'врач- педиатр, аллерголог' AND `main_specialty_id` IS NULL;");
        $this->addSql("UPDATE `customers` SET `main_specialty_id` = 16 WHERE `old_specialization` = 'врач-клинический фармаколог' AND `main_specialty_id` IS NULL;");
        $this->addSql("UPDATE `customers` SET `main_specialty_id` = 36 WHERE `old_specialization` = 'врач-лечебник' AND `main_specialty_id` IS NULL;");
        $this->addSql("UPDATE `customers` SET `main_specialty_id` = 36 WHERE `old_specialization` = 'врач-неонатолог' AND `main_specialty_id` IS NULL;");
        $this->addSql("UPDATE `customers` SET `main_specialty_id` = 22 WHERE `old_specialization` = 'врач-отоларинголог' AND `main_specialty_id` IS NULL;");
        $this->addSql("UPDATE `customers` SET `main_specialty_id` = 22 WHERE `old_specialization` = 'врач-оториноларинголог' AND `main_specialty_id` IS NULL;");
        $this->addSql("UPDATE `customers` SET `main_specialty_id` = 37 WHERE `old_specialization` = 'врач-педиатр' AND `main_specialty_id` IS NULL;");
        $this->addSql("UPDATE `customers` SET `main_specialty_id` = 37 WHERE `old_specialization` = 'врач-педиатр выезлная бригада смп' AND `main_specialty_id` IS NULL;");
        $this->addSql("UPDATE `customers` SET `main_specialty_id` = 37 WHERE `old_specialization` = 'врач-педиатр участковый' AND `main_specialty_id` IS NULL;");
        $this->addSql("UPDATE `customers` SET `main_specialty_id` = 37 WHERE `old_specialization` = 'врач-педиатр школы' AND `main_specialty_id` IS NULL;");
        $this->addSql("UPDATE `customers` SET `main_specialty_id` = 37 WHERE `old_specialization` = 'врач-педиатр-дерматолог' AND `main_specialty_id` IS NULL;");
        $this->addSql("UPDATE `customers` SET `main_specialty_id` = 26 WHERE `old_specialization` = 'врач-пульмонолог' AND `main_specialty_id` IS NULL;");
        $this->addSql("UPDATE `customers` SET `main_specialty_id` = 30 WHERE `old_specialization` = 'врач-терапевт' AND `main_specialty_id` IS NULL;");
        $this->addSql("UPDATE `customers` SET `main_specialty_id` = 30 WHERE `old_specialization` = 'врач-терапевт участковый' AND `main_specialty_id` IS NULL;");
        $this->addSql("UPDATE `customers` SET `main_specialty_id` = 30 WHERE `old_specialization` = 'врач-терапевт, врач-гериатр' AND `main_specialty_id` IS NULL;");
        $this->addSql("UPDATE `customers` SET `main_specialty_id` = 36 WHERE `old_specialization` = 'врач-эндоскопист' AND `main_specialty_id` IS NULL;");
        $this->addSql("UPDATE `customers` SET `main_specialty_id` = 37 WHERE `old_specialization` = 'врач—педиатр' AND `main_specialty_id` IS NULL;");
        $this->addSql("UPDATE `customers` SET `main_specialty_id` = 8 WHERE `old_specialization` = 'гастроэнтеролог' AND `main_specialty_id` IS NULL;");
        $this->addSql("UPDATE `customers` SET `main_specialty_id` = 8 WHERE `old_specialization` = 'гастроэнтеролог детский' AND `main_specialty_id` IS NULL;");
        $this->addSql("UPDATE `customers` SET `main_specialty_id` = 36 WHERE `old_specialization` = 'гл.врач' AND `main_specialty_id` IS NULL;");
        $this->addSql("UPDATE `customers` SET `main_specialty_id` = 11 WHERE `old_specialization` = 'дерматовенеролог' AND `main_specialty_id` IS NULL;");
        $this->addSql("UPDATE `customers` SET `main_specialty_id` = 11 WHERE `old_specialization` = 'дерматолог' AND `main_specialty_id` IS NULL;");
        $this->addSql("UPDATE `customers` SET `main_specialty_id` = 35 WHERE `old_specialization` = 'детская эндокринология, педиатрия' AND `main_specialty_id` IS NULL;");
        $this->addSql("UPDATE `customers` SET `main_specialty_id` = 20 WHERE `old_specialization` = 'детский онколог' AND `main_specialty_id` IS NULL;");
        $this->addSql("UPDATE `customers` SET `main_specialty_id` = 34 WHERE `old_specialization` = 'детский хирург' AND `main_specialty_id` IS NULL;");
        $this->addSql("UPDATE `customers` SET `main_specialty_id` = 18, `additional_specialty_id` = 6 WHERE `old_specialization` = 'доцент' AND `main_specialty_id` IS NULL;");
        $this->addSql("UPDATE `customers` SET `main_specialty_id` = 18, `additional_specialty_id` = 6 WHERE `old_specialization` = 'доцент каф. фтизиатрии' AND `main_specialty_id` IS NULL;");
        $this->addSql("UPDATE `customers` SET `main_specialty_id` = 36 WHERE `old_specialization` = 'другое' AND `main_specialty_id` IS NULL;");
        $this->addSql("UPDATE `customers` SET `main_specialty_id` = 36 WHERE `old_specialization` = 'зав. аптечным пунктом' AND `main_specialty_id` IS NULL;");
        $this->addSql("UPDATE `customers` SET `main_specialty_id` = 36 WHERE `old_specialization` = 'зав. детской поликлиники' AND `main_specialty_id` IS NULL;");
        $this->addSql("UPDATE `customers` SET `main_specialty_id` = 37 WHERE `old_specialization` = 'зав. дпо' AND `main_specialty_id` IS NULL;");
        $this->addSql("UPDATE `customers` SET `main_specialty_id` = 37 WHERE `old_specialization` = 'зав. кдо №1' AND `main_specialty_id` IS NULL;");
        $this->addSql("UPDATE `customers` SET `main_specialty_id` = 37 WHERE `old_specialization` = 'зав. кдо №2' AND `main_specialty_id` IS NULL;");
        $this->addSql("UPDATE `customers` SET `main_specialty_id` = 26 WHERE `old_specialization` = 'зав. отд. пульмонологии' AND `main_specialty_id` IS NULL;");
        $this->addSql("UPDATE `customers` SET `main_specialty_id` = 36 WHERE `old_specialization` = 'зав. отделением' AND `main_specialty_id` IS NULL;");
        $this->addSql("UPDATE `customers` SET `main_specialty_id` = 37 WHERE `old_specialization` = 'зав. педиатрическим отделением' AND `main_specialty_id` IS NULL;");
        $this->addSql("UPDATE `customers` SET `main_specialty_id` = 36 WHERE `old_specialization` = 'зав. поликлиники' AND `main_specialty_id` IS NULL;");
        $this->addSql("UPDATE `customers` SET `main_specialty_id` = 36 WHERE `old_specialization` = 'зав. поликлиникой' AND `main_specialty_id` IS NULL;");
        $this->addSql("UPDATE `customers` SET `main_specialty_id` = 30 WHERE `old_specialization` = 'зав. терапевтическим отд.' AND `main_specialty_id` IS NULL;");
        $this->addSql("UPDATE `customers` SET `main_specialty_id` = 30 WHERE `old_specialization` = 'зав. терапевтическим отделением' AND `main_specialty_id` IS NULL;");
        $this->addSql("UPDATE `customers` SET `main_specialty_id` = 36 WHERE `old_specialization` = 'зав.вр' AND `main_specialty_id` IS NULL;");
        $this->addSql("UPDATE `customers` SET `main_specialty_id` = 36 WHERE `old_specialization` = 'зав.каб.эвн' AND `main_specialty_id` IS NULL;");
        $this->addSql("UPDATE `customers` SET `main_specialty_id` = 22 WHERE `old_specialization` = 'зав.лор отделения' AND `main_specialty_id` IS NULL;");
        $this->addSql("UPDATE `customers` SET `main_specialty_id` = 36 WHERE `old_specialization` = 'зав.оппр' AND `main_specialty_id` IS NULL;");
        $this->addSql("UPDATE `customers` SET `main_specialty_id` = 36 WHERE `old_specialization` = 'зав.отд' AND `main_specialty_id` IS NULL;");
        $this->addSql("UPDATE `customers` SET `main_specialty_id` = 2 WHERE `old_specialization` = 'зав.отд. ак.и геник.' AND `main_specialty_id` IS NULL;");
        $this->addSql("UPDATE `customers` SET `main_specialty_id` = 26 WHERE `old_specialization` = 'зав.отд. пульмонол' AND `main_specialty_id` IS NULL;");
        $this->addSql("UPDATE `customers` SET `main_specialty_id` = 22 WHERE `old_specialization` = 'зав.отд.лор' AND `main_specialty_id` IS NULL;");
        $this->addSql("UPDATE `customers` SET `main_specialty_id` = 30 WHERE `old_specialization` = 'зав.отд.терапии' AND `main_specialty_id` IS NULL;");
        $this->addSql("UPDATE `customers` SET `main_specialty_id` = 30 WHERE `old_specialization` = 'зав.отд.терапии и воп' AND `main_specialty_id` IS NULL;");
        $this->addSql("UPDATE `customers` SET `main_specialty_id` = 30 WHERE `old_specialization` = 'зав.отделением терапевтическим' AND `main_specialty_id` IS NULL;");
        $this->addSql("UPDATE `customers` SET `main_specialty_id` = 37 WHERE `old_specialization` = 'зав.педиатр' AND `main_specialty_id` IS NULL;");
        $this->addSql("UPDATE `customers` SET `main_specialty_id` = 36 WHERE `old_specialization` = 'зав.пол ой' AND `main_specialty_id` IS NULL;");
        $this->addSql("UPDATE `customers` SET `main_specialty_id` = 36 WHERE `old_specialization` = 'зав.пол-ой' AND `main_specialty_id` IS NULL;");
        $this->addSql("UPDATE `customers` SET `main_specialty_id` = 36 WHERE `old_specialization` = 'зав.поликлиникой' AND `main_specialty_id` IS NULL;");
        $this->addSql("UPDATE `customers` SET `main_specialty_id` = 26 WHERE `old_specialization` = 'зав.пульм.отд.' AND `main_specialty_id` IS NULL;");
        $this->addSql("UPDATE `customers` SET `main_specialty_id` = 36 WHERE `old_specialization` = 'зав.сц' AND `main_specialty_id` IS NULL;");
        $this->addSql("UPDATE `customers` SET `main_specialty_id` = 30 WHERE `old_specialization` = 'зав.тер.отд' AND `main_specialty_id` IS NULL;");
        $this->addSql("UPDATE `customers` SET `main_specialty_id` = 36 WHERE `old_specialization` = 'зав.цен.зд' AND `main_specialty_id` IS NULL;");
        $this->addSql("UPDATE `customers` SET `main_specialty_id` = 36 WHERE `old_specialization` = 'заведующ.кабинетом' AND `main_specialty_id` IS NULL;");
        $this->addSql("UPDATE `customers` SET `main_specialty_id` = 36 WHERE `old_specialization` = 'заведующая' AND `main_specialty_id` IS NULL;");
        $this->addSql("UPDATE `customers` SET `main_specialty_id` = 37 WHERE `old_specialization` = 'заведующая педиатрическим отделением' AND `main_specialty_id` IS NULL;");
        $this->addSql("UPDATE `customers` SET `main_specialty_id` = 36 WHERE `old_specialization` = 'зам. гл. врача' AND `main_specialty_id` IS NULL;");
        $this->addSql("UPDATE `customers` SET `main_specialty_id` = 36 WHERE `old_specialization` = 'зам. главного врача' AND `main_specialty_id` IS NULL;");
        $this->addSql("UPDATE `customers` SET `main_specialty_id` = 36 WHERE `old_specialization` = 'зам. директора' AND `main_specialty_id` IS NULL;");
        $this->addSql("UPDATE `customers` SET `main_specialty_id` = 26 WHERE `old_specialization` = 'зам.гл.врача пол ки, пульмонолог' AND `main_specialty_id` IS NULL;");
        $this->addSql("UPDATE `customers` SET `main_specialty_id` = 26 WHERE `old_specialization` = 'зам.гл.врача пол-ки, пульмонолог' AND `main_specialty_id` IS NULL;");
        $this->addSql("UPDATE `customers` SET `main_specialty_id` = 36 WHERE `old_specialization` = 'зам.нач.по кэр' AND `main_specialty_id` IS NULL;");
        $this->addSql("UPDATE `customers` SET `main_specialty_id` = 36 WHERE `old_specialization` = 'интерн' AND `main_specialty_id` IS NULL;");
        $this->addSql("UPDATE `customers` SET `main_specialty_id` = 30 WHERE `old_specialization` = 'интерн терапевт' AND `main_specialty_id` IS NULL;");
        $this->addSql("UPDATE `customers` SET `main_specialty_id` = 13 WHERE `old_specialization` = 'инфекционист' AND `main_specialty_id` IS NULL;");
        $this->addSql("UPDATE `customers` SET `main_specialty_id` = 13 WHERE `old_specialization` = 'инфекционист, иммунолог аллерголог' AND `main_specialty_id` IS NULL;");
        $this->addSql("UPDATE `customers` SET `main_specialty_id` = 13 WHERE `old_specialization` = 'инфекционист, иммунолог-аллерголог' AND `main_specialty_id` IS NULL;");
        $this->addSql("UPDATE `customers` SET `main_specialty_id` = 13 WHERE `old_specialization` = 'инфекционные болезни' AND `main_specialty_id` IS NULL;");
        $this->addSql("UPDATE `customers` SET `main_specialty_id` = 14 WHERE `old_specialization` = 'кардио' AND `main_specialty_id` IS NULL;");
        $this->addSql("UPDATE `customers` SET `main_specialty_id` = 14 WHERE `old_specialization` = 'кардиолог' AND `main_specialty_id` IS NULL;");
        $this->addSql("UPDATE `customers` SET `main_specialty_id` = 36 WHERE `old_specialization` = 'клин.орд' AND `main_specialty_id` IS NULL;");
        $this->addSql("UPDATE `customers` SET `main_specialty_id` = 15 WHERE `old_specialization` = 'клиническая лабораторная диагностика' AND `main_specialty_id` IS NULL;");
        $this->addSql("UPDATE `customers` SET `main_specialty_id` = 16 WHERE `old_specialization` = 'клинический фармаколог' AND `main_specialty_id` IS NULL;");
        $this->addSql("UPDATE `customers` SET `main_specialty_id` = 36 WHERE `old_specialization` = 'колопроктолог' AND `main_specialty_id` IS NULL;");
        $this->addSql("UPDATE `customers` SET `main_specialty_id` = 36 WHERE `old_specialization` = 'консультант' AND `main_specialty_id` IS NULL;");
        $this->addSql("UPDATE `customers` SET `main_specialty_id` = 36 WHERE `old_specialization` = 'косметолог' AND `main_specialty_id` IS NULL;");
        $this->addSql("UPDATE `customers` SET `main_specialty_id` = 36 WHERE `old_specialization` = 'крп' AND `main_specialty_id` IS NULL;");
        $this->addSql("UPDATE `customers` SET `main_specialty_id` = 36 WHERE `old_specialization` = 'лечебное дело' AND `main_specialty_id` IS NULL;");
        $this->addSql("UPDATE `customers` SET `main_specialty_id` = 36 WHERE `old_specialization` = 'логопед' AND `main_specialty_id` IS NULL;");
        $this->addSql("UPDATE `customers` SET `main_specialty_id` = 22 WHERE `old_specialization` = 'лор' AND `main_specialty_id` IS NULL;");
        $this->addSql("UPDATE `customers` SET `main_specialty_id` = 22 WHERE `old_specialization` = 'лор врач' AND `main_specialty_id` IS NULL;");
        $this->addSql("UPDATE `customers` SET `main_specialty_id` = 22 WHERE `old_specialization` = 'лор сурдолог' AND `main_specialty_id` IS NULL;");
        $this->addSql("UPDATE `customers` SET `main_specialty_id` = 22 WHERE `old_specialization` = 'лор-врач' AND `main_specialty_id` IS NULL;");
        $this->addSql("UPDATE `customers` SET `main_specialty_id` = 22 WHERE `old_specialization` = 'лор-сурдолог' AND `main_specialty_id` IS NULL;");
        $this->addSql("UPDATE `customers` SET `main_specialty_id` = 36 WHERE `old_specialization` = 'м' AND `main_specialty_id` IS NULL;");
        $this->addSql("UPDATE `customers` SET `main_specialty_id` = 36 WHERE `old_specialization` = 'мед.пред' AND `main_specialty_id` IS NULL;");
        $this->addSql("UPDATE `customers` SET `main_specialty_id` = 32 WHERE `old_specialization` = 'медбрат' AND `main_specialty_id` IS NULL;");
        $this->addSql("UPDATE `customers` SET `main_specialty_id` = 17 WHERE `old_specialization` = 'медсестра' AND `main_specialty_id` IS NULL;");
        $this->addSql("UPDATE `customers` SET `main_specialty_id` = 36 WHERE `old_specialization` = 'менеджер' AND `main_specialty_id` IS NULL;");
        $this->addSql("UPDATE `customers` SET `main_specialty_id` = 36 WHERE `old_specialization` = 'начальник' AND `main_specialty_id` IS NULL;");
        $this->addSql("UPDATE `customers` SET `main_specialty_id` = 36 WHERE `old_specialization` = 'невролог' AND `main_specialty_id` IS NULL;");
        $this->addSql("UPDATE `customers` SET `main_specialty_id` = 37 WHERE `old_specialization` = 'невролог, педиатр' AND `main_specialty_id` IS NULL;");
        $this->addSql("UPDATE `customers` SET `main_specialty_id` = 36 WHERE `old_specialization` = 'неврология' AND `main_specialty_id` IS NULL;");
        $this->addSql("UPDATE `customers` SET `main_specialty_id` = 36 WHERE `old_specialization` = 'неонатолог' AND `main_specialty_id` IS NULL;");
        $this->addSql("UPDATE `customers` SET `main_specialty_id` = 36 WHERE `old_specialization` = 'неонатология' AND `main_specialty_id` IS NULL;");
        $this->addSql("UPDATE `customers` SET `main_specialty_id` = 36 WHERE `old_specialization` = 'общая врачебная практика' AND `main_specialty_id` IS NULL;");
        $this->addSql("UPDATE `customers` SET `main_specialty_id` = 36 WHERE `old_specialization` = 'общая практика' AND `main_specialty_id` IS NULL;");
        $this->addSql("UPDATE `customers` SET `main_specialty_id` = 36 WHERE `old_specialization` = 'общеврачебная практика' AND `main_specialty_id` IS NULL;");
        $this->addSql("UPDATE `customers` SET `main_specialty_id` = 22 WHERE `old_specialization` = 'олтоиноларингология' AND `main_specialty_id` IS NULL;");
        $this->addSql("UPDATE `customers` SET `main_specialty_id` = 21 WHERE `old_specialization` = 'организатор здравоохранения' AND `main_specialty_id` IS NULL;");
        $this->addSql("UPDATE `customers` SET `main_specialty_id` = 21 WHERE `old_specialization` = 'организация здравоохранения' AND `main_specialty_id` IS NULL;");
        $this->addSql("UPDATE `customers` SET `main_specialty_id` = 36 WHERE `old_specialization` = 'ординатор' AND `main_specialty_id` IS NULL;");
        $this->addSql("UPDATE `customers` SET `main_specialty_id` = 22 WHERE `old_specialization` = 'ординатор лор' AND `main_specialty_id` IS NULL;");
        $this->addSql("UPDATE `customers` SET `main_specialty_id` = 30 WHERE `old_specialization` = 'ординатор терапевт' AND `main_specialty_id` IS NULL;");
        $this->addSql("UPDATE `customers` SET `main_specialty_id` = 36 WHERE `old_specialization` = 'ординтор' AND `main_specialty_id` IS NULL;");
        $this->addSql("UPDATE `customers` SET `main_specialty_id` = 22 WHERE `old_specialization` = 'отларинголог' AND `main_specialty_id` IS NULL;");
        $this->addSql("UPDATE `customers` SET `main_specialty_id` = 22 WHERE `old_specialization` = 'отоларингодог' AND `main_specialty_id` IS NULL;");
        $this->addSql("UPDATE `customers` SET `main_specialty_id` = 22 WHERE `old_specialization` = 'отоларинголгия' AND `main_specialty_id` IS NULL;");
        $this->addSql("UPDATE `customers` SET `main_specialty_id` = 22 WHERE `old_specialization` = 'отоларинголог' AND `main_specialty_id` IS NULL;");
        $this->addSql("UPDATE `customers` SET `main_specialty_id` = 22 WHERE `old_specialization` = 'отоларингологи я' AND `main_specialty_id` IS NULL;");
        $this->addSql("UPDATE `customers` SET `main_specialty_id` = 22 WHERE `old_specialization` = 'отоларингологич' AND `main_specialty_id` IS NULL;");
        $this->addSql("UPDATE `customers` SET `main_specialty_id` = 22 WHERE `old_specialization` = 'отоларингология' AND `main_specialty_id` IS NULL;");
        $this->addSql("UPDATE `customers` SET `main_specialty_id` = 22 WHERE `old_specialization` = 'отоларинголол' AND `main_specialty_id` IS NULL;");
        $this->addSql("UPDATE `customers` SET `main_specialty_id` = 22 WHERE `old_specialization` = 'оториларинголог' AND `main_specialty_id` IS NULL;");
        $this->addSql("UPDATE `customers` SET `main_specialty_id` = 22 WHERE `old_specialization` = 'оториноалринголог' AND `main_specialty_id` IS NULL;");
        $this->addSql("UPDATE `customers` SET `main_specialty_id` = 22 WHERE `old_specialization` = 'оторинолариголог' AND `main_specialty_id` IS NULL;");
        $this->addSql("UPDATE `customers` SET `main_specialty_id` = 22 WHERE `old_specialization` = 'оториноларинголог' AND `main_specialty_id` IS NULL;");
        $this->addSql("UPDATE `customers` SET `main_specialty_id` = 22 WHERE `old_specialization` = 'оториноларинголог сурдолог' AND `main_specialty_id` IS NULL;");
        $this->addSql("UPDATE `customers` SET `main_specialty_id` = 22 WHERE `old_specialization` = 'оториноларинголог-сурдолог' AND `main_specialty_id` IS NULL;");
        $this->addSql("UPDATE `customers` SET `main_specialty_id` = 22 WHERE `old_specialization` = 'оториноларингологии' AND `main_specialty_id` IS NULL;");
        $this->addSql("UPDATE `customers` SET `main_specialty_id` = 22 WHERE `old_specialization` = 'оториноларингология' AND `main_specialty_id` IS NULL;");
        $this->addSql("UPDATE `customers` SET `main_specialty_id` = 22 WHERE `old_specialization` = 'оториноларингология, педиатрия' AND `main_specialty_id` IS NULL;");
        $this->addSql("UPDATE `customers` SET `main_specialty_id` = 22 WHERE `old_specialization` = 'оторинолярингология' AND `main_specialty_id` IS NULL;");
        $this->addSql("UPDATE `customers` SET `main_specialty_id` = 22 WHERE `old_specialization` = 'оторларингологияино' AND `main_specialty_id` IS NULL;");
        $this->addSql("UPDATE `customers` SET `main_specialty_id` = 22 WHERE `old_specialization` = 'отриноларинголог' AND `main_specialty_id` IS NULL;");
        $this->addSql("UPDATE `customers` SET `main_specialty_id` = 22 WHERE `old_specialization` = 'отриноларингология' AND `main_specialty_id` IS NULL;");
        $this->addSql("UPDATE `customers` SET `main_specialty_id` = 23 WHERE `old_specialization` = 'офтальмолог' AND `main_specialty_id` IS NULL;");
        $this->addSql("UPDATE `customers` SET `main_specialty_id` = 37 WHERE `old_specialization` = 'пед.дневн.стационара' AND `main_specialty_id` IS NULL;");
        $this->addSql("UPDATE `customers` SET `main_specialty_id` = 37 WHERE `old_specialization` = 'педиарт' AND `main_specialty_id` IS NULL;");
        $this->addSql("UPDATE `customers` SET `main_specialty_id` = 37 WHERE `old_specialization` = 'педиатоия' AND `main_specialty_id` IS NULL;");
        $this->addSql("UPDATE `customers` SET `main_specialty_id` = 37 WHERE `old_specialization` = 'педиатр' AND `main_specialty_id` IS NULL;");
        $this->addSql("UPDATE `customers` SET `main_specialty_id` = 19 WHERE `old_specialization` = 'педиатр  нефролог' AND `main_specialty_id` IS NULL;");
        $this->addSql("UPDATE `customers` SET `main_specialty_id` = 22 WHERE `old_specialization` = 'педиатр .отоларинголог' AND `main_specialty_id` IS NULL;");
        $this->addSql("UPDATE `customers` SET `main_specialty_id` = 3 WHERE `old_specialization` = 'педиатр аллерголог' AND `main_specialty_id` IS NULL;");
        $this->addSql("UPDATE `customers` SET `main_specialty_id` = 26 WHERE `old_specialization` = 'педиатр врач пульмонолог' AND `main_specialty_id` IS NULL;");
        $this->addSql("UPDATE `customers` SET `main_specialty_id` = 37 WHERE `old_specialization` = 'педиатр дшо' AND `main_specialty_id` IS NULL;");
        $this->addSql("UPDATE `customers` SET `main_specialty_id` = 37 WHERE `old_specialization` = 'педиатр психиатр психиатр нарколог' AND `main_specialty_id` IS NULL;");
        $this->addSql("UPDATE `customers` SET `main_specialty_id` = 37 WHERE `old_specialization` = 'педиатр психиатр психиатр-нарколог' AND `main_specialty_id` IS NULL;");
        $this->addSql("UPDATE `customers` SET `main_specialty_id` = 26 WHERE `old_specialization` = 'педиатр пульмонолог' AND `main_specialty_id` IS NULL;");
        $this->addSql("UPDATE `customers` SET `main_specialty_id` = 37 WHERE `old_specialization` = 'педиатр скорой мед.помощи' AND `main_specialty_id` IS NULL;");
        $this->addSql("UPDATE `customers` SET `main_specialty_id` = 37 WHERE `old_specialization` = 'педиатр спорт врач' AND `main_specialty_id` IS NULL;");
        $this->addSql("UPDATE `customers` SET `main_specialty_id` = 37 WHERE `old_specialization` = 'педиатр участковый' AND `main_specialty_id` IS NULL;");
        $this->addSql("UPDATE `customers` SET `main_specialty_id` = 37 WHERE `old_specialization` = 'педиатр я, узи' AND `main_specialty_id` IS NULL;");
        $this->addSql("UPDATE `customers` SET `main_specialty_id` = 19 WHERE `old_specialization` = 'педиатр- нефролог' AND `main_specialty_id` IS NULL;");
        $this->addSql("UPDATE `customers` SET `main_specialty_id` = 3 WHERE `old_specialization` = 'педиатр-аллерголог' AND `main_specialty_id` IS NULL;");
        $this->addSql("UPDATE `customers` SET `main_specialty_id` = 3 WHERE `old_specialization` = 'педиатр, аллерголог' AND `main_specialty_id` IS NULL;");
        $this->addSql("UPDATE `customers` SET `main_specialty_id` = 3 WHERE `old_specialization` = 'педиатр, аллерголог иммунолог' AND `main_specialty_id` IS NULL;");
        $this->addSql("UPDATE `customers` SET `main_specialty_id` = 3 WHERE `old_specialization` = 'педиатр, аллерголог иммунолог, воп' AND `main_specialty_id` IS NULL;");
        $this->addSql("UPDATE `customers` SET `main_specialty_id` = 3 WHERE `old_specialization` = 'педиатр, аллерголог-иммунолог' AND `main_specialty_id` IS NULL;");
        $this->addSql("UPDATE `customers` SET `main_specialty_id` = 3 WHERE `old_specialization` = 'педиатр, аллерголог-иммунолог, воп' AND `main_specialty_id` IS NULL;");
        $this->addSql("UPDATE `customers` SET `main_specialty_id` = 37 WHERE `old_specialization` = 'педиатр, врач общей практики, организатор здравоохранения' AND `main_specialty_id` IS NULL;");
        $this->addSql("UPDATE `customers` SET `main_specialty_id` = 8 WHERE `old_specialization` = 'педиатр, гастроэнтеролог' AND `main_specialty_id` IS NULL;");
        $this->addSql("UPDATE `customers` SET `main_specialty_id` = 8 WHERE `old_specialization` = 'педиатр, гастроэнтеролог, узи' AND `main_specialty_id` IS NULL;");
        $this->addSql("UPDATE `customers` SET `main_specialty_id` = 37 WHERE `old_specialization` = 'педиатр, диетолог' AND `main_specialty_id` IS NULL;");
        $this->addSql("UPDATE `customers` SET `main_specialty_id` = 13 WHERE `old_specialization` = 'педиатр, инфекционист' AND `main_specialty_id` IS NULL;");
        $this->addSql("UPDATE `customers` SET `main_specialty_id` = 37 WHERE `old_specialization` = 'педиатр, неонатолог' AND `main_specialty_id` IS NULL;");
        $this->addSql("UPDATE `customers` SET `main_specialty_id` = 19 WHERE `old_specialization` = 'педиатр, нефролог' AND `main_specialty_id` IS NULL;");
        $this->addSql("UPDATE `customers` SET `main_specialty_id` = 26 WHERE `old_specialization` = 'педиатр, пульмонолог' AND `main_specialty_id` IS NULL;");
        $this->addSql("UPDATE `customers` SET `main_specialty_id` = 33 WHERE `old_specialization` = 'педиатр, физиотерапевт' AND `main_specialty_id` IS NULL;");
        $this->addSql("UPDATE `customers` SET `main_specialty_id` = 22 WHERE `old_specialization` = 'педиатр,отоларинголог' AND `main_specialty_id` IS NULL;");
        $this->addSql("UPDATE `customers` SET `main_specialty_id` = 26 WHERE `old_specialization` = 'педиатр,пульмонолог' AND `main_specialty_id` IS NULL;");
        $this->addSql("UPDATE `customers` SET `main_specialty_id` = 37 WHERE `old_specialization` = 'педиатри' AND `main_specialty_id` IS NULL;");
        $this->addSql("UPDATE `customers` SET `main_specialty_id` = 37 WHERE `old_specialization` = 'педиатрич' AND `main_specialty_id` IS NULL;");
        $this->addSql("UPDATE `customers` SET `main_specialty_id` = 37 WHERE `old_specialization` = 'педиатрия' AND `main_specialty_id` IS NULL;");
        $this->addSql("UPDATE `customers` SET `main_specialty_id` = 19 WHERE `old_specialization` = 'педиатрия ,нефрология' AND `main_specialty_id` IS NULL;");
        $this->addSql("UPDATE `customers` SET `main_specialty_id` = 37 WHERE `old_specialization` = 'педиатрия неврология' AND `main_specialty_id` IS NULL;");
        $this->addSql("UPDATE `customers` SET `main_specialty_id` = 3 WHERE `old_specialization` = 'педиатрия, аллергология' AND `main_specialty_id` IS NULL;");
        $this->addSql("UPDATE `customers` SET `main_specialty_id` = 3 WHERE `old_specialization` = 'педиатрия, аллергология и иммунология' AND `main_specialty_id` IS NULL;");
        $this->addSql("UPDATE `customers` SET `main_specialty_id` = 8 WHERE `old_specialization` = 'педиатрия, гастроэнтерология' AND `main_specialty_id` IS NULL;");
        $this->addSql("UPDATE `customers` SET `main_specialty_id` = 9 WHERE `old_specialization` = 'педиатрия, гематология' AND `main_specialty_id` IS NULL;");
        $this->addSql("UPDATE `customers` SET `main_specialty_id` = 21 WHERE `old_specialization` = 'педиатрия, детская кардиология, организация здравоохранения и общественное здоровье' AND `main_specialty_id` IS NULL;");
        $this->addSql("UPDATE `customers` SET `main_specialty_id` = 14 WHERE `old_specialization` = 'педиатрия, детская кардиология, функциональная диагностика' AND `main_specialty_id` IS NULL;");
        $this->addSql("UPDATE `customers` SET `main_specialty_id` = 13 WHERE `old_specialization` = 'педиатрия, инфекционные болезни' AND `main_specialty_id` IS NULL;");
        $this->addSql("UPDATE `customers` SET `main_specialty_id` = 37 WHERE `old_specialization` = 'педиатрия, лфк' AND `main_specialty_id` IS NULL;");
        $this->addSql("UPDATE `customers` SET `main_specialty_id` = 37 WHERE `old_specialization` = 'педиатрия, неонатология' AND `main_specialty_id` IS NULL;");
        $this->addSql("UPDATE `customers` SET `main_specialty_id` = 19 WHERE `old_specialization` = 'педиатрия, нефрология' AND `main_specialty_id` IS NULL;");
        $this->addSql("UPDATE `customers` SET `main_specialty_id` = 37 WHERE `old_specialization` = 'педиатрия, общая врачебная практика' AND `main_specialty_id` IS NULL;");
        $this->addSql("UPDATE `customers` SET `main_specialty_id` = 23 WHERE `old_specialization` = 'педиатрия, офтальмология' AND `main_specialty_id` IS NULL;");
        $this->addSql("UPDATE `customers` SET `main_specialty_id` = 26 WHERE `old_specialization` = 'педиатрия, пульмонология' AND `main_specialty_id` IS NULL;");
        $this->addSql("UPDATE `customers` SET `main_specialty_id` = 26 WHERE `old_specialization` = 'педиатрия, пульмонология, гастроэнтерология' AND `main_specialty_id` IS NULL;");
        $this->addSql("UPDATE `customers` SET `main_specialty_id` = 30 WHERE `old_specialization` = 'педиатрия, терапия' AND `main_specialty_id` IS NULL;");
        $this->addSql("UPDATE `customers` SET `main_specialty_id` = 37 WHERE `old_specialization` = 'педиатрия, функциональная диагностика' AND `main_specialty_id` IS NULL;");
        $this->addSql("UPDATE `customers` SET `main_specialty_id` = 26 WHERE `old_specialization` = 'педиатрия,пульмонология' AND `main_specialty_id` IS NULL;");
        $this->addSql("UPDATE `customers` SET `main_specialty_id` = 35 WHERE `old_specialization` = 'педиатрия,эндокринология' AND `main_specialty_id` IS NULL;");
        $this->addSql("UPDATE `customers` SET `main_specialty_id` = 37 WHERE `old_specialization` = 'педитрия' AND `main_specialty_id` IS NULL;");
        $this->addSql("UPDATE `customers` SET `main_specialty_id` = 37 WHERE `old_specialization` = 'пелиатр' AND `main_specialty_id` IS NULL;");
        $this->addSql("UPDATE `customers` SET `main_specialty_id` = 36 WHERE `old_specialization` = 'преподаватель' AND `main_specialty_id` IS NULL;");
        $this->addSql("UPDATE `customers` SET `main_specialty_id` = 24 WHERE `old_specialization` = 'провизор' AND `main_specialty_id` IS NULL;");
        $this->addSql("UPDATE `customers` SET `main_specialty_id` = 18, `additional_specialty_id` = 15 WHERE `old_specialization` = 'профессор' AND `main_specialty_id` IS NULL;");
        $this->addSql("UPDATE `customers` SET `main_specialty_id` = 36 WHERE `old_specialization` = 'профпатолог' AND `main_specialty_id` IS NULL;");
        $this->addSql("UPDATE `customers` SET `main_specialty_id` = 36 WHERE `old_specialization` = 'психолог' AND `main_specialty_id` IS NULL;");
        $this->addSql("UPDATE `customers` SET `main_specialty_id` = 26 WHERE `old_specialization` = 'пульмонолог' AND `main_specialty_id` IS NULL;");
        $this->addSql("UPDATE `customers` SET `main_specialty_id` = 26 WHERE `old_specialization` = 'пульмонолог, аллерголог иммунолог' AND `main_specialty_id` IS NULL;");
        $this->addSql("UPDATE `customers` SET `main_specialty_id` = 26 WHERE `old_specialization` = 'пульмонолог, аллерголог-иммунолог' AND `main_specialty_id` IS NULL;");
        $this->addSql("UPDATE `customers` SET `main_specialty_id` = 26 WHERE `old_specialization` = 'пульмонолог.  педиатр.' AND `main_specialty_id` IS NULL;");
        $this->addSql("UPDATE `customers` SET `main_specialty_id` = 26 WHERE `old_specialization` = 'пульмонология' AND `main_specialty_id` IS NULL;");
        $this->addSql("UPDATE `customers` SET `main_specialty_id` = 26 WHERE `old_specialization` = 'пульмонология, педиатрия' AND `main_specialty_id` IS NULL;");
        $this->addSql("UPDATE `customers` SET `main_specialty_id` = 36 WHERE `old_specialization` = 'радиология' AND `main_specialty_id` IS NULL;");
        $this->addSql("UPDATE `customers` SET `main_specialty_id` = 36 WHERE `old_specialization` = 'разработчик' AND `main_specialty_id` IS NULL;");
        $this->addSql("UPDATE `customers` SET `main_specialty_id` = 27 WHERE `old_specialization` = 'реаниматолог' AND `main_specialty_id` IS NULL;");
        $this->addSql("UPDATE `customers` SET `main_specialty_id` = 28 WHERE `old_specialization` = 'ревматолог' AND `main_specialty_id` IS NULL;");
        $this->addSql("UPDATE `customers` SET `main_specialty_id` = 29 WHERE `old_specialization` = 'рентгенолог' AND `main_specialty_id` IS NULL;");
        $this->addSql("UPDATE `customers` SET `main_specialty_id` = 36 WHERE `old_specialization` = 'рук. проекта пс' AND `main_specialty_id` IS NULL;");
        $this->addSql("UPDATE `customers` SET `main_specialty_id` = 36 WHERE `old_specialization` = 'руководитель бизнес подразделения' AND `main_specialty_id` IS NULL;");
        $this->addSql("UPDATE `customers` SET `main_specialty_id` = 36 WHERE `old_specialization` = 'руководитель бизнес-подразделения' AND `main_specialty_id` IS NULL;");
        $this->addSql("UPDATE `customers` SET `main_specialty_id` = 36 WHERE `old_specialization` = 'с' AND `main_specialty_id` IS NULL;");
        $this->addSql("UPDATE `customers` SET `main_specialty_id` = 6 WHERE `old_specialization` = 'скорая помощь' AND `main_specialty_id` IS NULL;");
        $this->addSql("UPDATE `customers` SET `main_specialty_id` = 36 WHERE `old_specialization` = 'специалист' AND `main_specialty_id` IS NULL;");
        $this->addSql("UPDATE `customers` SET `main_specialty_id` = 36 WHERE `old_specialization` = 'студент' AND `main_specialty_id` IS NULL;");
        $this->addSql("UPDATE `customers` SET `main_specialty_id` = 36 WHERE `old_specialization` = 'студент 3 курса медицинского факультета нгу' AND `main_specialty_id` IS NULL;");
        $this->addSql("UPDATE `customers` SET `main_specialty_id` = 37 WHERE `old_specialization` = 'студент 5 курса педиатрического факультета' AND `main_specialty_id` IS NULL;");
        $this->addSql("UPDATE `customers` SET `main_specialty_id` = 36 WHERE `old_specialization` = 'студентка' AND `main_specialty_id` IS NULL;");
        $this->addSql("UPDATE `customers` SET `main_specialty_id` = 36 WHERE `old_specialization` = 'студентка 6 курс ягму' AND `main_specialty_id` IS NULL;");
        $this->addSql("UPDATE `customers` SET `main_specialty_id` = 36 WHERE `old_specialization` = 'субординатор' AND `main_specialty_id` IS NULL;");
        $this->addSql("UPDATE `customers` SET `main_specialty_id` = 36 WHERE `old_specialization` = 'сурдолог' AND `main_specialty_id` IS NULL;");
        $this->addSql("UPDATE `customers` SET `main_specialty_id` = 22 WHERE `old_specialization` = 'сурдолог  оториноларинголог' AND `main_specialty_id` IS NULL;");
        $this->addSql("UPDATE `customers` SET `main_specialty_id` = 22 WHERE `old_specialization` = 'сурдолог отоларинголог' AND `main_specialty_id` IS NULL;");
        $this->addSql("UPDATE `customers` SET `main_specialty_id` = 22 WHERE `old_specialization` = 'сурдолог оторинголог' AND `main_specialty_id` IS NULL;");
        $this->addSql("UPDATE `customers` SET `main_specialty_id` = 22 WHERE `old_specialization` = 'сурдолог оториноларинголог' AND `main_specialty_id` IS NULL;");
        $this->addSql("UPDATE `customers` SET `main_specialty_id` = 22 WHERE `old_specialization` = 'сурдолог- оториноларинголог' AND `main_specialty_id` IS NULL;");
        $this->addSql("UPDATE `customers` SET `main_specialty_id` = 22 WHERE `old_specialization` = 'сурдолог-отоларинголог' AND `main_specialty_id` IS NULL;");
        $this->addSql("UPDATE `customers` SET `main_specialty_id` = 22 WHERE `old_specialization` = 'сурдолог-оторинголог' AND `main_specialty_id` IS NULL;");
        $this->addSql("UPDATE `customers` SET `main_specialty_id` = 22 WHERE `old_specialization` = 'сурдолог-оториноларинголог' AND `main_specialty_id` IS NULL;");
        $this->addSql("UPDATE `customers` SET `main_specialty_id` = 36 WHERE `old_specialization` = 'сурдология' AND `main_specialty_id` IS NULL;");
        $this->addSql("UPDATE `customers` SET `main_specialty_id` = 22 WHERE `old_specialization` = 'сурдология оториноларингология' AND `main_specialty_id` IS NULL;");
        $this->addSql("UPDATE `customers` SET `main_specialty_id` = 22 WHERE `old_specialization` = 'сурдология-оториноларингология' AND `main_specialty_id` IS NULL;");
        $this->addSql("UPDATE `customers` SET `main_specialty_id` = 36 WHERE `old_specialization` = 'т' AND `main_specialty_id` IS NULL;");
        $this->addSql("UPDATE `customers` SET `main_specialty_id` = 30 WHERE `old_specialization` = 'тарапия' AND `main_specialty_id` IS NULL;");
        $this->addSql("UPDATE `customers` SET `main_specialty_id` = 30 WHERE `old_specialization` = 'терапевт' AND `main_specialty_id` IS NULL;");
        $this->addSql("UPDATE `customers` SET `main_specialty_id` = 30 WHERE `old_specialization` = 'терапевт гастроэнтеролог' AND `main_specialty_id` IS NULL;");
        $this->addSql("UPDATE `customers` SET `main_specialty_id` = 30 WHERE `old_specialization` = 'терапевт пульмонолог' AND `main_specialty_id` IS NULL;");
        $this->addSql("UPDATE `customers` SET `main_specialty_id` = 30 WHERE `old_specialization` = 'терапевт участковый' AND `main_specialty_id` IS NULL;");
        $this->addSql("UPDATE `customers` SET `main_specialty_id` = 8 WHERE `old_specialization` = 'терапевт-гастроэнтеролог' AND `main_specialty_id` IS NULL;");
        $this->addSql("UPDATE `customers` SET `main_specialty_id` = 26 WHERE `old_specialization` = 'терапевт-пульмонолог' AND `main_specialty_id` IS NULL;");
        $this->addSql("UPDATE `customers` SET `main_specialty_id` = 30 WHERE `old_specialization` = 'терапевт, гастроэнтеролог' AND `main_specialty_id` IS NULL;");
        $this->addSql("UPDATE `customers` SET `main_specialty_id` = 30 WHERE `old_specialization` = 'терапевт,аллерголог' AND `main_specialty_id` IS NULL;");
        $this->addSql("UPDATE `customers` SET `main_specialty_id` = 30 WHERE `old_specialization` = 'терапия' AND `main_specialty_id` IS NULL;");
        $this->addSql("UPDATE `customers` SET `main_specialty_id` = 30 WHERE `old_specialization` = 'терапия рентгенология' AND `main_specialty_id` IS NULL;");
        $this->addSql("UPDATE `customers` SET `main_specialty_id` = 30 WHERE `old_specialization` = 'терапия-рентгенология' AND `main_specialty_id` IS NULL;");
        $this->addSql("UPDATE `customers` SET `main_specialty_id` = 30 WHERE `old_specialization` = 'терапия, акушерство гинекология' AND `main_specialty_id` IS NULL;");
        $this->addSql("UPDATE `customers` SET `main_specialty_id` = 30 WHERE `old_specialization` = 'терапия, акушерство-гинекология' AND `main_specialty_id` IS NULL;");
        $this->addSql("UPDATE `customers` SET `main_specialty_id` = 30 WHERE `old_specialization` = 'терапия, аллегология иммунология' AND `main_specialty_id` IS NULL;");
        $this->addSql("UPDATE `customers` SET `main_specialty_id` = 30 WHERE `old_specialization` = 'терапия, аллегология-иммунология' AND `main_specialty_id` IS NULL;");
        $this->addSql("UPDATE `customers` SET `main_specialty_id` = 30 WHERE `old_specialization` = 'терапия, диетология' AND `main_specialty_id` IS NULL;");
        $this->addSql("UPDATE `customers` SET `main_specialty_id` = 30 WHERE `old_specialization` = 'терапия, организация здравоохранения' AND `main_specialty_id` IS NULL;");
        $this->addSql("UPDATE `customers` SET `main_specialty_id` = 30 WHERE `old_specialization` = 'терапия,эндокринология' AND `main_specialty_id` IS NULL;");
        $this->addSql("UPDATE `customers` SET `main_specialty_id` = 36 WHERE `old_specialization` = 'травматолог' AND `main_specialty_id` IS NULL;");
        $this->addSql("UPDATE `customers` SET `main_specialty_id` = 17 WHERE `old_specialization` = 'тритон медсестра' AND `main_specialty_id` IS NULL;");
        $this->addSql("UPDATE `customers` SET `main_specialty_id` = 36 WHERE `old_specialization` = 'умывальников начальник' AND `main_specialty_id` IS NULL;");
        $this->addSql("UPDATE `customers` SET `main_specialty_id` = 36 WHERE `old_specialization` = 'уролог' AND `main_specialty_id` IS NULL;");
        $this->addSql("UPDATE `customers` SET `main_specialty_id` = 37 WHERE `old_specialization` = 'уч.врач педиатр' AND `main_specialty_id` IS NULL;");
        $this->addSql("UPDATE `customers` SET `main_specialty_id` = 37 WHERE `old_specialization` = 'уч.врач-педиатр' AND `main_specialty_id` IS NULL;");
        $this->addSql("UPDATE `customers` SET `main_specialty_id` = 37 WHERE `old_specialization` = 'уч.пед' AND `main_specialty_id` IS NULL;");
        $this->addSql("UPDATE `customers` SET `main_specialty_id` = 37 WHERE `old_specialization` = 'уч.педиатр' AND `main_specialty_id` IS NULL;");
        $this->addSql("UPDATE `customers` SET `main_specialty_id` = 30 WHERE `old_specialization` = 'уч.тер' AND `main_specialty_id` IS NULL;");
        $this->addSql("UPDATE `customers` SET `main_specialty_id` = 30 WHERE `old_specialization` = 'уч.терапевт' AND `main_specialty_id` IS NULL;");
        $this->addSql("UPDATE `customers` SET `main_specialty_id` = 37 WHERE `old_specialization` = 'участ.педиатр' AND `main_specialty_id` IS NULL;");
        $this->addSql("UPDATE `customers` SET `main_specialty_id` = 30 WHERE `old_specialization` = 'участ.терапевт' AND `main_specialty_id` IS NULL;");
        $this->addSql("UPDATE `customers` SET `main_specialty_id` = 37 WHERE `old_specialization` = 'участковый врач педиатр' AND `main_specialty_id` IS NULL;");
        $this->addSql("UPDATE `customers` SET `main_specialty_id` = 37 WHERE `old_specialization` = 'участковый врач-педиатр' AND `main_specialty_id` IS NULL;");
        $this->addSql("UPDATE `customers` SET `main_specialty_id` = 37 WHERE `old_specialization` = 'участковый педиатр' AND `main_specialty_id` IS NULL;");
        $this->addSql("UPDATE `customers` SET `main_specialty_id` = 37 WHERE `old_specialization` = 'участковый педиатр,аллерголог' AND `main_specialty_id` IS NULL;");
        $this->addSql("UPDATE `customers` SET `main_specialty_id` = 30 WHERE `old_specialization` = 'участковый терапевт' AND `main_specialty_id` IS NULL;");
        $this->addSql("UPDATE `customers` SET `main_specialty_id` = 31 WHERE `old_specialization` = 'фармацевт' AND `main_specialty_id` IS NULL;");
        $this->addSql("UPDATE `customers` SET `main_specialty_id` = 32 WHERE `old_specialization` = 'фельдшер' AND `main_specialty_id` IS NULL;");
        $this->addSql("UPDATE `customers` SET `main_specialty_id` = 32 WHERE `old_specialization` = 'фельдшер лечебное дело' AND `main_specialty_id` IS NULL;");
        $this->addSql("UPDATE `customers` SET `main_specialty_id` = 32 WHERE `old_specialization` = 'фельдшер педиатр' AND `main_specialty_id` IS NULL;");
        $this->addSql("UPDATE `customers` SET `main_specialty_id` = 32 WHERE `old_specialization` = 'фельдшер педиатрического участка' AND `main_specialty_id` IS NULL;");
        $this->addSql("UPDATE `customers` SET `main_specialty_id` = 32 WHERE `old_specialization` = 'фельдшер скорой помощи' AND `main_specialty_id` IS NULL;");
        $this->addSql("UPDATE `customers` SET `main_specialty_id` = 32 WHERE `old_specialization` = 'фельдшер то2' AND `main_specialty_id` IS NULL;");
        $this->addSql("UPDATE `customers` SET `main_specialty_id` = 32 WHERE `old_specialization` = 'фельдшер-педиатр' AND `main_specialty_id` IS NULL;");
        $this->addSql("UPDATE `customers` SET `main_specialty_id` = 33 WHERE `old_specialization` = 'физиотерапевт' AND `main_specialty_id` IS NULL;");
        $this->addSql("UPDATE `customers` SET `main_specialty_id` = 33 WHERE `old_specialization` = 'физиотерапевт, врач по медицинской реабилитации' AND `main_specialty_id` IS NULL;");
        $this->addSql("UPDATE `customers` SET `main_specialty_id` = 33 WHERE `old_specialization` = 'физиотерапия' AND `main_specialty_id` IS NULL;");
        $this->addSql("UPDATE `customers` SET `main_specialty_id` = 22 WHERE `old_specialization` = 'фониатр' AND `main_specialty_id` IS NULL;");
        $this->addSql("UPDATE `customers` SET `main_specialty_id` = 36 WHERE `old_specialization` = 'фтизиатр' AND `main_specialty_id` IS NULL;");
        $this->addSql("UPDATE `customers` SET `main_specialty_id` = 36 WHERE `old_specialization` = 'фтизиопедиатр' AND `main_specialty_id` IS NULL;");
        $this->addSql("UPDATE `customers` SET `main_specialty_id` = 33 WHERE `old_specialization` = 'функциональная диагностика' AND `main_specialty_id` IS NULL;");
        $this->addSql("UPDATE `customers` SET `main_specialty_id` = 34 WHERE `old_specialization` = 'хирург' AND `main_specialty_id` IS NULL;");
        $this->addSql("UPDATE `customers` SET `main_specialty_id` = 30 WHERE `old_specialization` = 'цеховый терапевт' AND `main_specialty_id` IS NULL;");
        $this->addSql("UPDATE `customers` SET `main_specialty_id` = 35 WHERE `old_specialization` = 'эндокринолог' AND `main_specialty_id` IS NULL;");
        $this->addSql("UPDATE `customers` SET `main_specialty_id` = 35 WHERE `old_specialization` = 'эндокринология, педиатрия, терапия' AND `main_specialty_id` IS NULL;");
        $this->addSql("UPDATE `customers` SET `main_specialty_id` = 36 WHERE `old_specialization` = 'эпидемиолог' AND `main_specialty_id` IS NULL;");
        $this->addSql("UPDATE `customers` SET `main_specialty_id` = 36 WHERE `old_specialization` = 'cтудент' AND `main_specialty_id` IS NULL;");
        $this->addSql("UPDATE `customers` SET `main_specialty_id` = 1 WHERE `old_specialization` = 'frkvdbg' AND `main_specialty_id` IS NULL;");
        $this->addSql("UPDATE `customers` SET `main_specialty_id` = 37 WHERE `old_specialization` = 'gtlbfnhbz' AND `main_specialty_id` IS NULL;");
        $this->addSql("UPDATE `customers` SET `main_specialty_id` = 36 WHERE `main_specialty_id` IS NULL;");
        $this->addSql("DELETE FROM `customers` WHERE `old_specialization` = 'asulyananahit@yandex.ru' AND `main_specialty_id` IS NULL;");
    }

    public function down(Schema $schema) : void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() !== 'mysql', 'Migration can only be executed safely on \'mysql\'.');
    
        $this->addSql('ALTER TABLE `customers` DROP `old_specialization`;');
    }
}
