parameters:
    # Adds a fallback DATABASE_URL if the env var is not set.
    # This allows you to run cache:warmup even if your
    # environment variables are not available yet.
    # You should not need to change this value.
    env(DATABASE_URL): ''

doctrine:
    dbal:
        # configure these for your database server
        driver: 'pdo_mysql'
        server_version: '5.6'
        charset: utf8mb4
        default_table_options:
            charset: utf8mb4
            collate: utf8mb4_unicode_ci

        url: '%env(resolve:DATABASE_URL)%'
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true
        mappings:
            Domain:
                is_bundle: false
                type: xml
                dir: '%kernel.project_dir%/config/doctrine/domain'
                prefix: 'App\Domain\Entity'
                alias: Domain
            Customer:
                is_bundle: false
                type: xml
                dir: '%kernel.project_dir%/config/doctrine/customer'
                prefix: 'App\Domain\Entity\Customer'
                alias: Customer
            Conference:
                is_bundle: false
                type: xml
                dir: '%kernel.project_dir%/config/doctrine/conference'
                prefix: 'App\Domain\Entity\Conference'
                alias: Conference
            Module:
                is_bundle: false
                type: xml
                dir: '%kernel.project_dir%/config/doctrine/module'
                prefix: 'App\Domain\Entity\Module'
                alias: Module
            Article:
                is_bundle: false
                type: xml
                dir: '%kernel.project_dir%/config/doctrine/article'
                prefix: 'App\Domain\Entity\Article'
                alias: Article
            ClinicalAnalysis:
                is_bundle: false
                type: xml
                dir: '%kernel.project_dir%/config/doctrine/clinical_analysis'
                prefix: 'App\Domain\Entity\ClinicalAnalysis'
                alias: ClinicalAnalysis
            News:
                is_bundle: false
                type: xml
                dir: '%kernel.project_dir%/config/doctrine/news'
                prefix: 'App\Domain\Entity\News'
                alias: News
            Banner:
                is_bundle: false
                type: xml
                dir: '%kernel.project_dir%/config/doctrine/banner'
                prefix: 'App\Domain\Entity\Banner'
                alias: Banner
            AdvertBanner:
                is_bundle: false
                type: xml
                dir: '%kernel.project_dir%/config/doctrine/advert_banner'
                prefix: 'App\Domain\Entity\AdvertBanner'
                alias: AdvertBanner
            PresidiumMember:
                is_bundle: false
                type: xml
                dir: '%kernel.project_dir%/config/doctrine/presidium'
                prefix: 'App\Domain\Entity\PresidiumMember'
                alias: PresidiumMember
            Document:
                is_bundle: false
                type: xml
                dir: '%kernel.project_dir%/config/doctrine/document'
                prefix: 'App\Domain\Entity\Document'
                alias: Document
            Direction:
                is_bundle: false
                type: xml
                dir: '%kernel.project_dir%/config/doctrine/direction'
                prefix: 'App\Domain\Entity\Direction'
                alias: Direction
            User:
                is_bundle: false
                type: xml
                dir: '%kernel.project_dir%/config/doctrine/user'
                prefix: 'App\Domain\Interactor\User'
                alias: User
            Webinar:
                is_bundle: false
                type: xml
                dir: '%kernel.project_dir%/config/doctrine/webinar'
                prefix: 'App\Webinar'
                alias: Webinar
            Entity:
                is_bundle: false
                type: xml
                dir: '%kernel.project_dir%/config/doctrine/entity'
                prefix: 'App\Entity'
                alias: Entity
            MainSpecialty:
                is_bundle: false
                type: xml
                dir: '%kernel.project_dir%/config/doctrine/specialty'
                prefix: 'App\Domain\Entity\Specialty'
                alias: MainSpecialty
