monolog:
    handlers:
        main:
            type: fingers_crossed
            action_level: error
            handler: grouped
            excluded_404s:
                # regex: exclude all 404 errors from the logs
                - ^/
            channels: ["!confirmSend"]

        grouped:
            type: group
            members: [nested, deduplicated]

        nested:
            type: stream
            path: "%kernel.logs_dir%/%kernel.environment%.log"
            level: debug

        deduplicated:
            type: deduplication
            handler: swift

        swift:
            type: swift_mailer
            from_email: '%env(LOG_MAIL_FROM)%'
            to_email: '%env(LOG_MAIL_TO)%'
            subject: 'An Error Occurred! %%message%%'
            level: error
            formatter: monolog.formatter.html
            content_type: text/html

        console:
            type: console
            process_psr_3_messages: false
            channels: ["!event", "!doctrine", "!confirmSend"]

        deprecation:
            type: stream
            path: "%kernel.logs_dir%/%kernel.environment%.deprecations.log"

        deprecation_filter:
            type: filter
            handler: deprecation
            max_level: info
            channels: ["php"]

        confirmation_email:
            type: stream
            path: "%kernel.logs_dir%/%kernel.environment%.confirmation_emails_send.log"
            level: debug
            channels: confirmSend

        webinar_reminder_email:
            type: stream
            path: "%kernel.logs_dir%/%kernel.environment%.webinar_reminder_emails_send.log"
            level: debug
            channels: webinarReminder